package network.crypta.clients.fcp;

import network.crypta.node.Node;
import network.crypta.support.SimpleFieldSet;

/**
 * Base type for FCP messages generated by the node and delivered to a client endpoint.
 *
 * <p>{@code FCPResponse} bridges internal node components and the FCP wire protocol by wrapping all
 * response attributes inside a {@link SimpleFieldSet}. Subclasses populate the field set with their
 * specific keys before streaming the structure back to the client connection. Typical producers are
 * request handlers that assemble the payload immediately before flushing it to the socket, so
 * instances usually exist only for the duration of a single outbound write.
 *
 * <p>The class assumes a single-threaded lifecycle: callers build and serialize the response on the
 * same thread without reusing it afterward. No internal synchronization is provided, so sharing an
 * instance across concurrent writers requires external locking. In return, the type remains very
 * lightweight and avoids unnecessary defensive copying when encoding outbound protocol frames.
 *
 * <ul>
 *   <li><strong>Responsibilities:</strong> hold metadata common to responses, enforce identifier
 *       propagation, and expose the name for routing/logging.
 *   <li><strong>Notable behavior:</strong> {@link #run(FCPConnectionHandler, Node)} always signals
 *       an error if invoked because responses are node-originated only.
 * </ul>
 *
 * @see FCPMessage
 * @see FCPConnectionHandler
 */
public abstract class FCPResponse extends FCPMessage {

  /**
   * Core field set tracking the serialized representation of this response message on the wire. The
   * reference is initialized once in the constructor and never reassigned, but the contained
   * key/value pairs remain mutable so subclasses can append protocol-specific entries right up
   * until the response is emitted to the client connection.
   */
  protected final SimpleFieldSet fs;

  /**
   * Creates a response scaffold tied to the supplied FCP identifier.
   *
   * <p>The constructor eagerly allocates the backing {@link SimpleFieldSet} so subclasses gain a
   * ready-to-use structure for inserting headers and payload metadata. When the identifier argument
   * is {@code null}, the {@code IDENTIFIER} field is intentionally omitted, mirroring legacy FCP
   * semantics where correlation is optional for fire-and-forget events. Non-null identifiers are
   * stored verbatim, allowing downstream code to correlate replies with the originating request
   * without touching transport-level envelopes.
   *
   * @param fcpIdentifier Unique token string linking replies to requests; null omits IDENTIFIER
   *     field entry.
   */
  protected FCPResponse(String fcpIdentifier) {
    fs = new SimpleFieldSet(true);
    fs.putOverwrite(IDENTIFIER, fcpIdentifier);
  }

  /**
   * Returns the mutable field set that ultimately gets serialized as the outbound FCP response.
   *
   * <p>Callers typically populate additional keys immediately after constructing a subclass, and
   * may read the same instance later when encoding the message for the socket. The returned object
   * is live and reflects subsequent modifications; no defensive copying occurs. As a result,
   * external callers must avoid holding on to the reference after writing to the client to prevent
   * accidental reuse or mutation races.
   *
   * @return Live SimpleFieldSet containing header/value pairs ready for wire serialization without
   *     defensive copying.
   */
  @Override
  public SimpleFieldSet getFieldSet() {
    return fs;
  }

  /**
   * Reports the protocol-level message name used when announcing this response to clients.
   *
   * <p>Each subclass must return the exact identifier expected by FCP, typically an uppercase
   * string such as {@code "DataFound"} or {@code "NodeHello"}. The value feeds directly into
   * logging, routing, and serialization, so implementations should avoid dynamic computation and
   * instead return a stable constant. Returning {@code null} is prohibited because peers rely on a
   * definite string to distinguish response varieties.
   *
   * @return Constant, human-readable message name that uniquely identifies the response type across
   *     the FCP protocol.
   */
  @Override
  public abstract String getName();

  /**
   * {@inheritDoc}
   *
   * <p>The response hierarchy exists solely on the node-to-client side of the protocol. Invoking
   * this method therefore always raises {@link MessageInvalidException} to guard against clients
   * accidentally sending a response message upstream. The exception embeds {@link
   * ProtocolErrorMessage#INVALID_MESSAGE} so callers can map the failure to a protocol error frame
   * and audit the misuse. Although this override never performs handler interactions, it keeps the
   * signature identical to {@link FCPMessage#run(FCPConnectionHandler, Node)} for uniformity.
   *
   * @param handler Handler instance that attempted to process the inbound message despite it being
   *     node-originated only.
   * @param node Node that detected the misuse; not otherwise touched because execution aborts
   *     immediately.
   * @throws MessageInvalidException Always thrown to reject client-originated attempts to send
   *     response-only envelope types.
   */
  @Override
  public void run(FCPConnectionHandler handler, Node node) throws MessageInvalidException {
    throw new MessageInvalidException(
        ProtocolErrorMessage.INVALID_MESSAGE,
        getName() + " is a reply from the node; the client should not send it.",
        null,
        false);
  }
}
