package network.crypta.clients.http;

import java.io.IOException;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Objects;
import network.crypta.client.HighLevelSimpleClient;
import network.crypta.l10n.BaseL10n;
import network.crypta.l10n.NodeL10n;
import network.crypta.l10n.TranslationPaths;
import network.crypta.support.HTMLNode;
import network.crypta.support.MultiValueTable;
import network.crypta.support.SimpleFieldSet.KeyIterator;
import network.crypta.support.SimpleFieldSet;
import network.crypta.support.api.HTTPRequest;
import network.crypta.support.io.BucketTools;

/**
 * Serves the translation management toadlet that lets operators view and edit localized strings at
 * runtime. The toadlet exposes an HTML UI for listing untranslated keys, editing entries, and
 * downloading override files without restarting the node. It is intended for administrative users
 * interacting through the built-in web interface rather than external API consumers.
 *
 * <p>Pages generated by this toadlet honor the {@code toTranslateOnly} filter to focus on missing
 * translations and redirect back to the filtered list after edits. The handler is not thread-safe
 * beyond the guarantees provided by the surrounding HTTP framework; each request builds a view over
 * shared localization state held by {@link BaseL10n}. State changes only when callers submit POST
 * requests that add or remove overrides.
 *
 * <p>Typical call flow:
 *
 * <ul>
 *   <li>A GET request renders either the list of translation keys or a specific edit form.
 *   <li>A POST request saves an override, removes one, or advances to the next untranslated key.
 *   <li>After changes, the user can download the override file for persistence.
 * </ul>
 *
 * The toadlet relies on {@link HighLevelSimpleClient} for application glue, but it keeps
 * request-level parsing and HTML generation self-contained to minimize coupling. Callers should
 * treat it as a long-lived endpoint registered once during node initialization and reused for
 * multiple sessions.
 *
 * @author Florent Daigni&egrave;re &lt;nextgens@freenetproject.org&gt;
 * @author Artefact2
 */
public class TranslationToadlet extends Toadlet {
  /**
   * Canonical path segment for the translation toadlet, used when registering routes and when
   * emitting navigation, links back to the translation UI. The trailing slash is intentional to
   * align with other in-UI links that append query parameters directly without adding a separator.
   */
  public static final String TOADLET_URL = TranslationPaths.TOADLET_URL;

  private static final String PARAM_TO_TRANSLATE_ONLY = "toTranslateOnly";
  private static final String PARAM_GET_OVERRIDE_FILE = "getOverrideTranslationFile";
  private static final String PARAM_TRANSLATION_UPDATED = "translation_updated";
  private static final String PARAM_TRANSLATE = "translate";
  private static final String PARAM_REMOVE = "remove";
  private static final String PARAM_REMOVE_CONFIRM = "remove_confirm";
  private static final String PARAM_REMOVE_CONFIRMED = "remove_confirmed";
  private static final String PARAM_GOTO_NEXT = "gotoNext";
  private static final String PARAM_TRANSLATING_FOR = "translating_for";
  private static final String PARAM_TRANSLATION_UPDATE = "translation_update";
  private static final String ATTR_CLASS = "class";
  private static final String ATTR_VALUE = "value";
  private static final String TAG_TABLE = "table";
  private static final String TAG_INPUT = "input";
  private static final String CLASS_TRANSLATION = "translation";
  private static final String CLASS_TRANSLATION_KEY = "translation-key";
  private static final String CLASS_TRANSLATION_ORIG = "translation-orig";
  private static final String CLASS_TRANSLATION_NEW = "translation-new";
  private static final String TAG_SMALL = "small";
  private static final String INPUT_TYPE_HIDDEN = "hidden";
  private static final String INPUT_TYPE_SUBMIT = "submit";
  private static final String INPUT_TYPE_CHECKBOX = "checkbox";
  private static final String L10N_TRANSLATION_KEY_LABEL = "translationKeyLabel";
  private static final String L10N_ORIGINAL_VERSION_LABEL = "originalVersionLabel";
  private static final String L10N_CURRENT_TRANSLATION_LABEL = "currentTranslationLabel";
  private static final String PATTERN_LANG = "lang";
  private static final String L10N_CONTRIBUTING_WITH_LANG = "contributingToLabelWithLang";
  private BaseL10n base;
  private String translatingFor;

  TranslationToadlet(HighLevelSimpleClient client) {
    super(client);
    this.base = NodeL10n.getBase();
    this.translatingFor = "Node";
  }

  /**
   * Handles incoming GET requests routed to the translation toadlet. Depending on the query string,
   * the method renders the translation list, shows an edit form for a specific key, serves the
   * override file download, or redirects back to the list. Requests are treated as idempotent
   * reads; state is only mutated when the caller follows up with a POST.
   *
   * @param uri full request URI including any query parameters that select actions or keys; never
   *     {@code null}.
   * @param request parsed HTTP request providing parameter accessors; parameters such as {@code
   *     translate}, {@code getOverrideTranslationFile}, and {@code toTranslateOnly} drive the
   *     response.
   * @param ctx toadlet context used to write HTML or redirects; must be open for the reply
   *     lifecycle of this method.
   * @throws ToadletContextClosedException if the connection is closed while the response is being
   *     generated or headers are sent.
   * @throws IOException if writing the response body or computing derived resources fails for any
   *     reason in the underlying stream layer.
   */
  @Override
  public void handleMethodGET(URI uri, HTTPRequest request, ToadletContext ctx)
      throws ToadletContextClosedException, IOException {
    if (!ctx.checkFullAccess(this)) return;

    boolean showEverything = !request.isParameterSet(PARAM_TO_TRANSLATE_ONLY);

    if (request.isParameterSet(PARAM_GET_OVERRIDE_FILE)) {
      sendOverrideTranslationFile(ctx);
      return;
    }
    if (request.isParameterSet(PARAM_TRANSLATION_UPDATED)) {
      showTranslationUpdatedPage(ctx, request.getParam(PARAM_TRANSLATION_UPDATED), showEverything);
      return;
    }
    if (request.isParameterSet(PARAM_TRANSLATE)) {
      showTranslationEditPage(
          ctx,
          request.getParam(PARAM_TRANSLATE),
          request.isParameterSet(PARAM_GOTO_NEXT),
          showEverything);
      return;
    }
    if (request.isParameterSet(PARAM_REMOVE)) {
      showRemoveOverridePage(ctx, request.getParam(PARAM_REMOVE), showEverything);
      return;
    }

    renderTranslationList(ctx, showEverything);
  }

  /**
   * Processes form submissions for translation edits. POST requests either store a new override,
   * delete one, or advance to the next untranslated key depending on the parameters. The method
   * updates the in-memory localization state and then redirects so that page refreshes do not
   * repeat the mutation. Inputs are validated only to the extent necessary to locate keys;
   * malformed bodies are rejected with status codes produced by the surrounding framework.
   *
   * @param uri original request URI whose path identifies the toadlet; query parameters are ignored
   *     for POST semantics beyond filter preservation.
   * @param request request wrapper that supplies form fields such as {@code trans}, {@code key},
   *     {@code remove}, and navigation hints; must not be {@code null}.
   * @param ctx response context used for issuing redirects back to the translation list or edit
   *     page; must remain open until the redirect is written.
   * @throws ToadletContextClosedException if the client disconnects before, the redirect response
   *     is fully sent.
   * @throws IOException if writing the redirect or reading form data fails due to I/O errors in the
   *     servlet container or transport stack.
   */
  public void handleMethodPOST(URI uri, HTTPRequest request, ToadletContext ctx)
      throws ToadletContextClosedException, IOException {
    Objects.requireNonNull(uri, "uri");
    if (!ctx.checkFullAccess(this)) return;

    if (request.isPartSet(PARAM_TRANSLATING_FOR)) {
      updateTranslationTarget(request);
      redirectTo(ctx, TOADLET_URL);
      return;
    }

    boolean toTranslateOnly = request.isPartSet(PARAM_TO_TRANSLATE_ONLY);

    if (!request.getPartAsStringFailsafe(PARAM_TRANSLATION_UPDATE, 32).isEmpty()) {
      handleTranslationUpdate(request, ctx, toTranslateOnly);
    } else if (!request.getPartAsStringFailsafe(PARAM_REMOVE_CONFIRMED, 32).isEmpty()) {
      handleRemoveConfirmed(request, ctx, toTranslateOnly);
    } else {
      redirectTo(ctx, "/");
    }
  }

  private void redirectTo(ToadletContext ctx, String target)
      throws ToadletContextClosedException, IOException {
    MultiValueTable<String, String> headers = MultiValueTable.from("Location", target);
    ctx.sendReplyHeaders(302, "Found", headers, null, 0);
  }

  private void sendOverrideTranslationFile(ToadletContext ctx)
      throws ToadletContextClosedException, IOException {
    SimpleFieldSet sfs = this.base.getOverrideForCurrentLanguageTranslation();
    if (sfs == null) {
      super.sendErrorPage(
          ctx,
          503 /* Service Unavailable */,
          "Service Unavailable",
          translation("noCustomTranslations"));
      return;
    }
    byte[] data = sfs.toOrderedString().getBytes(StandardCharsets.UTF_8);
    MultiValueTable<String, String> head =
        MultiValueTable.from(
            "Content-Disposition",
            "attachment; filename=\""
                + this.base.getL10nOverrideFileName(this.base.getSelectedLanguage())
                + '"');
    ctx.sendReplyHeaders(200, "Found", head, "text/plain; charset=utf-8", data.length);
    ctx.writeData(data);
  }

  private void showTranslationUpdatedPage(ToadletContext ctx, String key, boolean showEverything)
      throws ToadletContextClosedException, IOException {
    PageNode page = ctx.getPageMaker().getPageNode(translation("translationUpdatedTitle"), ctx);
    HTMLNode contentNode = page.getContentNode();

    HTMLNode translationNode = contentNode.addChild("div", ATTR_CLASS, CLASS_TRANSLATION);
    HTMLNode legendTable = translationNode.addChild(TAG_TABLE, ATTR_CLASS, CLASS_TRANSLATION);

    HTMLNode legendRow = legendTable.addChild("tr").addChild("b");
    addLegendCells(legendRow);

    HTMLNode contentRow = legendTable.addChild("tr");
    contentRow.addChild("td", ATTR_CLASS, CLASS_TRANSLATION_KEY, key);
    contentRow.addChild("td", ATTR_CLASS, CLASS_TRANSLATION_ORIG, this.base.getDefaultString(key));
    contentRow.addChild("td", ATTR_CLASS, CLASS_TRANSLATION_NEW, this.base.getString(key));

    HTMLNode footer = translationNode.addChild("div", ATTR_CLASS, "warning");
    footer
        .addChild("a", "href", TOADLET_URL + '?' + PARAM_GET_OVERRIDE_FILE)
        .addChild("#", translation("downloadTranslationsFile"));
    footer.addChild("%", "&nbsp;&nbsp;");
    footer
        .addChild(
            "a",
            "href",
            TOADLET_URL + "?" + PARAM_TRANSLATE + "=" + key + filterSuffix(showEverything))
        .addChild("#", translation("reEdit"));
    footer.addChild("%", "&nbsp;&nbsp;");
    footer
        .addChild(
            "a", "href", showEverything ? TOADLET_URL : TOADLET_URL + "?" + PARAM_TO_TRANSLATE_ONLY)
        .addChild("#", translation("returnToTranslations"));

    this.writeHTMLReply(ctx, 200, "OK", page.generate());
  }

  private void showTranslationEditPage(
      ToadletContext ctx, String key, boolean gotoNext, boolean showEverything)
      throws ToadletContextClosedException, IOException {
    PageNode page = ctx.getPageMaker().getPageNode(translation("translationUpdateTitle"), ctx);
    HTMLNode contentNode = page.getContentNode();

    HTMLNode translationNode = contentNode.addChild("div", ATTR_CLASS, CLASS_TRANSLATION);
    HTMLNode updateForm = ctx.addFormChild(translationNode, TOADLET_URL, "trans_update");
    HTMLNode legendTable = updateForm.addChild(TAG_TABLE, ATTR_CLASS, CLASS_TRANSLATION);

    HTMLNode legendRow = legendTable.addChild("tr");
    addLegendCells(legendRow);

    HTMLNode contentRow = legendTable.addChild("tr");
    contentRow.addChild("td", ATTR_CLASS, CLASS_TRANSLATION_KEY, key);
    contentRow.addChild("td", ATTR_CLASS, CLASS_TRANSLATION_ORIG, this.base.getDefaultString(key));

    contentRow
        .addChild("td", ATTR_CLASS, CLASS_TRANSLATION_NEW)
        .addChild(
            "textarea",
            new String[] {"name", "rows", "cols"},
            new String[] {"trans", "20", "80"},
            this.base.getString(key));

    contentRow.addChild(
        TAG_INPUT,
        new String[] {"type", "name", ATTR_VALUE},
        new String[] {INPUT_TYPE_HIDDEN, "key", key});

    updateForm.addChild(
        TAG_INPUT,
        new String[] {"type", "name", ATTR_VALUE},
        new String[] {
          INPUT_TYPE_SUBMIT, PARAM_TRANSLATION_UPDATE, translation("updateTranslationCommand")
        });
    updateForm.addChild(
        TAG_INPUT,
        new String[] {"type", "name", (gotoNext ? "checked" : "unchecked")},
        new String[] {INPUT_TYPE_CHECKBOX, PARAM_GOTO_NEXT, ""},
        translation(PARAM_GOTO_NEXT));
    if (!showEverything) {
      updateForm.addChild(
          TAG_INPUT,
          new String[] {"type", "name", ATTR_VALUE},
          new String[] {INPUT_TYPE_HIDDEN, PARAM_TO_TRANSLATE_ONLY, key});
    }

    updateForm.addChild(
        TAG_INPUT,
        new String[] {"type", "name", ATTR_VALUE},
        new String[] {INPUT_TYPE_SUBMIT, "cancel", NodeL10n.getBase().getString("Toadlet.cancel")});
    this.writeHTMLReply(ctx, 200, "OK", page.generate());
  }

  private void showRemoveOverridePage(ToadletContext ctx, String key, boolean showEverything)
      throws ToadletContextClosedException, IOException {
    PageNode page = ctx.getPageMaker().getPageNode(translation("removeOverrideTitle"), ctx);
    HTMLNode contentNode = page.getContentNode();

    HTMLNode content =
        ctx.getPageMaker()
            .getInfobox(
                "infobox-warning",
                translation("removeOverrideWarningTitle"),
                contentNode,
                "translation-override",
                true);
    content
        .addChild("p")
        .addChild(
            "#",
            NodeL10n.getBase()
                .getString(
                    "TranslationToadlet.confirmRemoveOverride",
                    new String[] {"key", ATTR_VALUE},
                    new String[] {key, this.base.getString(key)}));
    HTMLNode removeForm =
        ctx.addFormChild(content.addChild("p"), TOADLET_URL, PARAM_REMOVE_CONFIRMED);
    if (!showEverything) {
      removeForm.addChild(
          TAG_INPUT,
          new String[] {"type", "name", ATTR_VALUE},
          new String[] {INPUT_TYPE_HIDDEN, PARAM_TO_TRANSLATE_ONLY, key});
    }
    removeForm.addChild(
        TAG_INPUT,
        new String[] {"type", "name", ATTR_VALUE},
        new String[] {INPUT_TYPE_HIDDEN, PARAM_REMOVE_CONFIRM, key});
    removeForm.addChild(
        TAG_INPUT,
        new String[] {"type", "name", ATTR_VALUE},
        new String[] {INPUT_TYPE_SUBMIT, PARAM_REMOVE_CONFIRMED, translation(PARAM_REMOVE)});
    removeForm.addChild(
        TAG_INPUT,
        new String[] {"type", "name", ATTR_VALUE},
        new String[] {INPUT_TYPE_SUBMIT, "cancel", NodeL10n.getBase().getString("Toadlet.cancel")});

    this.writeHTMLReply(ctx, 200, "OK", page.generate());
  }

  private void renderTranslationList(ToadletContext ctx, boolean showEverything)
      throws ToadletContextClosedException, IOException {
    PageNode page = ctx.getPageMaker().getPageNode(translation("translationUpdateTitle"), ctx);
    HTMLNode contentNode = page.getContentNode();

    HTMLNode translatingForBox =
        ctx.getPageMaker().getInfobox(null, translation("selectTranslation"), contentNode);
    ArrayList<String> elementsToTranslate = new ArrayList<>();
    elementsToTranslate.add("Node");

    HTMLNode translatingForForm =
        ctx.addFormChild(translatingForBox, TOADLET_URL, "ChooseWhatToTranslate")
            .addChild("p", translation("showTranslationOf"));
    HTMLNode translatingForOption =
        translatingForForm.addChild("select", "name", PARAM_TRANSLATING_FOR);
    for (String element : elementsToTranslate) {
      HTMLNode option = translatingForOption.addChild("option", "name", element, element);
      if (element.equals(this.translatingFor)) {
        option.addAttribute("selected", "selected");
      }
    }
    translatingForForm.addChild(TAG_INPUT, "type", INPUT_TYPE_SUBMIT);

    HTMLNode translationNode = contentNode.addChild("div", ATTR_CLASS, CLASS_TRANSLATION);
    HTMLNode translationHeaderNode = translationNode.addChild("p");
    translationHeaderNode.addChild(
        "#", translationContributingWithLang(this.base.getSelectedLanguage().fullName));
    translationHeaderNode
        .addChild("a", "href", TOADLET_URL + '?' + PARAM_GET_OVERRIDE_FILE)
        .addChild("#", translation("downloadTranslationsFile"));
    translationHeaderNode.addChild("#", " ");
    if (showEverything) {
      translationHeaderNode
          .addChild("a", "href", TOADLET_URL + '?' + PARAM_TO_TRANSLATE_ONLY)
          .addChild("#", translation("hideAlreadyTranslated"));
    } else {
      translationHeaderNode
          .addChild("a", "href", TOADLET_URL)
          .addChild("#", translation("showEverything"));
    }
    HTMLNode legendTable = translationNode.addChild(TAG_TABLE, ATTR_CLASS, CLASS_TRANSLATION);

    HTMLNode legendRow = legendTable.addChild("tr");
    addLegendCells(legendRow);

    KeyIterator it = this.base.getDefaultLanguageTranslation().keyIterator("");

    while (it.hasNext()) {
      String key = it.nextKey();
      boolean isOverriden = this.base.isOverridden(key);
      if (!showEverything && (isOverriden || (this.base.getString(key, true) != null))) continue;
      HTMLNode contentRow = legendTable.addChild("tr");
      contentRow.addChild("td", ATTR_CLASS, CLASS_TRANSLATION_KEY, key);
      contentRow.addChild(
          "td", ATTR_CLASS, CLASS_TRANSLATION_ORIG, this.base.getDefaultString(key));

      contentRow
          .addChild("td", ATTR_CLASS, CLASS_TRANSLATION_NEW)
          .addChild(setOrRemoveOverride(key, isOverriden, showEverything));
    }

    this.writeHTMLReply(ctx, 200, "OK", page.generate());
  }

  private void updateTranslationTarget(HTTPRequest request) {
    final String translateFor = request.getPartAsStringFailsafe(PARAM_TRANSLATING_FOR, 255);

    if ("Node".equals(translateFor)) {
      this.translatingFor = "Node";
      this.base = NodeL10n.getBase();
    }
  }

  private void handleTranslationUpdate(
      HTTPRequest request, ToadletContext ctx, boolean toTranslateOnly)
      throws ToadletContextClosedException, IOException {
    String key = request.getPartAsStringFailsafe("key", 256);
    this.base.setOverride(
        key,
        new String(BucketTools.toByteArray(request.getPart("trans")), StandardCharsets.UTF_8)
            .trim());

    if ("on".equalsIgnoreCase(request.getPartAsStringFailsafe(PARAM_GOTO_NEXT, 7))) {
      String nextKey = findNextKeyToTranslate();
      if (nextKey != null) {
        redirectTo(
            ctx,
            TOADLET_URL
                + '?'
                + PARAM_GOTO_NEXT
                + '&'
                + PARAM_TRANSLATE
                + '='
                + nextKey
                + toTranslateOnlySuffix(toTranslateOnly));
        return;
      }
    }

    redirectTo(
        ctx,
        TOADLET_URL
            + '?'
            + PARAM_TRANSLATION_UPDATED
            + '='
            + key
            + toTranslateOnlySuffix(toTranslateOnly));
  }

  private String findNextKeyToTranslate() {
    KeyIterator it = base.getDefaultLanguageTranslation().keyIterator("");

    while (it.hasNext()) {
      String newKey = it.nextKey();
      boolean isOverriden = this.base.isOverridden(newKey);
      if (isOverriden || (this.base.getString(newKey, true) != null)) {
        continue;
      }
      return newKey;
    }
    return null;
  }

  private void handleRemoveConfirmed(
      HTTPRequest request, ToadletContext ctx, boolean toTranslateOnly)
      throws ToadletContextClosedException, IOException {
    String key = request.getPartAsStringFailsafe(PARAM_REMOVE_CONFIRM, 256).trim();
    this.base.setOverride(key, "");

    redirectTo(
        ctx,
        TOADLET_URL
            + '?'
            + PARAM_TRANSLATION_UPDATED
            + '='
            + key
            + toTranslateOnlySuffix(toTranslateOnly));
  }

  private void addLegendCells(HTMLNode row) {
    row.addChild("td", ATTR_CLASS, CLASS_TRANSLATION_KEY, translation(L10N_TRANSLATION_KEY_LABEL));
    row.addChild("td", ATTR_CLASS, CLASS_TRANSLATION_KEY, translation(L10N_ORIGINAL_VERSION_LABEL));
    row.addChild(
        "td", ATTR_CLASS, CLASS_TRANSLATION_KEY, translation(L10N_CURRENT_TRANSLATION_LABEL));
  }

  private String filterSuffix(boolean showEverything) {
    return showEverything ? "" : "&" + PARAM_TO_TRANSLATE_ONLY;
  }

  private String toTranslateOnlySuffix(boolean toTranslateOnly) {
    return toTranslateOnly ? "&" + PARAM_TO_TRANSLATE_ONLY : "";
  }

  private HTMLNode setOrRemoveOverride(String key, boolean isOverriden, boolean showEverything) {
    String value = this.base.getString(key, true);
    String filterSuffix = filterSuffix(showEverything);

    HTMLNode translationField =
        new HTMLNode("span", ATTR_CLASS, isOverriden ? "translate_d" : "translate_it");
    if (value == null) {
      translationField.addChild("#", this.base.getDefaultString(key));
      translationField
          .addChild(
              "a", "href", TranslationToadlet.TOADLET_URL + "?translate=" + key + filterSuffix)
          .addChild(TAG_SMALL, translation("bracketTranslateIt"));
    } else {
      translationField.addChild("#", this.base.getString(key));
      translationField
          .addChild(
              "a", "href", TranslationToadlet.TOADLET_URL + "?translate=" + key + filterSuffix)
          .addChild(TAG_SMALL, translation("bracketUpdateTranslation"));
      if (isOverriden)
        translationField
            .addChild("a", "href", TranslationToadlet.TOADLET_URL + "?remove=" + key + filterSuffix)
            .addChild(TAG_SMALL, translation("bracketRemoveOverride"));
    }

    return translationField;
  }

  private String translation(String key) {
    return NodeL10n.getBase().getString("TranslationToadlet." + key);
  }

  private String translationContributingWithLang(String value) {
    return NodeL10n.getBase()
        .getString(
            "TranslationToadlet." + L10N_CONTRIBUTING_WITH_LANG,
            new String[] {PATTERN_LANG},
            new String[] {value});
  }

  @Override
  public String path() {
    return TOADLET_URL;
  }
}
