package org.spaceroots.mantissa.algebra;

/**
 * Base class for families of orthogonal polynomials built from three-term recurrence coefficients.
 *
 * <p>Orthogonal polynomials generated by this hierarchy follow a standard recurrence of the form:
 *
 * <pre>{@code
 *     O_0(X)   = constant polynomial of degree 0
 *     O_1(X)   = base polynomial of degree 1
 * a_{1,k} O_{k+1}(X) = (a_{2,k} + a_{3,k} X) O_k(X) - a_{4,k} O_{k-1}(X)
 * }</pre>
 *
 * <p>The concrete subclasses (for example {@link Legendre}, {@link Laguerre}, {@link Hermite}, and
 * {@link Chebyshev}) supply the coefficient sequences and seed polynomials through a {@link
 * CoefficientsGenerator}. Instances represent a single polynomial of a given degree, storing its
 * coefficients in the rational-number representation inherited from {@link Polynomial.Rational}.
 * The class does not mutate those coefficients after construction, so instances can be shared
 * safely as long as the underlying generator is not modified concurrently. Typical usage is to
 * delegate construction to a specific family class, which internally invokes this base constructor,
 * or to derive a new family by providing a generator that encapsulates the recurrence rules for the
 * desired orthogonality measure. The design favors clarity over eager computation: generators cache
 * coefficients incrementally, while constructed polynomials merely reference the precomputed array.
 *
 * <ul>
 *   <li>Defines common storage and lifecycle for concrete orthogonal polynomial families.
 *   <li>Relies on generator-backed caching to avoid recomputing coefficient sequences.
 *   <li>Produces immutable coefficient arrays per polynomial instance after construction.
 * </ul>
 *
 * @see CoefficientsGenerator
 * @see Polynomial.Rational
 * @version $Id: OrthogonalPolynomial.java 1711 2006-12-13 21:27:51Z luc $
 * @author L. Maisonobe
 */
public abstract class OrthogonalPolynomial extends Polynomial.Rational {

  /**
   * Creates an orthogonal polynomial of the requested degree using a supplied generator.
   *
   * <p>The constructor delegates all recurrence handling to the {@link CoefficientsGenerator}
   * provided by the concrete subclass. The generator computes and caches the full coefficient array
   * for the requested degree, allowing subsequent evaluations to reuse the same immutable data
   * without additional allocations. Callers are expected to pass non-negative degrees that the
   * generator can satisfy; negative values or unsupported degrees result in generator-specific
   * failures. Construction itself is side-effect free beyond generator caching, making the
   * resulting polynomial safe to retain or reuse across threads if the generator implementation is
   * thread-safe.
   *
   * @param degree zero or positive degree of the polynomial to build from the family
   * @param generator provider that computes recurrence coefficients and caches results for this
   *     polynomial family
   */
  protected OrthogonalPolynomial(int degree, CoefficientsGenerator generator) {
    a = generator.getCoefficients(degree);
  }
}
