package org.spaceroots.mantissa.algebra;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigInteger;
import java.util.Arrays;

/**
 * Represents a single-variable polynomial abstraction that supports algebraic and analytic
 * operations.
 *
 * <p>The base class exposes a common API for querying structure (degree, identity, zero), scalar
 * arithmetic, evaluation, and derivatives while delegating coefficient storage to concrete
 * implementations. Current subclasses cover exact rational arithmetic and double-precision real
 * coefficients; both keep instances immutable by allocating new arrays on every operation rather
 * than mutating existing coefficients. The class is intentionally minimal and abstract so clients
 * can choose the numeric domain that best matches their accuracy and performance requirements.
 *
 * <p>Typical usage creates a concrete {@link Rational} or {@link Double} polynomial, combines it
 * with other instances through addition, subtraction, or multiplication, and evaluates results at
 * one or more sample points. Methods avoid surprises by returning new objects, so callers can share
 * instances safely between threads as long as they do not expose the protected coefficient arrays
 * to external mutation.
 *
 * <ul>
 *   <li>Responsibilities: define the shared protocol for scalar multiplication, division, and
 *       differentiation.
 *   <li>Notable behaviors: returns new instances for every operation; supports value evaluation and
 *       derivative creation in a numerically stable order (Horner scheme).
 *   <li>Thread-safety: immutable public API; subclasses should avoid leaking internal arrays to
 *       preserve safe sharing.
 * </ul>
 *
 * @version $Id: Polynomial.java 1716 2006-12-13 22:56:35Z luc $
 * @author L. Maisonobe
 * @see Polynomial.Rational
 * @see Polynomial.Double
 */
public abstract class Polynomial implements Serializable {

  /**
   * Creates a new polynomial base instance.
   *
   * <p>The constructor is public to mirror the implicit default constructor generated by the
   * compiler, but the class remains abstract and therefore cannot be instantiated directly.
   * Concrete subclasses call this constructor implicitly while normalizing their coefficient
   * arrays. Clients should obtain instances through {@link Rational} or {@link Double} factory
   * constructors rather than subclassing unless they need a custom numeric domain.
   */
  protected Polynomial() {}

  /**
   * Check if the instance is the null polynomial.
   *
   * <p>Implementations treat a polynomial as null when all coefficients are zero after any internal
   * normalization. The check is inexpensive and does not allocate, making it suitable for guarding
   * early exits before heavier algebra operations.
   *
   * @return true if every stored coefficient evaluates to zero in the current numeric domain
   */
  public abstract boolean isZero();

  /**
   * Check if the instance is the constant unit polynomial.
   *
   * <p>Unit polynomials have degree zero and value one for all inputs. This helper is frequently
   * used when simplifying products or divisions where multiplying by one should return the same
   * instance to avoid unnecessary allocations.
   *
   * @return true if the polynomial is constant and equal to one everywhere
   */
  public abstract boolean isOne();

  /**
   * Check if the instance is the identity polynomial.
   *
   * <p>The identity polynomial evaluates to the input variable (x) and has coefficients [0, 1]. It
   * is a common neutral element when composing polynomials or building linear terms, so callers can
   * short-circuit certain transforms when this predicate returns true.
   *
   * @return true if the polynomial equals x with no constant offset
   */
  public abstract boolean isIdentity();

  /**
   * Get the polynomial degree.
   *
   * <p>The degree is defined as the highest exponent with a non-zero coefficient after leading
   * zeros are trimmed. Implementations guarantee the degree is non-negative and will return 0 for
   * the null and unit polynomials. The method performs constant-time lookup based on internal
   * normalization.
   *
   * @return degree of the polynomial, with 0 for constant values
   */
  public abstract int getDegree();

  /**
   * Negate the instance.
   *
   * <p>Creates a new polynomial whose coefficients are the additive inverses of the current ones.
   * Implementations return a distinct object and leave the original unchanged, enabling safe reuse
   * across threads. Calling negate twice yields a polynomial equal to the original.
   *
   * @return a new polynomial representing -this
   */
  public abstract Polynomial negate();

  /**
   * Multiply the instance by a constant.
   *
   * <p>The operation scales every coefficient by the supplied rational value and returns a new
   * polynomial of identical degree unless the multiplier is zero, in which case the result is the
   * null polynomial. Implementations should avoid copying when the multiplier is one to preserve
   * performance.
   *
   * @param r constant to multiply by; may not be zero for callers relying on original degree
   * @return a new polynomial containing scaled coefficients
   */
  public abstract Polynomial multiply(RationalNumber r);

  /**
   * Multiply the instance by a constant.
   *
   * <p>This overload accepts primitive longs for convenience. Implementations typically delegate to
   * the {@link #multiply(RationalNumber)} variant after wrapping the value to preserve exactness.
   *
   * @param l integer constant to multiply by
   * @return a new Polynomial with coefficients scaled by {@code l}
   */
  public abstract Polynomial multiply(long l);

  /**
   * Multiply the instance by a constant.
   *
   * <p>Wrapping {@link BigInteger} values allows callers to scale coefficients without losing
   * precision. Implementations typically defer to the {@link #multiply(RationalNumber)} path to
   * preserve rational accuracy.
   *
   * @param i arbitrary-precision integer constant to multiply by
   * @return a new Polynomial scaled by the supplied integer
   */
  public Polynomial multiply(BigInteger i) {
    return multiply(new RationalNumber(i));
  }

  /**
   * Divide the instance by a constant.
   *
   * <p>The operation multiplies coefficients by the reciprocal of {@code l}. Implementations should
   * reject zero divisors with {@link ArithmeticException}. The result preserves degree unless the
   * scalar is zero, which is disallowed here.
   *
   * @param l non-zero integer divisor applied uniformly to all coefficients
   * @return a new polynomial whose coefficients are scaled by 1/{@code l}
   * @exception ArithmeticException if the constant is zero
   */
  public Polynomial divide(long l) {
    return divide(new RationalNumber(l));
  }

  /**
   * Divide the instance by a constant.
   *
   * <p>Divides all coefficients by the provided rational value. The operation is equivalent to
   * multiplying by {@code r.invert()} but keeps intent clearer at call sites. A zero divisor raises
   * {@link ArithmeticException}.
   *
   * @param r non-zero rational divisor applied to every coefficient
   * @return a new polynomial with each coefficient divided by {@code r}
   * @exception ArithmeticException if the constant is zero
   */
  public Polynomial divide(RationalNumber r) {
    return multiply(r.invert());
  }

  /**
   * Divide the instance by a constant.
   *
   * <p>Convenience overload for arbitrary-precision integer divisors. Internally delegates to the
   * rational division path to retain exactness and consistent zero checks.
   *
   * @param i non-zero {@link BigInteger} divisor applied to all coefficients
   * @return a new polynomial scaled by the inverse of {@code i}
   * @exception ArithmeticException if the constant is zero
   */
  public Polynomial divide(BigInteger i) {
    return divide(new RationalNumber(i));
  }

  /**
   * Get the value of the polynomial for a specified unknown.
   *
   * <p>Implementations should evaluate using Horner's rule to minimize intermediate allocations and
   * improve numerical stability. The method performs no domain checks and returns the numeric
   * domain of the concrete subclass (double for floating values, doubleValue for rationals).
   *
   * @param x value of the unknown at which the polynomial is evaluated
   * @return value of the polynomial computed in the subclass numeric representation
   */
  public abstract double valueAt(double x);

  /**
   * Get the derivative of the instance with respect to the unknown. The derivative of an n degree
   * polynomial is an n-1 degree polynomial of the same type.
   *
   * <p>Derivatives are computed symbolically by multiplying each coefficient by its exponent and
   * shifting degrees down by one. Implementations return a new polynomial; constant polynomials
   * produce the null polynomial. The returned instance preserves the numeric domain of the
   * receiver.
   *
   * @return a new polynomial representing the first derivative of this instance
   */
  public abstract Polynomial getDerivative();

  /**
   * Implements single-variable polynomials backed by exact {@link RationalNumber} coefficients.
   *
   * <p>Constructors normalize leading zeros so the internal array index always matches the
   * exponent. All algebraic operations allocate fresh arrays and never mutate existing coefficient
   * storage, which keeps instances effectively immutable once built. Use this variant when exact
   * arithmetic is required or when operations such as Euclidean division must preserve fractional
   * results without rounding error.
   *
   * <p>Supported operations include addition, subtraction, scalar and polynomial multiplication,
   * evaluation, derivation, and full Euclidean division with quotient and remainder output. Because
   * intermediate values are rationals, performance is slower than the {@link Double} variant but
   * results remain precise.
   */
  public static class Rational extends Polynomial {

    /** Simple constructor. Build a null polynomial */
    public Rational() {
      a = new RationalNumber[] {RationalNumber.ZERO};
    }

    /**
     * Simple constructor. Build a constant polynomial
     *
     * @param value constant value of the polynomial
     */
    public Rational(long value) {
      this(new RationalNumber(value));
    }

    /**
     * Simple constructor. Build a constant polynomial
     *
     * @param value constant value of the polynomial
     */
    public Rational(RationalNumber value) {
      a = new RationalNumber[] {value};
    }

    /**
     * Simple constructor. Build a first degree polynomial
     *
     * @param a1 leeding degree coefficient
     * @param a0 constant term
     */
    @SuppressWarnings("unused")
    public Rational(long a1, long a0) {
      this(new RationalNumber(a1), new RationalNumber(a0));
    }

    /**
     * Simple constructor. Build a first degree polynomial
     *
     * @param a1 leeding degree coefficient
     * @param a0 constant term
     */
    public Rational(RationalNumber a1, RationalNumber a0) {
      if (!a1.isZero()) {
        a = new RationalNumber[] {a0, a1};
      } else {
        a = new RationalNumber[] {a0};
      }
    }

    /**
     * Simple constructor. Build a second degree polynomial
     *
     * @param a2 leeding degree coefficient
     * @param a1 first degree coefficient
     * @param a0 constant term
     */
    @SuppressWarnings("unused")
    public Rational(long a2, long a1, long a0) {
      this(new RationalNumber(a2), new RationalNumber(a1), new RationalNumber(a0));
    }

    /**
     * Simple constructor. Build a second degree polynomial
     *
     * @param a2 leeding degree coefficient
     * @param a1 first degree coefficient
     * @param a0 constant term
     */
    public Rational(RationalNumber a2, RationalNumber a1, RationalNumber a0) {
      if (!a2.isZero()) {
        a = new RationalNumber[] {a0, a1, a2};
      } else {
        if (!a1.isZero()) {
          a = new RationalNumber[] {a0, a1};
        } else {
          a = new RationalNumber[] {a0};
        }
      }
    }

    /**
     * Simple constructor. Build a third degree polynomial
     *
     * @param a3 leeding degree coefficient
     * @param a2 second degree coefficient
     * @param a1 first degree coefficient
     * @param a0 constant term
     */
    @SuppressWarnings("unused")
    public Rational(long a3, long a2, long a1, long a0) {
      this(
          new RationalNumber(a3),
          new RationalNumber(a2),
          new RationalNumber(a1),
          new RationalNumber(a0));
    }

    /**
     * Simple constructor. Build a third degree polynomial
     *
     * @param a3 leeding degree coefficient
     * @param a2 second degree coefficient
     * @param a1 first degree coefficient
     * @param a0 constant term
     */
    public Rational(RationalNumber a3, RationalNumber a2, RationalNumber a1, RationalNumber a0) {
      if (!a3.isZero()) {
        a = new RationalNumber[] {a0, a1, a2, a3};
      } else {
        if (!a2.isZero()) {
          a = new RationalNumber[] {a0, a1, a2};
        } else {
          if (!a1.isZero()) {
            a = new RationalNumber[] {a0, a1};
          } else {
            a = new RationalNumber[] {a0};
          }
        }
      }
    }

    /**
     * Simple constructor. Build a polynomial from its coefficients
     *
     * @param a coefficients array, the a[0] array element is the constant term while the
     *     a[a.length-1] element is the leeding degree coefficient. The array is copied in a new
     *     array, so it can be changed once the constructor as returned.
     */
    public Rational(RationalNumber[] a) {

      // remove null high degree coefficients
      int i = a.length - 1;
      while ((i > 0) && (a[i].isZero())) {
        --i;
      }

      // copy the remaining coefficients
      this.a = new RationalNumber[i + 1];
      System.arraycopy(a, 0, this.a, 0, i + 1);
    }

    /**
     * Simple constructor. Build a one-term polynomial from one coefficient and the corresponding
     * degree
     *
     * @param c coefficient
     * @param degree degree associated with the coefficient
     */
    public Rational(RationalNumber c, int degree) {

      if (c.isZero() || degree < 0) {
        a = new RationalNumber[] {RationalNumber.ZERO};
      } else {
        a = new RationalNumber[degree + 1];
        Arrays.fill(a, 0, degree, RationalNumber.ZERO);
        a[degree] = c;
      }
    }

    /**
     * Check if the instance is the null polynomial.
     *
     * @return true if the polynomial is null
     */
    public boolean isZero() {
      return (a.length == 1) && a[0].isZero();
    }

    /**
     * Check if the instance is the constant unit polynomial.
     *
     * @return true if the polynomial is the constant unit polynomial
     */
    public boolean isOne() {
      return (a.length == 1) && a[0].isOne();
    }

    /**
     * Check if the instance is the identity polynomial.
     *
     * @return true if the polynomial is the identity polynomial
     */
    public boolean isIdentity() {
      return (a.length == 2) && a[0].isZero() && a[1].isOne();
    }

    /**
     * Get the polynomial degree.
     *
     * @return degree
     */
    public int getDegree() {
      return a.length - 1;
    }

    /**
     * Get the coefficients of the polynomial.
     *
     * @return a copy of the coefficients array, the array element at index 0 is the constant term
     *     while the element at index a.length-1 is the leading degree coefficient
     */
    public RationalNumber[] getCoefficients() {
      return a.clone();
    }

    /**
     * Add a polynomial to the instance
     *
     * @param p polynomial to add
     * @return a new polynomial which is the sum of the instance and p
     */
    public Rational add(Rational p) {

      // identify the lowest degree polynomial
      int lowLength = Math.min(a.length, p.a.length);
      int highLength = Math.max(a.length, p.a.length);

      // build the coefficients array
      RationalNumber[] newA = new RationalNumber[highLength];
      for (int i = 0; i < lowLength; ++i) {
        newA[i] = a[i].add(p.a[i]);
      }
      System.arraycopy(
          (a.length < p.a.length) ? p.a : a, lowLength, newA, lowLength, highLength - lowLength);

      return new Rational(newA);
    }

    /**
     * Subtract a polynomial from the instance.
     *
     * @param p polynomial to subtract
     * @return a new polynomial which is the difference the instance minus p
     */
    public Rational subtract(Rational p) {

      // identify the lowest degree polynomial
      int lowLength = Math.min(a.length, p.a.length);
      int highLength = Math.max(a.length, p.a.length);

      // build the coefficients array
      RationalNumber[] newA = new RationalNumber[highLength];
      for (int i = 0; i < lowLength; ++i) {
        newA[i] = a[i].subtract(p.a[i]);
      }
      if (a.length < p.a.length) {
        for (int i = lowLength; i < highLength; ++i) {
          newA[i] = p.a[i].negate();
        }
      } else {
        System.arraycopy(a, lowLength, newA, lowLength, highLength - lowLength);
      }

      return new Rational(newA);
    }

    /**
     * Negate the instance.
     *
     * @return a new polynomial
     */
    public Polynomial negate() {
      RationalNumber[] newA = new RationalNumber[a.length];
      for (int i = 0; i < a.length; ++i) {
        newA[i] = a[i].negate();
      }
      return new Rational(newA);
    }

    /**
     * Multiply the instance by a polynomial.
     *
     * @param p polynomial to multiply by
     * @return a new polynomial
     */
    public Rational multiply(Rational p) {

      RationalNumber[] newA = new RationalNumber[a.length + p.a.length - 1];

      for (int i = 0; i < newA.length; ++i) {
        newA[i] = RationalNumber.ZERO;
        for (int j = Math.max(0, i + 1 - p.a.length); j < Math.min(a.length, i + 1); ++j) {
          newA[i] = newA[i].add(a[j].multiply(p.a[i - j]));
        }
      }

      return new Rational(newA);
    }

    /**
     * Multiply the instance by a constant.
     *
     * @param l constant to multiply by
     * @return a new polynomial
     */
    public Polynomial multiply(long l) {
      return multiply(new RationalNumber(l));
    }

    /**
     * Multiply the instance by a constant.
     *
     * @param r constant to multiply by
     * @return a new polynomial
     */
    public Polynomial multiply(RationalNumber r) {

      if (r.isZero()) {
        return new Rational(new RationalNumber[] {RationalNumber.ZERO});
      }

      if (r.isOne()) {
        return this;
      }

      RationalNumber[] newA = new RationalNumber[a.length];
      for (int i = 0; i < a.length; ++i) {
        newA[i] = a[i].multiply(r);
      }
      return new Rational(newA);
    }

    /**
     * Get the value of the polynomial for a specified unknown.
     *
     * @param x value of the unknown
     * @return value of the polynomial
     */
    public double valueAt(double x) {
      double y = 0;
      for (int i = a.length - 1; i >= 0; --i) {
        y = y * x + a[i].doubleValue();
      }
      return y;
    }

    /**
     * Get the derivative of the instance with respect to the unknown. The derivative of an n degree
     * polynomial is an n-1 degree polynomial of the same type.
     *
     * @return a new polynomial which is the derivative of the instance
     */
    public Polynomial getDerivative() {
      if (a.length == 1) {
        return new Rational();
      }
      RationalNumber[] newA = new RationalNumber[a.length - 1];
      for (int i = 1; i < a.length; ++i) {
        newA[i - 1] = a[i].multiply(i);
      }
      return new Rational(newA);
    }

    /**
     * Perform the euclidian division of two polynomials.
     *
     * @param dividend numerator polynomial
     * @param divisor denominator polynomial
     * @return an object containing the quotient and the remainder of the division
     */
    public static DivisionResult euclidianDivision(Rational dividend, Rational divisor) {

      Rational quotient = new Rational(0L);
      Rational remainder = dividend;

      int divisorDegree = divisor.getDegree();
      int remainderDegree = remainder.getDegree();
      while ((!remainder.isZero()) && (remainderDegree >= divisorDegree)) {

        RationalNumber c = remainder.a[remainderDegree].divide(divisor.a[divisorDegree]);
        Rational monomial = new Rational(c, remainderDegree - divisorDegree);

        remainder = remainder.subtract(monomial.multiply(divisor));
        quotient = quotient.add(monomial);

        remainderDegree = remainder.getDegree();
      }

      return new DivisionResult(quotient, remainder);
    }

    /**
     * Get the Least Common Multiple of the coefficients denominators. This number is the smallest
     * integer by which we should multiply the instance to get a polynomial whose coefficients are
     * all integers.
     *
     * @return the Least Common Multiple of the coefficients denominators
     */
    public BigInteger getDenominatorsLCM() {

      BigInteger lcm = BigInteger.ONE;

      for (RationalNumber rationalNumber : a) {
        RationalNumber newCoeff = rationalNumber.multiply(lcm);
        if (!newCoeff.isInteger()) {
          lcm = lcm.multiply(newCoeff.getDenominator());
        }
      }

      return lcm;
    }

    /**
     * Returns a string representation of the polynomial.
     *
     * <p>The representation is user oriented. Terms are displayed lowest degrees first. The
     * multiplications signs, coefficients equals to one and null terms are not displayed (except if
     * the polynomial is 0, in which case the 0 constant term is displayed). Addition of terms with
     * negative coefficients are replaced by subtraction of terms with positive coefficients except
     * for the first displayed term (i.e. we display <code>-3</code> for a constant negative
     * polynomial, but <code>1 - 3 x + x^2</code> if the negative coefficient is not the first one
     * displayed).
     *
     * <p>The method constructs the string lazily with {@link StringBuilder} and omits zero terms to
     * avoid noise. Resulting text is stable and safe for logs or diagnostics but not intended for
     * round-trip parsing.
     *
     * @return a string representation of the polynomial suitable for diagnostics
     */
    public String toString() {

      StringBuilder s = new StringBuilder();
      for (int i = 0; i < a.length; ++i) {
        RationalNumber coefficient = a[i];
        if (!coefficient.isZero()) {
          appendTerm(s, coefficient, i);
        }
      }

      return s.isEmpty() ? "0" : s.toString();
    }

    private void appendTerm(StringBuilder s, RationalNumber coefficient, int degree) {
      boolean firstTerm = s.isEmpty();
      boolean negative = coefficient.isNegative();

      if (!firstTerm) {
        s.append(negative ? " - " : " + ");
      } else if (negative) {
        s.append('-');
      }

      RationalNumber absAi = RationalNumber.abs(coefficient);
      boolean needsCoefficient = (degree == 0) || !absAi.isOne();
      if (needsCoefficient) {
        s.append(absAi);
      }

      if (degree > 0) {
        if (needsCoefficient) {
          s.append(' ');
        }
        s.append('x');
        if (degree > 1) {
          s.append('^');
          s.append(degree);
        }
      }
    }

    /** Coefficients array. */
    protected RationalNumber[] a;

    @Serial private static final long serialVersionUID = -794133890636181115L;
  }

  /**
   * Stores the quotient and remainder produced by Euclidean division of two {@link Rational}
   * polynomials.
   *
   * <p>The record is intentionally minimal and serializable so it can be returned from algorithms
   * and shipped across process boundaries without additional wrappers. Both components are
   * immutable polynomial instances computed by {@link Rational#euclidianDivision(Rational,
   * Rational)}.
   *
   * @param quotient the polynomial factor representing the integer quotient of the division
   * @param remainder the polynomial remainder whose degree is strictly less than the divisor
   * @see Polynomial.Rational#euclidianDivision
   */
  public record DivisionResult(Rational quotient, Rational remainder) implements Serializable {

    @Serial private static final long serialVersionUID = 2498681794544365690L;
  }

  /**
   * Implements single-variable polynomials backed by double-precision floating point coefficients.
   *
   * <p>This variant favors performance over exactness and is suitable for numeric workflows such as
   * curve fitting or evaluation at many sample points. Constructors normalize leading zeros so the
   * internal array length always reflects the current degree, and all algebraic operations allocate
   * new arrays to keep instances effectively immutable.
   *
   * <p>Because doubles are subject to rounding, repeated operations may accumulate error. Prefer
   * the {@link Rational} variant when correctness across many divisions is critical.
   */
  public static class Double extends Polynomial {

    /** Simple constructor. Build a null polynomial */
    public Double() {
      a = new double[] {0.0};
    }

    /**
     * Simple constructor. Build a constant polynomial
     *
     * @param value constant value of the polynomial
     */
    public Double(long value) {
      this((double) value);
    }

    /**
     * Simple constructor. Build a constant polynomial
     *
     * @param value constant value of the polynomial
     */
    public Double(double value) {
      a = new double[] {value};
    }

    /**
     * Simple constructor. Build a first degree polynomial
     *
     * @param a1 leeding degree coefficient
     * @param a0 constant term
     */
    public Double(long a1, long a0) {
      this((double) a1, (double) a0);
    }

    /**
     * Simple constructor. Build a first degree polynomial
     *
     * @param a1 leeding degree coefficient
     * @param a0 constant term
     */
    public Double(double a1, double a0) {
      if (a1 != 0) {
        a = new double[] {a0, a1};
      } else {
        a = new double[] {a0};
      }
    }

    /**
     * Simple constructor. Build a second degree polynomial
     *
     * @param a2 leeding degree coefficient
     * @param a1 first degree coefficient
     * @param a0 constant term
     */
    public Double(long a2, long a1, long a0) {
      this((double) a2, (double) a1, (double) a0);
    }

    /**
     * Simple constructor. Build a second degree polynomial
     *
     * @param a2 leeding degree coefficient
     * @param a1 first degree coefficient
     * @param a0 constant term
     */
    public Double(double a2, double a1, double a0) {
      if (a2 != 0) {
        a = new double[] {a0, a1, a2};
      } else {
        if (a1 != 0) {
          a = new double[] {a0, a1};
        } else {
          a = new double[] {a0};
        }
      }
    }

    /**
     * Simple constructor. Build a third degree polynomial
     *
     * @param a3 leeding degree coefficient
     * @param a2 second degree coefficient
     * @param a1 first degree coefficient
     * @param a0 constant term
     */
    public Double(long a3, long a2, long a1, long a0) {
      this((double) a3, (double) a2, (double) a1, (double) a0);
    }

    /**
     * Simple constructor. Build a third degree polynomial
     *
     * @param a3 leeding degree coefficient
     * @param a2 second degree coefficient
     * @param a1 first degree coefficient
     * @param a0 constant term
     */
    public Double(double a3, double a2, double a1, double a0) {
      if (a3 != 0) {
        a = new double[] {a0, a1, a2, a3};
      } else {
        if (a2 != 0) {
          a = new double[] {a0, a1, a2};
        } else {
          if (a1 != 0) {
            a = new double[] {a0, a1};
          } else {
            a = new double[] {a0};
          }
        }
      }
    }

    /**
     * Simple constructor. Build a polynomial from its coefficients
     *
     * @param a coefficients array, the a[0] array element is the constant term while the
     *     a[a.length-1] element is the leeding degree coefficient. The array is copied in a new
     *     array, so it can be changed once the constructor as returned.
     */
    public Double(double[] a) {

      // remove null high degree coefficients
      int i = a.length - 1;
      while ((i > 0) && (a[i] == 0)) {
        --i;
      }

      // copy the remaining coefficients
      this.a = new double[i + 1];
      System.arraycopy(a, 0, this.a, 0, i + 1);
    }

    /**
     * Simple constructor. Build a one-term polynomial from one coefficient and the corresponding
     * degree
     *
     * @param c coefficient
     * @param degree degree associated with the coefficient
     */
    public Double(double c, int degree) {
      if ((c == 0) || degree < 0) {
        a = new double[] {0.0};
      } else {
        a = new double[degree + 1];
        Arrays.fill(a, 0, degree, 0.0);
        a[degree] = c;
      }
    }

    /**
     * Simple constructor. Build a {@link Polynomial.Double Polynomial.Double} from a {@link
     * Polynomial.Rational Polynomial.Rational}
     *
     * @param r a rational polynomial
     */
    public Double(Rational r) {
      // convert the coefficients
      a = new double[r.a.length];
      for (int i = 0; i < a.length; ++i) {
        a[i] = r.a[i].doubleValue();
      }
    }

    /**
     * Check if the instance is the null polynomial.
     *
     * @return true if the polynomial is null
     */
    public boolean isZero() {
      return (a.length == 1) && (a[0] == 0);
    }

    /**
     * Check if the instance is the constant unit polynomial.
     *
     * @return true if the polynomial is the constant unit polynomial
     */
    public boolean isOne() {
      return (a.length == 1) && ((a[0] - 1.0) == 0);
    }

    /**
     * Check if the instance is the identity polynomial.
     *
     * @return true if the polynomial is the identity polynomial
     */
    public boolean isIdentity() {
      return (a.length == 2) && (a[0] == 0) && ((a[1] - 1.0) == 0);
    }

    /**
     * Get the polynomial degree.
     *
     * @return degree
     */
    public int getDegree() {
      return a.length - 1;
    }

    /**
     * Get the coefficients of the polynomial.
     *
     * @return a copy of the coefficients array, the array element at index 0 is the constant term
     *     while the element at index a.length-1 is the leading degree coefficient
     */
    public double[] getCoefficients() {
      return a.clone();
    }

    /**
     * Add a polynomial to the instance
     *
     * @param p polynomial to add
     * @return a new polynomial which is the sum of the instance and p
     */
    public Double add(Double p) {

      // identify the lowest degree polynomial
      int lowLength = Math.min(a.length, p.a.length);
      int highLength = Math.max(a.length, p.a.length);

      // build the coefficients array
      double[] newA = new double[highLength];
      for (int i = 0; i < lowLength; ++i) {
        newA[i] = a[i] + p.a[i];
      }
      System.arraycopy(
          (a.length < p.a.length) ? p.a : a, lowLength, newA, lowLength, highLength - lowLength);

      return new Double(newA);
    }

    /**
     * Subtract a polynomial from the instance.
     *
     * @param p polynomial to subtract
     * @return a new polynomial which is the difference the instance minus p
     */
    public Double subtract(Double p) {

      // identify the lowest degree polynomial
      int lowLength = Math.min(a.length, p.a.length);
      int highLength = Math.max(a.length, p.a.length);

      // build the coefficients array
      double[] newA = new double[highLength];
      for (int i = 0; i < lowLength; ++i) {
        newA[i] = a[i] - p.a[i];
      }
      if (a.length < p.a.length) {
        for (int i = lowLength; i < highLength; ++i) {
          newA[i] = -p.a[i];
        }
      } else {
        System.arraycopy(a, lowLength, newA, lowLength, highLength - lowLength);
      }

      return new Double(newA);
    }

    /**
     * Negate the instance.
     *
     * @return a new polynomial
     */
    public Polynomial negate() {
      double[] newA = new double[a.length];
      for (int i = 0; i < a.length; ++i) {
        newA[i] = -a[i];
      }
      return new Double(newA);
    }

    /**
     * Multiply the instance by a polynomial.
     *
     * @param p polynomial to multiply by
     * @return a new polynomial
     */
    public Double multiply(Double p) {

      double[] newA = new double[a.length + p.a.length - 1];

      for (int i = 0; i < newA.length; ++i) {
        newA[i] = 0.0;
        for (int j = Math.max(0, i + 1 - p.a.length); j < Math.min(a.length, i + 1); ++j) {
          newA[i] += a[j] * p.a[i - j];
        }
      }

      return new Double(newA);
    }

    /**
     * Multiply the instance by a constant.
     *
     * @param l constant to multiply by
     * @return a new polynomial
     */
    public Polynomial multiply(long l) {
      return multiply((double) l);
    }

    /**
     * Multiply the instance by a constant.
     *
     * @param r constant to multiply by
     * @return a new polynomial
     */
    public Polynomial multiply(RationalNumber r) {
      return multiply(r.doubleValue());
    }

    /**
     * Multiply the instance by a constant.
     *
     * @param r constant to multiply by
     * @return a new polynomial
     */
    public Polynomial multiply(double r) {

      if (r == 0) {
        return new Double(new double[] {0.0});
      }

      double[] newA = new double[a.length];
      for (int i = 0; i < a.length; ++i) {
        newA[i] = a[i] * r;
      }
      return new Double(newA);
    }

    /**
     * Get the value of the polynomial for a specified unknown.
     *
     * @param x value of the unknown
     * @return value of the polynomial
     */
    public double valueAt(double x) {
      double y = 0;
      for (int i = a.length - 1; i >= 0; --i) {
        y = y * x + a[i];
      }
      return y;
    }

    /**
     * Get the derivative of the instance with respect to the unknown. The derivative of an n degree
     * polynomial is an n-1 degree polynomial of the same type.
     *
     * @return a new polynomial which is the derivative of the instance
     */
    public Polynomial getDerivative() {
      if (a.length == 1) {
        return new Double();
      }
      double[] newA = new double[a.length - 1];
      for (int i = 1; i < a.length; ++i) {
        newA[i - 1] = a[i] * i;
      }
      return new Double(newA);
    }

    /**
     * Returns a string representation of the polynomial.
     *
     * <p>The representation is user oriented. Terms are displayed lowest degrees first. The
     * multiplications signs, coefficients equals to one and null terms are not displayed (except if
     * the polynomial is 0, in which case the 0 constant term is displayed). Addition of terms with
     * negative coefficients are replaced by subtraction of terms with positive coefficients except
     * for the first displayed term (i.e. we display <code>-3</code> for a constant negative
     * polynomial, but <code>1 - 3 x + x^2</code> if the negative coefficient is not the first one
     * displayed).
     *
     * <p>Because coefficients are doubles, the textual form uses the default {@code
     * Double#toString} double formatting. The output is intended for logging and debugging, not
     * exact recovery of the original polynomial.
     *
     * @return a string representation of the polynomial suitable for human inspection
     */
    public String toString() {

      StringBuilder s = new StringBuilder();
      for (int i = 0; i < a.length; ++i) {
        double coefficient = a[i];
        if (coefficient != 0) {
          appendTerm(s, coefficient, i);
        }
      }

      return s.isEmpty() ? "0" : s.toString();
    }

    private void appendTerm(StringBuilder s, double coefficient, int degree) {
      boolean firstTerm = s.isEmpty();
      boolean negative = coefficient < 0;

      if (!firstTerm) {
        s.append(negative ? " - " : " + ");
      } else if (negative) {
        s.append('-');
      }

      double absAi = Math.abs(coefficient);
      boolean needsCoefficient = (degree == 0) || ((absAi - 1) != 0);
      if (needsCoefficient) {
        s.append(absAi);
      }

      if (degree > 0) {
        if (needsCoefficient) {
          s.append(' ');
        }
        s.append('x');
        if (degree > 1) {
          s.append('^');
          s.append(degree);
        }
      }
    }

    /** Coefficients array. */
    protected double[] a;

    @Serial private static final long serialVersionUID = -4210522025715687648L;
  }
}
