package network.crypta.platform.appcatalog;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.nio.file.attribute.PosixFilePermission;
import java.nio.file.attribute.PosixFilePermissions;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.StringJoiner;
import java.util.zip.ZipEntry;
import java.util.zip.ZipException;
import java.util.zip.ZipFile;
import network.crypta.platform.appdist.AppApiCompatibilityMetadata;
import network.crypta.platform.appdist.AppBundleManifest;
import network.crypta.platform.appdist.AppBundleManifestParser;
import network.crypta.platform.appdist.AppBundlePackager;
import network.crypta.platform.appdist.AppDistributionException;

/**
 * Deterministic writer for developer-authored app catalog properties.
 *
 * <p>The writer consumes one or more {@link AppCatalogEntryDescriptor} files, reads each referenced
 * local ZIP artifact, derives default app metadata from the root {@code cryptad-app.properties}
 * manifest, computes the exact ZIP byte size and lowercase SHA-256 digest, and emits a strict
 * {@code cryptad-app-catalog.properties} payload accepted by {@link AppCatalogParser}. Descriptor
 * {@code app.id} and {@code version} values are treated as consistency checks against the artifact
 * manifest, not as replacements for manifest-bound fields. That keeps generated catalogs compatible
 * with the runtime installer, which verifies the catalog entry against the extracted bundle before
 * accepting an installation or update.
 *
 * <p>This class is stateless and safe to call from multiple tooling invocations. It deliberately
 * stops at byte generation and optional file output; signing remains the responsibility of {@link
 * AppCatalogSigner}, which signs the exact bytes written here.
 *
 * @see AppCatalogBuildRequest
 * @see AppCatalogEntryDescriptor
 */
public final class AppCatalogWriter {
  private static final int COPY_BUFFER_BYTES = 64 * 1024;
  private static final String CATALOG_PARAMETER_NAME = "catalog";
  private static final String REPLACEMENT_APP_ID = "replacementAppId";

  private AppCatalogWriter() {}

  /**
   * Builds a catalog from descriptor files and optionally writes it to disk.
   *
   * <p>The returned catalog is parsed back from the generated bytes before the optional file write,
   * so a successful result proves that the emitted ordering and fields are compatible with the
   * production catalog parser. Each descriptor is processed in request order. The writer reads the
   * referenced artifact as a regular no-symlink file, copies it into a bounded temporary snapshot,
   * computes the byte size and SHA-256 digest from that snapshot, and reads only the snapshot's
   * root bundle manifest for catalog metadata. It does not sign the catalog or copy bundle
   * artifacts into the catalog.
   *
   * @param request catalog metadata, descriptor files, and optional output file
   * @return generated catalog, exact serialized bytes, and optional written output path
   * @throws IOException if descriptor, artifact, or output files cannot be read or written
   * @throws AppCatalogException if descriptor metadata or artifact structure is malformed
   */
  public static WriteResult write(AppCatalogBuildRequest request) throws IOException {
    AppCatalogBuildRequest checkedRequest = Objects.requireNonNull(request, "request");
    List<AppCatalogEntry> entries =
        buildEntries(checkedRequest.entryDescriptorFiles(), checkedRequest.reviewReceiptFiles());
    AppCatalog catalog =
        new AppCatalog(
            catalogVersion(entries, checkedRequest.securityPolicy()),
            checkedRequest.catalogId(),
            checkedRequest.catalogName(),
            checkedRequest.generatedAt(),
            checkedRequest.securityPolicy(),
            entries);
    byte[] catalogBytes = serialize(catalog);
    AppCatalog parsedCatalog = AppCatalogParser.parse(catalogBytes);
    Path outputFile = checkedRequest.outputFile().orElse(null);
    if (outputFile != null) {
      writeCatalogBytes(outputFile, catalogBytes);
      return new WriteResult(parsedCatalog, catalogBytes, outputFile);
    }
    return new WriteResult(parsedCatalog, catalogBytes);
  }

  /**
   * Serializes an already validated catalog using the canonical parser-compatible key order.
   *
   * <p>This method does not sign or write sidecars. It is useful for tests and controlled tooling
   * that already assembled {@link AppCatalogEntry} instances but still needs byte-for-byte stable
   * catalog properties before passing them to {@link AppCatalogSigner}. The returned bytes use
   * UTF-8 and preserve the entry order carried by the catalog model. Callers are responsible for
   * using values that already satisfy the catalog parser's single-line and artifact metadata rules.
   *
   * @param catalog validated catalog model to encode in catalog properties form
   * @return UTF-8 catalog properties bytes in deterministic writer order
   */
  public static byte[] serialize(AppCatalog catalog) {
    AppCatalog checkedCatalog = Objects.requireNonNull(catalog, CATALOG_PARAMETER_NAME);
    requireCatalogVersionMatchesEntries(checkedCatalog);
    StringBuilder builder = new StringBuilder();
    appendProperty(builder, "catalog.version", Integer.toString(checkedCatalog.version()));
    appendProperty(builder, "catalog.id", checkedCatalog.catalogId());
    appendProperty(builder, "catalog.name", checkedCatalog.name());
    appendProperty(builder, "catalog.generatedAt", checkedCatalog.generatedAt().toString());
    appendProperty(builder, "catalog.entries", joinAppIds(checkedCatalog.entries()));
    appendSecurityPolicy(builder, checkedCatalog.securityPolicy());
    for (AppCatalogEntry entry : checkedCatalog.entries()) {
      appendEntry(builder, entry);
    }
    return builder.toString().getBytes(StandardCharsets.UTF_8);
  }

  private static List<AppCatalogEntry> buildEntries(
      List<Path> descriptorFiles, List<Path> reviewReceiptFiles) throws IOException {
    Map<ReviewReceiptKey, AppReviewReceipt> receipts = loadReviewReceipts(reviewReceiptFiles);
    List<AppCatalogEntry> entries = new ArrayList<>(descriptorFiles.size());
    for (Path descriptorFile : descriptorFiles) {
      AppCatalogEntry entry = inspectEntryDescriptor(descriptorFile).entry();
      entries.add(withMatchingReviewReceipt(entry, receipts));
    }
    if (!receipts.isEmpty()) {
      throw AppCatalogSidecars.invalidEntry("review receipt does not match any catalog entry");
    }
    return List.copyOf(entries);
  }

  private static Map<ReviewReceiptKey, AppReviewReceipt> loadReviewReceipts(List<Path> receiptFiles)
      throws IOException {
    Map<ReviewReceiptKey, AppReviewReceipt> receipts = new LinkedHashMap<>();
    for (Path receiptFile : receiptFiles) {
      AppReviewReceipt receipt = AppReviewReceiptIO.read(receiptFile);
      ReviewReceiptKey key = ReviewReceiptKey.fromReceipt(receipt);
      AppReviewReceipt previous = receipts.putIfAbsent(key, receipt);
      if (previous != null) {
        throw AppCatalogSidecars.invalidEntry("duplicate review receipt for catalog entry");
      }
    }
    return receipts;
  }

  private static AppCatalogEntry withMatchingReviewReceipt(
      AppCatalogEntry entry, Map<ReviewReceiptKey, AppReviewReceipt> receipts) {
    AppReviewReceipt receipt = receipts.remove(ReviewReceiptKey.fromEntry(entry));
    if (receipt == null) {
      return entry;
    }
    return new AppCatalogEntry(
        entry.appId(),
        entry.name(),
        entry.version(),
        entry.summary(),
        entry.homepage().orElse(null),
        entry.source().orElse(null),
        entry.license().orElse(null),
        entry.categories(),
        entry.compatibility(),
        entry.review(),
        receipt,
        entry.changelog(),
        entry.screenshots(),
        entry.productionMetadata(),
        entry.maintenanceMetadata(),
        entry.bundleUri(),
        entry.bundleSha256(),
        entry.bundleSizeBytes(),
        entry.bundleType(),
        entry.permissions(),
        entry.permissionRationales());
  }

  /**
   * Parses and inspects one catalog entry descriptor.
   *
   * <p>This helper is intended for developer tooling that needs to verify descriptor metadata
   * against the referenced bundle before writing a full catalog. It applies the same artifact
   * snapshot, manifest parsing, and descriptor consistency checks used by {@link #write}.
   *
   * @param descriptorFile descriptor sidecar to parse
   * @return inspected descriptor, generated catalog entry, and artifact manifest
   * @throws IOException if the descriptor or artifact cannot be read
   * @throws AppCatalogException if descriptor metadata or artifact structure is malformed
   */
  public static CatalogEntryInspection inspectEntryDescriptor(Path descriptorFile)
      throws IOException {
    AppCatalogEntryDescriptor descriptor = AppCatalogEntryDescriptor.parse(descriptorFile);
    ArtifactMetadata artifact = inspectArtifact(descriptor.artifactPath());
    return new CatalogEntryInspection(
        descriptor, toEntry(descriptor, artifact), artifact.manifest());
  }

  private static int catalogVersion(
      List<AppCatalogEntry> entries, AppCatalogSecurityPolicy securityPolicy) {
    for (AppCatalogEntry entry : entries) {
      if (entry.hasMaintenanceMetadata()) {
        return AppCatalog.VERSION_FIRST_PARTY_MAINTENANCE;
      }
    }
    if (securityPolicy.hasCatalogFields()) {
      return AppCatalog.VERSION_SECURITY_POLICY;
    }
    for (AppCatalogEntry entry : entries) {
      if (entry.hasProductionMetadata()) {
        return AppCatalog.VERSION_PRODUCTION_CHANNELS;
      }
    }
    for (AppCatalogEntry entry : entries) {
      if (entry.hasStoreMetadata()) {
        return AppCatalog.VERSION_STORE_METADATA;
      }
    }
    return AppCatalog.VERSION_MINIMAL;
  }

  private static void requireCatalogVersionMatchesEntries(AppCatalog catalog) {
    if (catalog.securityPolicy().hasCatalogFields()
        && catalog.version() < AppCatalog.VERSION_SECURITY_POLICY) {
      throw AppCatalogSidecars.invalidEntry(
          "catalog.version 4 is required when security policy metadata is present");
    }
    for (AppCatalogEntry entry : catalog.entries()) {
      if (entry.hasMaintenanceMetadata()
          && catalog.version() < AppCatalog.VERSION_FIRST_PARTY_MAINTENANCE) {
        throw AppCatalogSidecars.invalidEntry(
            "catalog.version 5 is required when maintenance metadata is present");
      }
    }
    if (catalog.version() >= AppCatalog.VERSION_PRODUCTION_CHANNELS) {
      return;
    }
    for (AppCatalogEntry entry : catalog.entries()) {
      if (entry.hasProductionMetadata()) {
        throw AppCatalogSidecars.invalidEntry(
            "catalog.version 3 is required when production channel metadata is present");
      }
    }
    if (catalog.version() == AppCatalog.VERSION_STORE_METADATA) {
      return;
    }
    for (AppCatalogEntry entry : catalog.entries()) {
      if (entry.hasStoreMetadata()) {
        throw AppCatalogSidecars.invalidEntry(
            "catalog.version 2 is required when app-store or API metadata is present");
      }
    }
  }

  private static AppCatalogEntry toEntry(
      AppCatalogEntryDescriptor descriptor, ArtifactMetadata artifact) {
    AppBundleManifest manifest = artifact.manifest();
    String appId = manifest.appId();
    String version = manifest.appVersion();
    requireManifestAppIdMatch(descriptor, appId);
    requireManifestVersionMatch(descriptor, version);
    return new AppCatalogEntry(
        appId,
        descriptor.nameOverride().orElse(manifest.appName()),
        version,
        descriptor.summary(),
        descriptor.homepage().orElse(null),
        descriptor.source().orElse(null),
        descriptor.license().orElse(null),
        descriptor.categories(),
        compatibilityForCatalog(descriptor, manifest),
        descriptor.review(),
        descriptor.changelog(),
        descriptor.screenshots(),
        descriptor.productionMetadata(),
        descriptor.maintenanceMetadata(),
        descriptor.bundleUri(),
        artifact.sha256(),
        artifact.sizeBytes(),
        AppCatalogEntry.ZIP_BUNDLE_TYPE,
        descriptor.permissionsOverride().orElse(manifest.permissions()),
        descriptor.permissionRationales());
  }

  private static AppCatalogCompatibilityMetadata compatibilityForCatalog(
      AppCatalogEntryDescriptor descriptor, AppBundleManifest manifest) {
    AppCatalogCompatibilityMetadata descriptorCompatibility = descriptor.compatibility();
    AppApiCompatibilityMetadata apiCompatibility =
        descriptorCompatibility.apiCompatibility().declared()
            ? descriptorCompatibility.apiCompatibility()
            : manifest.apiCompatibility();
    return new AppCatalogCompatibilityMetadata(
        descriptorCompatibility.minimumCryptaVersion(),
        descriptorCompatibility.maximumCryptaVersion(),
        apiCompatibility);
  }

  private static void requireManifestAppIdMatch(
      AppCatalogEntryDescriptor descriptor, String manifestAppId) {
    Optional<String> appIdOverride = descriptor.appIdOverride();
    if (appIdOverride.isEmpty()) {
      return;
    }
    String descriptorAppId = AppCatalogEntry.normalizeAppId(appIdOverride.get());
    if (!manifestAppId.equals(descriptorAppId)) {
      throw AppCatalogSidecars.invalidEntry(
          "catalog entry descriptor app.id must match artifact manifest app.id: "
              + descriptorAppId
              + " != "
              + manifestAppId);
    }
  }

  private static void requireManifestVersionMatch(
      AppCatalogEntryDescriptor descriptor, String manifestVersion) {
    Optional<String> versionOverride = descriptor.versionOverride();
    if (versionOverride.isEmpty()) {
      return;
    }
    String descriptorVersion = versionOverride.get();
    if (!manifestVersion.equals(descriptorVersion)) {
      throw AppCatalogSidecars.invalidEntry(
          "catalog entry descriptor version must match artifact manifest app.version: "
              + descriptorVersion
              + " != "
              + manifestVersion);
    }
  }

  private static ArtifactMetadata inspectArtifact(Path artifactPath) throws IOException {
    Path normalizedArtifact =
        Objects.requireNonNull(artifactPath, "artifactPath").toAbsolutePath().normalize();
    requireReadableArtifactFile(normalizedArtifact);
    ArtifactSnapshot snapshot = snapshotArtifact(normalizedArtifact);
    try {
      AppBundleManifest manifest = readRootManifest(snapshot.file());
      return new ArtifactMetadata(snapshot.sha256(), snapshot.sizeBytes(), manifest);
    } finally {
      Files.deleteIfExists(snapshot.file());
    }
  }

  private static void requireReadableArtifactFile(Path artifactPath) {
    if (Files.isSymbolicLink(artifactPath)) {
      throw AppCatalogSidecars.invalidEntry("artifact.path must not be a symbolic link");
    }
    if (!Files.isRegularFile(artifactPath, LinkOption.NOFOLLOW_LINKS)) {
      throw AppCatalogSidecars.invalidEntry("artifact.path must be a regular file");
    }
  }

  private static ArtifactSnapshot snapshotArtifact(Path artifactPath) throws IOException {
    MessageDigest digest = AppCatalogSidecars.newArtifactSha256Digest();
    long sizeBytes = 0L;
    byte[] buffer = new byte[COPY_BUFFER_BYTES];
    Path snapshot = createSnapshotFile();
    try (InputStream input = Files.newInputStream(artifactPath, LinkOption.NOFOLLOW_LINKS);
        OutputStream output =
            Files.newOutputStream(
                snapshot, StandardOpenOption.WRITE, StandardOpenOption.TRUNCATE_EXISTING)) {
      int bytesRead;
      while ((bytesRead = input.read(buffer)) >= 0) {
        if (bytesRead == 0) {
          continue;
        }
        sizeBytes += bytesRead;
        if (sizeBytes > AppCatalogSidecars.MAX_ARTIFACT_BYTES) {
          throw AppCatalogSidecars.invalidEntry("artifact.path exceeds the artifact size cap");
        }
        digest.update(buffer, 0, bytesRead);
        output.write(buffer, 0, bytesRead);
      }
      return new ArtifactSnapshot(
          snapshot, AppCatalogSidecars.lowercaseHex(digest.digest()), sizeBytes);
    } catch (IOException | RuntimeException exception) {
      Files.deleteIfExists(snapshot);
      throw exception;
    }
  }

  // The file name is generated by the JDK, the file is created before bytes are copied into it,
  // and POSIX hosts receive owner-only permissions. The snapshot is removed in the caller's
  // finally block after ZIP metadata has been read from the same immutable byte copy.
  @SuppressWarnings("java:S5443")
  private static Path createSnapshotFile() throws IOException {
    try {
      return Files.createTempFile(
          "cryptad-catalog-artifact-",
          ".zip",
          PosixFilePermissions.asFileAttribute(
              Set.of(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE)));
    } catch (UnsupportedOperationException _) {
      Path snapshot = Files.createTempFile("cryptad-catalog-artifact-", ".zip");
      try {
        restrictPortableSnapshotPermissions(snapshot);
        return snapshot;
      } catch (IOException | RuntimeException exception) {
        Files.deleteIfExists(snapshot);
        throw exception;
      }
    }
  }

  private static void restrictPortableSnapshotPermissions(Path snapshot) throws IOException {
    java.io.File file = snapshot.toFile();
    if (!file.setReadable(true, true)
        || !file.setWritable(true, true)
        || !file.setExecutable(false, true)) {
      throw new IOException("failed to restrict catalog artifact snapshot permissions");
    }
  }

  // Archive inspection is safe here: the writer reads the ZIP central directory, rejects artifacts
  // over the installer entry cap, and decompresses only the bounded root manifest entry.
  @SuppressWarnings("java:S5042")
  private static AppBundleManifest readRootManifest(Path artifactPath) throws IOException {
    ZipEntry manifestEntry = null;
    try (ZipFile zip = new ZipFile(artifactPath.toFile(), StandardCharsets.UTF_8)) {
      requireZipEntryCountWithinCatalogCap(zip);
      Enumeration<? extends ZipEntry> entries = zip.entries();
      while (entries.hasMoreElements()) {
        ZipEntry entry = entries.nextElement();
        if (AppBundleManifestParser.MANIFEST_FILE_NAME.equals(entry.getName())) {
          if (manifestEntry != null) {
            throw AppCatalogSidecars.invalidEntry(
                "artifact ZIP contains duplicate root cryptad-app.properties entries");
          }
          if (entry.isDirectory()) {
            throw AppCatalogSidecars.invalidEntry(
                "artifact ZIP root cryptad-app.properties must be a file");
          }
          manifestEntry = entry;
        }
      }
      if (manifestEntry == null) {
        throw AppCatalogSidecars.invalidEntry(
            "artifact ZIP must contain cryptad-app.properties at the root");
      }
      return parseManifest(readManifestEntry(zip, manifestEntry));
    } catch (ZipException exception) {
      throw new AppCatalogException(
          AppCatalogSidecars.INVALID_CATALOG_ENTRY,
          "artifact.path must point to a readable ZIP file",
          exception);
    }
  }

  private static void requireZipEntryCountWithinCatalogCap(ZipFile zip) {
    if (zip.size() > AppBundlePackager.MAX_CATALOG_ZIP_ENTRIES) {
      throw AppCatalogSidecars.invalidEntry(
          "artifact ZIP contains too many entries for catalog installation");
    }
  }

  private static byte[] readManifestEntry(ZipFile zip, ZipEntry manifestEntry) throws IOException {
    byte[] buffer = new byte[COPY_BUFFER_BYTES];
    long totalBytes = 0L;
    try (InputStream input = zip.getInputStream(manifestEntry);
        ByteArrayOutputStream output = new ByteArrayOutputStream()) {
      int bytesRead;
      while ((bytesRead = input.read(buffer)) >= 0) {
        if (bytesRead == 0) {
          continue;
        }
        totalBytes += bytesRead;
        if (totalBytes > AppCatalogSidecars.MAX_CATALOG_BYTES) {
          throw AppCatalogSidecars.invalidEntry(
              "artifact root cryptad-app.properties exceeds the allowed size");
        }
        output.write(buffer, 0, bytesRead);
      }
      return output.toByteArray();
    }
  }

  private static AppBundleManifest parseManifest(byte[] manifestBytes) throws IOException {
    try {
      return AppBundleManifestParser.parseContent(
          new String(manifestBytes, StandardCharsets.UTF_8));
    } catch (AppDistributionException exception) {
      throw new AppCatalogException(
          AppCatalogSidecars.INVALID_CATALOG_ENTRY,
          "artifact root cryptad-app.properties is invalid: " + exception.getMessage(),
          exception);
    }
  }

  private static void writeCatalogBytes(Path outputFile, byte[] catalogBytes) throws IOException {
    Path normalizedOutput =
        Objects.requireNonNull(outputFile, "outputFile").toAbsolutePath().normalize();
    if (normalizedOutput.getFileName() == null) {
      throw new IOException("catalog output path must name a file");
    }
    Path parent = normalizedOutput.getParent();
    if (parent != null) {
      createSafeCatalogOutputParent(parent);
    }
    requireWritableCatalogOutput(normalizedOutput);
    Files.write(
        normalizedOutput,
        catalogBytes,
        StandardOpenOption.CREATE,
        StandardOpenOption.TRUNCATE_EXISTING,
        StandardOpenOption.WRITE,
        LinkOption.NOFOLLOW_LINKS);
  }

  private static void createSafeCatalogOutputParent(Path parent) throws IOException {
    Path outputParent = Objects.requireNonNull(parent, "parent");
    Path existingAncestor = outputParent;
    while (existingAncestor != null && !Files.exists(existingAncestor, LinkOption.NOFOLLOW_LINKS)) {
      existingAncestor = existingAncestor.getParent();
    }
    if (existingAncestor != null
        && (Files.isSymbolicLink(existingAncestor)
            || !Files.isDirectory(existingAncestor, LinkOption.NOFOLLOW_LINKS))) {
      throw new IOException("catalog output parent must be a real directory: " + existingAncestor);
    }
    Files.createDirectories(outputParent);
    if (Files.isSymbolicLink(outputParent)
        || !Files.isDirectory(outputParent, LinkOption.NOFOLLOW_LINKS)) {
      throw new IOException("catalog output parent must be a real directory: " + outputParent);
    }
  }

  private static void requireWritableCatalogOutput(Path outputFile) throws IOException {
    if (!Files.exists(outputFile, LinkOption.NOFOLLOW_LINKS)) {
      return;
    }
    if (Files.isSymbolicLink(outputFile)) {
      throw new IOException("catalog output path must not be a symbolic link: " + outputFile);
    }
    if (!Files.isRegularFile(outputFile, LinkOption.NOFOLLOW_LINKS)) {
      throw new IOException("catalog output path must be a regular file: " + outputFile);
    }
  }

  private static String joinAppIds(List<AppCatalogEntry> entries) {
    StringJoiner joiner = new StringJoiner(",");
    for (AppCatalogEntry entry : entries) {
      joiner.add(entry.appId());
    }
    return joiner.toString();
  }

  private static void appendEntry(StringBuilder builder, AppCatalogEntry entry) {
    String prefix = "app." + entry.appId() + ".";
    appendProperty(builder, prefix + "id", entry.appId());
    appendProperty(builder, prefix + "name", entry.name());
    appendProperty(builder, prefix + "version", entry.version());
    appendProperty(builder, prefix + "summary", entry.summary());
    entry.homepage().ifPresent(uri -> appendProperty(builder, prefix + "homepage", uri.toString()));
    entry.source().ifPresent(uri -> appendProperty(builder, prefix + "source", uri.toString()));
    entry.license().ifPresent(value -> appendProperty(builder, prefix + "license", value));
    if (!entry.categories().isEmpty()) {
      appendProperty(builder, prefix + "categories", joinValues(entry.categories()));
    }
    String minimumCryptaVersion = entry.compatibility().minimumCryptaVersion();
    if (minimumCryptaVersion != null) {
      appendProperty(builder, prefix + "minimumCryptaVersion", minimumCryptaVersion);
    }
    String maximumCryptaVersion = entry.compatibility().maximumCryptaVersion();
    if (maximumCryptaVersion != null) {
      appendProperty(builder, prefix + "maximumCryptaVersion", maximumCryptaVersion);
    }
    appendApiCompatibility(builder, prefix, entry.compatibility());
    appendProductionMetadata(builder, prefix, entry.productionMetadata());
    appendMaintenanceMetadata(builder, prefix, entry.maintenanceMetadata());
    if (entry.review().hasCatalogFields()) {
      appendProperty(builder, prefix + "review.status", entry.review().status().catalogValue());
      entry
          .review()
          .note()
          .ifPresent(value -> appendProperty(builder, prefix + "review.note", value));
    }
    entry
        .reviewReceipt()
        .ifPresent(receipt -> AppReviewReceiptIO.appendReceiptProperties(builder, prefix, receipt));
    if (!entry.permissionRationales().isEmpty()) {
      entry
          .permissionRationales()
          .forEach(
              (permission, rationale) ->
                  appendProperty(
                      builder, prefix + "permissions.rationale." + permission, rationale));
    }
    for (int index = 0; index < entry.screenshots().size(); index++) {
      appendProperty(
          builder, prefix + "screenshot." + (index + 1), entry.screenshots().get(index).toString());
    }
    entry
        .changelog()
        .summary()
        .ifPresent(value -> appendProperty(builder, prefix + "changelog.summary", value));
    entry
        .changelog()
        .uri()
        .ifPresent(uri -> appendProperty(builder, prefix + "changelog.uri", uri.toString()));
    appendProperty(builder, prefix + "bundle.uri", entry.bundleUri().toString());
    appendProperty(builder, prefix + "bundle.sha256", entry.bundleSha256());
    appendProperty(builder, prefix + "bundle.size.bytes", Long.toString(entry.bundleSizeBytes()));
    appendProperty(builder, prefix + "bundle.type", entry.bundleType());
    appendProperty(builder, prefix + "permissions", joinValues(entry.permissions()));
  }

  private static String joinValues(List<String> values) {
    StringJoiner joiner = new StringJoiner(",");
    for (String value : values) {
      joiner.add(value);
    }
    return joiner.toString();
  }

  private static void appendApiCompatibility(
      StringBuilder builder, String prefix, AppCatalogCompatibilityMetadata compatibility) {
    var api = compatibility.apiCompatibility();
    if (api.minimumVersion() != null) {
      appendProperty(builder, prefix + "api.minimumVersion", api.minimumVersion().toString());
    }
    if (api.maximumTestedVersion() != null) {
      appendProperty(
          builder, prefix + "api.maximumTestedVersion", api.maximumTestedVersion().toString());
    }
    if (!api.optionalCapabilities().isEmpty()) {
      appendProperty(
          builder, prefix + "api.optionalCapabilities", joinValues(api.optionalCapabilities()));
    }
    if (api.declared()) {
      appendProperty(
          builder,
          prefix + "api.experimentalCapabilitiesAccepted",
          Boolean.toString(api.experimentalCapabilitiesAccepted()));
    }
  }

  private static void appendProductionMetadata(
      StringBuilder builder, String prefix, AppCatalogProductionMetadata metadata) {
    if (!metadata.hasCatalogFields()) {
      return;
    }
    appendProperty(builder, prefix + "channel", metadata.channel().catalogValue());
    appendProperty(builder, prefix + "support.status", metadata.supportStatus().catalogValue());
    appendProperty(
        builder, prefix + "deprecation.status", metadata.deprecationStatus().catalogValue());
    metadata
        .deprecationMessage()
        .ifPresent(value -> appendProperty(builder, prefix + "deprecation.message", value));
    metadata
        .replacementAppId()
        .ifPresent(value -> appendProperty(builder, prefix + REPLACEMENT_APP_ID, value));
    if (metadata.securityAdvisories().isEmpty()) {
      return;
    }
    appendProperty(
        builder,
        prefix + "securityAdvisories",
        joinValues(
            metadata.securityAdvisories().stream().map(AppCatalogSecurityAdvisory::id).toList()));
    for (AppCatalogSecurityAdvisory advisory : metadata.securityAdvisories()) {
      appendProperty(
          builder,
          prefix + "securityAdvisory." + advisory.id() + ".uri",
          advisory.uri().toString());
    }
  }

  private static void appendMaintenanceMetadata(
      StringBuilder builder, String prefix, AppCatalogMaintenanceMetadata metadata) {
    if (!metadata.hasCatalogFields()) {
      return;
    }
    appendProperty(builder, prefix + "maintenance.owner", metadata.owner().orElseThrow());
    metadata
        .ownerUri()
        .ifPresent(uri -> appendProperty(builder, prefix + "maintenance.ownerUri", uri.toString()));
    appendProperty(
        builder,
        prefix + "maintenance.supportLevel",
        metadata.supportLevel().orElseThrow().catalogValue());
    appendProperty(
        builder,
        prefix + "maintenance.dataSchemaPolicy",
        metadata.dataSchemaPolicy().orElseThrow().catalogValue());
    appendProperty(
        builder,
        prefix + "maintenance.migrationPolicy",
        metadata.migrationPolicy().orElseThrow().catalogValue());
    appendProperty(
        builder,
        prefix + "maintenance.backupRestore",
        metadata.backupRestore().orElseThrow().catalogValue());
    appendProperty(
        builder,
        prefix + "maintenance.securityPolicy",
        metadata.securityPolicy().orElseThrow().catalogValue());
    appendProperty(
        builder,
        prefix + "maintenance.deprecationPolicy",
        metadata.deprecationPolicy().orElseThrow().catalogValue());
    metadata
        .supportUri()
        .ifPresent(
            uri -> appendProperty(builder, prefix + "maintenance.supportUri", uri.toString()));
  }

  private static void appendSecurityPolicy(
      StringBuilder builder, AppCatalogSecurityPolicy securityPolicy) {
    if (!securityPolicy.hasCatalogFields()) {
      return;
    }
    if (!securityPolicy.advisories().isEmpty()) {
      appendProperty(
          builder,
          "catalog.securityAdvisories",
          joinValues(
              securityPolicy.advisories().stream()
                  .map(AppCatalogSecurityAdvisoryRecord::id)
                  .toList()));
      for (AppCatalogSecurityAdvisoryRecord advisory : securityPolicy.advisories()) {
        String prefix = "catalog.securityAdvisory." + advisory.id() + ".";
        appendProperty(builder, prefix + "uri", advisory.uri().toString());
        appendProperty(builder, prefix + "title", advisory.title());
        appendProperty(builder, prefix + "severity", advisory.severity().catalogValue());
        appendProperty(builder, prefix + "status", advisory.status().catalogValue());
        appendProperty(builder, prefix + "action", advisory.action().catalogValue());
        appendProperty(builder, prefix + "summary", advisory.summary());
        appendProperty(builder, prefix + "publishedAt", advisory.publishedAt().toString());
        appendProperty(builder, prefix + "updatedAt", advisory.updatedAt().toString());
        advisory
            .replacementAppId()
            .ifPresent(value -> appendProperty(builder, prefix + REPLACEMENT_APP_ID, value));
        advisory
            .safeUninstallGuidance()
            .ifPresent(value -> appendProperty(builder, prefix + "safeUninstallGuidance", value));
      }
    }
    if (!securityPolicy.denylist().isEmpty()) {
      appendProperty(
          builder,
          "catalog.securityDenylist",
          joinValues(
              securityPolicy.denylist().stream().map(AppCatalogVersionDenylistEntry::id).toList()));
      for (AppCatalogVersionDenylistEntry denylistEntry : securityPolicy.denylist()) {
        String prefix = "catalog.securityDenylist." + denylistEntry.id() + ".";
        appendProperty(builder, prefix + "appId", denylistEntry.appId());
        appendProperty(builder, prefix + "version", denylistEntry.version());
        appendProperty(builder, prefix + "advisoryId", denylistEntry.advisoryId());
        appendProperty(builder, prefix + "reason", denylistEntry.reason());
        denylistEntry
            .replacementAppId()
            .ifPresent(value -> appendProperty(builder, prefix + REPLACEMENT_APP_ID, value));
        denylistEntry
            .safeUninstallGuidance()
            .ifPresent(value -> appendProperty(builder, prefix + "safeUninstallGuidance", value));
      }
    }
  }

  private static void appendProperty(StringBuilder builder, String key, String value) {
    builder.append(key).append('=').append(value).append('\n');
  }

  private record ArtifactSnapshot(Path file, String sha256, long sizeBytes) {}

  private record ArtifactMetadata(String sha256, long sizeBytes, AppBundleManifest manifest) {}

  private record ReviewReceiptKey(
      String appId, String appVersion, String artifactSha256, long artifactSizeBytes) {
    private static ReviewReceiptKey fromEntry(AppCatalogEntry entry) {
      return new ReviewReceiptKey(
          entry.appId(), entry.version(), entry.bundleSha256(), entry.bundleSizeBytes());
    }

    private static ReviewReceiptKey fromReceipt(AppReviewReceipt receipt) {
      AppReviewReceiptPayload payload = receipt.payload();
      return new ReviewReceiptKey(
          payload.appId(),
          payload.appVersion(),
          payload.artifactSha256(),
          payload.artifactSizeBytes());
    }
  }

  /**
   * Descriptor inspection result used by offline compatibility tooling.
   *
   * @param descriptor parsed descriptor sidecar
   * @param entry catalog entry that would be written for the descriptor
   * @param manifest root manifest extracted from the referenced ZIP artifact
   */
  public record CatalogEntryInspection(
      AppCatalogEntryDescriptor descriptor, AppCatalogEntry entry, AppBundleManifest manifest) {}

  /**
   * Result returned after writing or building catalog properties.
   *
   * <p>The result keeps the parsed model and serialized bytes together so tooling can display the
   * catalog summary, sign the exact emitted payload, and report the output location without reading
   * the file back from disk. Instances are immutable. The serialized byte array is copied on both
   * construction and access because those bytes are the material that catalog signatures cover.
   */
  public static final class WriteResult {
    private final AppCatalog catalog;
    private final byte[] catalogBytes;
    private final Path catalogFile;

    /**
     * Creates an immutable in-memory write result.
     *
     * <p>The byte array is defensively copied on construction and access so callers cannot mutate
     * the authenticated payload after passing it to signing or verification helpers.
     *
     * @param catalog parsed catalog model produced from {@code catalogBytes}
     * @param catalogBytes exact UTF-8 bytes for {@code cryptad-app-catalog.properties}
     */
    public WriteResult(AppCatalog catalog, byte[] catalogBytes) {
      this.catalog = Objects.requireNonNull(catalog, CATALOG_PARAMETER_NAME);
      this.catalogBytes = Objects.requireNonNull(catalogBytes, "catalogBytes").clone();
      this.catalogFile = null;
    }

    /**
     * Creates an immutable write result for bytes that were also written to disk.
     *
     * <p>The file path is stored in absolute normalized form. The constructor does not read the
     * file back; the serialized bytes supplied to the result remain the source of truth for signing
     * and tests.
     *
     * @param catalog parsed catalog model produced from {@code catalogBytes}
     * @param catalogBytes exact UTF-8 bytes for {@code cryptad-app-catalog.properties}
     * @param catalogFile output file written by the request
     */
    public WriteResult(AppCatalog catalog, byte[] catalogBytes, Path catalogFile) {
      this.catalog = Objects.requireNonNull(catalog, CATALOG_PARAMETER_NAME);
      this.catalogBytes = Objects.requireNonNull(catalogBytes, "catalogBytes").clone();
      this.catalogFile =
          Objects.requireNonNull(catalogFile, "catalogFile").toAbsolutePath().normalize();
    }

    /**
     * Returns the parsed catalog model produced from the generated bytes.
     *
     * <p>The model has already passed the production parser, so callers can use it for summaries
     * and follow-up validation without reparsing the serialized bytes.
     *
     * @return parsed catalog model represented by the generated properties
     */
    public AppCatalog catalog() {
      return catalog;
    }

    /**
     * Returns the exact generated catalog properties bytes.
     *
     * <p>The returned array is a defensive copy. Mutating it cannot change the result state or any
     * bytes already written to disk.
     *
     * @return defensive copy of {@code cryptad-app-catalog.properties} bytes
     */
    public byte[] catalogBytes() {
      return catalogBytes.clone();
    }

    /**
     * Returns the catalog file written by the request, when configured.
     *
     * <p>An empty value means the request only built bytes in memory. When present, the path is
     * absolute and normalized by the result constructor.
     *
     * @return optional normalized output path for the generated catalog file
     */
    public Optional<Path> catalogFile() {
      return Optional.ofNullable(catalogFile);
    }
  }
}
