package network.crypta.platform.appcatalog;

import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * Input for developer tooling that writes {@code cryptad-app-catalog.properties}.
 *
 * <p>A request supplies catalog-level metadata, a deterministic list of entry descriptor files, and
 * an optional output path. {@link AppCatalogWriter} treats the request as the complete authoring
 * plan for one catalog file: every descriptor is parsed, every referenced bundle artifact is
 * inspected, and the resulting properties are emitted in stable key order. The writer preserves
 * descriptor-file order in {@code catalog.entries}; callers that collect files from a glob should
 * sort that list before constructing the request.
 *
 * <p>The generated timestamp is an explicit input rather than an implicit clock read so catalog
 * authoring can be reproducible in tests, release jobs, and local CLI workflows. Paths are
 * normalized during construction, but the request does not read descriptor contents or bundle
 * artifacts. That validation remains in the writer so callers can build, inspect, and pass around a
 * request without performing file-system work.
 */
public final class AppCatalogBuildRequest {
  private final String catalogId;
  private final String catalogName;
  private final Instant generatedAt;
  private final List<Path> entryDescriptorFiles;
  private final List<Path> reviewReceiptFiles;
  private final AppCatalogSecurityPolicy securityPolicy;
  private final Path outputFile;

  /**
   * Creates a request that returns bytes without writing a catalog file.
   *
   * <p>This overload is useful for tests and command-line flows that want to inspect or sign the
   * generated bytes before deciding where to place them. It delegates to the canonical constructor,
   * so catalog identifiers, names, timestamps, and descriptor paths are validated in the same way
   * as requests that include an output file.
   *
   * @param catalogId stable catalog identifier used as the catalog namespace
   * @param catalogName human-readable catalog name shown in developer output
   * @param generatedAt deterministic generation timestamp for the catalog metadata
   * @param entryDescriptorFiles descriptor files in the exact order written to the catalog
   */
  public AppCatalogBuildRequest(
      String catalogId, String catalogName, Instant generatedAt, List<Path> entryDescriptorFiles) {
    this(
        catalogId,
        catalogName,
        generatedAt,
        entryDescriptorFiles,
        List.of(),
        AppCatalogSecurityPolicy.EMPTY,
        null);
  }

  /**
   * Creates a request with review receipt files and no output file.
   *
   * <p>Receipt paths are normalized and stored in caller-supplied order. {@link AppCatalogWriter}
   * later matches them to descriptor entries by receipt payload binding so catalog authoring can
   * remain deterministic even when receipts are supplied separately from entry descriptors.
   *
   * @param catalogId stable catalog identifier used as the catalog namespace
   * @param catalogName human-readable catalog name shown in developer output
   * @param generatedAt deterministic generation timestamp for the catalog metadata
   * @param entryDescriptorFiles descriptor files in the exact order written to the catalog
   * @param reviewReceiptFiles receipt files to embed into matching catalog entries
   */
  public AppCatalogBuildRequest(
      String catalogId,
      String catalogName,
      Instant generatedAt,
      List<Path> entryDescriptorFiles,
      List<Path> reviewReceiptFiles) {
    this(
        catalogId,
        catalogName,
        generatedAt,
        entryDescriptorFiles,
        reviewReceiptFiles,
        AppCatalogSecurityPolicy.EMPTY,
        null);
  }

  /**
   * Creates a request with review receipt files, root security policy, and no output file.
   *
   * @param catalogId stable catalog identifier used as the catalog namespace
   * @param catalogName human-readable catalog name shown in developer output
   * @param generatedAt deterministic generation timestamp for the catalog metadata
   * @param entryDescriptorFiles descriptor files in the exact order written to the catalog
   * @param reviewReceiptFiles receipt files to embed into matching catalog entries
   * @param securityPolicy catalog-level security advisory and denylist policy
   */
  @SuppressWarnings("unused")
  public AppCatalogBuildRequest(
      String catalogId,
      String catalogName,
      Instant generatedAt,
      List<Path> entryDescriptorFiles,
      List<Path> reviewReceiptFiles,
      AppCatalogSecurityPolicy securityPolicy) {
    this(
        catalogId,
        catalogName,
        generatedAt,
        entryDescriptorFiles,
        reviewReceiptFiles,
        securityPolicy,
        null);
  }

  /**
   * Creates a normalized immutable build request.
   *
   * <p>The constructor normalizes the catalog identifier through the same rules used by parsed
   * catalog files, rejects blank single-line names, copies descriptor paths into an immutable list,
   * and converts all stored paths to absolute normalized form. It intentionally does not check
   * whether the files exist. Missing or malformed descriptor files are reported by {@link
   * AppCatalogWriter} with descriptor-specific context.
   *
   * @param catalogId stable catalog identifier used as the catalog namespace
   * @param catalogName human-readable catalog name shown in developer output
   * @param generatedAt deterministic generation timestamp for the catalog metadata
   * @param entryDescriptorFiles descriptor files in the exact order written to the catalog
   * @param reviewReceiptFiles receipt files to embed into matching catalog entries
   * @param outputFile optional destination for the generated catalog properties bytes
   * @throws AppCatalogException if catalog metadata or descriptor-file inputs are malformed
   */
  @SuppressWarnings("unused")
  public AppCatalogBuildRequest(
      String catalogId,
      String catalogName,
      Instant generatedAt,
      List<Path> entryDescriptorFiles,
      List<Path> reviewReceiptFiles,
      Path outputFile) {
    this(
        catalogId,
        catalogName,
        generatedAt,
        entryDescriptorFiles,
        reviewReceiptFiles,
        AppCatalogSecurityPolicy.EMPTY,
        outputFile);
  }

  /**
   * Creates a normalized immutable build request with root security policy.
   *
   * @param catalogId stable catalog identifier used as the catalog namespace
   * @param catalogName human-readable catalog name shown in developer output
   * @param generatedAt deterministic generation timestamp for the catalog metadata
   * @param entryDescriptorFiles descriptor files in the exact order written to the catalog
   * @param reviewReceiptFiles receipt files to embed into matching catalog entries
   * @param securityPolicy catalog-level security advisory and denylist policy
   * @param outputFile optional destination for the generated catalog properties bytes
   * @throws AppCatalogException if catalog metadata or descriptor-file inputs are malformed
   */
  public AppCatalogBuildRequest(
      String catalogId,
      String catalogName,
      Instant generatedAt,
      List<Path> entryDescriptorFiles,
      List<Path> reviewReceiptFiles,
      AppCatalogSecurityPolicy securityPolicy,
      Path outputFile) {
    this.catalogId = AppCatalog.normalizeCatalogId(catalogId);
    this.catalogName =
        AppCatalogSidecars.requireNonBlankSingleLine(
            catalogName, "catalog.name", AppCatalogSidecars.INVALID_CATALOG_ENTRY);
    this.generatedAt = Objects.requireNonNull(generatedAt, "generatedAt");
    this.entryDescriptorFiles = normalizeDescriptorFiles(entryDescriptorFiles);
    this.reviewReceiptFiles = normalizeReviewReceiptFiles(reviewReceiptFiles);
    this.securityPolicy = Objects.requireNonNull(securityPolicy, "securityPolicy");
    this.outputFile = normalizeOutputFile(outputFile);
  }

  /**
   * Returns the normalized catalog id.
   *
   * @return stable catalog identifier written to {@code catalog.id}
   */
  public String catalogId() {
    return catalogId;
  }

  /**
   * Returns the normalized catalog display name.
   *
   * @return human-readable catalog name written to {@code catalog.name}
   */
  public String catalogName() {
    return catalogName;
  }

  /**
   * Returns the deterministic catalog generation timestamp.
   *
   * @return timestamp written to {@code catalog.generatedAt}
   */
  public Instant generatedAt() {
    return generatedAt;
  }

  /**
   * Returns the normalized descriptor files in catalog entry order.
   *
   * <p>The returned list is a defensive copy of the immutable request state. Mutating the list
   * returned by this accessor is not possible through the collection API, and callers that need a
   * different order must build a new request.
   *
   * @return immutable descriptor paths in the order used for {@code catalog.entries}
   */
  public List<Path> entryDescriptorFiles() {
    return List.copyOf(entryDescriptorFiles);
  }

  /**
   * Returns normalized review receipt files in caller-supplied order.
   *
   * @return immutable receipt paths
   */
  public List<Path> reviewReceiptFiles() {
    return List.copyOf(reviewReceiptFiles);
  }

  /**
   * Returns the catalog-level security policy to write.
   *
   * @return immutable security policy
   */
  public AppCatalogSecurityPolicy securityPolicy() {
    return securityPolicy;
  }

  /**
   * Returns the optional output file for generated catalog properties.
   *
   * <p>An empty value means the writer should return catalog bytes without writing them to disk.
   * When present, the path has already been converted to absolute normalized form.
   *
   * @return optional destination for {@code cryptad-app-catalog.properties}
   */
  public Optional<Path> outputFile() {
    return Optional.ofNullable(outputFile);
  }

  /**
   * Returns a copy of this request that writes the generated catalog to {@code outputFile}.
   *
   * <p>The original request is not modified. The destination path is normalized by the canonical
   * constructor, which keeps CLI code simple and makes the writer's result stable regardless of the
   * current working directory used to create the request.
   *
   * @param outputFile destination for {@code cryptad-app-catalog.properties}
   * @return request with the same catalog metadata and descriptor files plus an output path
   */
  public AppCatalogBuildRequest withOutputFile(Path outputFile) {
    return new AppCatalogBuildRequest(
        catalogId,
        catalogName,
        generatedAt,
        entryDescriptorFiles,
        reviewReceiptFiles,
        securityPolicy,
        outputFile);
  }

  @Override
  public boolean equals(Object object) {
    if (this == object) {
      return true;
    }
    if (!(object instanceof AppCatalogBuildRequest that)) {
      return false;
    }
    return catalogId.equals(that.catalogId)
        && catalogName.equals(that.catalogName)
        && generatedAt.equals(that.generatedAt)
        && entryDescriptorFiles.equals(that.entryDescriptorFiles)
        && reviewReceiptFiles.equals(that.reviewReceiptFiles)
        && securityPolicy.equals(that.securityPolicy)
        && Objects.equals(outputFile, that.outputFile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        catalogId,
        catalogName,
        generatedAt,
        entryDescriptorFiles,
        reviewReceiptFiles,
        securityPolicy,
        outputFile);
  }

  @Override
  public String toString() {
    return "AppCatalogBuildRequest["
        + "catalogId="
        + catalogId
        + ", catalogName="
        + catalogName
        + ", generatedAt="
        + generatedAt
        + ", entryDescriptorFiles="
        + entryDescriptorFiles
        + ", reviewReceiptFiles="
        + reviewReceiptFiles
        + ", securityPolicy="
        + securityPolicy
        + ", outputFile="
        + outputFile()
        + ']';
  }

  private static List<Path> normalizeDescriptorFiles(List<Path> descriptorFiles) {
    Objects.requireNonNull(descriptorFiles, "entryDescriptorFiles");
    if (descriptorFiles.isEmpty()) {
      throw AppCatalogSidecars.invalidEntry(
          "catalog build request must include at least one entry descriptor file");
    }
    List<Path> normalized = new ArrayList<>(descriptorFiles.size());
    for (Path descriptorFile : descriptorFiles) {
      normalized.add(
          Objects.requireNonNull(descriptorFile, "entryDescriptorFile")
              .toAbsolutePath()
              .normalize());
    }
    return List.copyOf(normalized);
  }

  private static List<Path> normalizeReviewReceiptFiles(List<Path> reviewReceiptFiles) {
    Objects.requireNonNull(reviewReceiptFiles, "reviewReceiptFiles");
    List<Path> normalized = new ArrayList<>(reviewReceiptFiles.size());
    for (Path reviewReceiptFile : reviewReceiptFiles) {
      normalized.add(
          Objects.requireNonNull(reviewReceiptFile, "reviewReceiptFiles value")
              .toAbsolutePath()
              .normalize());
    }
    return List.copyOf(normalized);
  }

  private static Path normalizeOutputFile(Path outputFile) {
    return outputFile == null ? null : outputFile.toAbsolutePath().normalize();
  }
}
