package network.crypta.platform.appcatalog;

import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * Input for developer tooling that writes {@code cryptad-app-catalog.properties}.
 *
 * <p>A request supplies catalog-level metadata, a deterministic list of entry descriptor files, and
 * an optional output path. {@link AppCatalogWriter} treats the request as the complete authoring
 * plan for one catalog file: every descriptor is parsed, every referenced bundle artifact is
 * inspected, and the resulting properties are emitted in stable key order. The writer preserves
 * descriptor-file order in {@code catalog.entries}; callers that collect files from a glob should
 * sort that list before constructing the request.
 *
 * <p>The generated timestamp is an explicit input rather than an implicit clock read so catalog
 * authoring can be reproducible in tests, release jobs, and local CLI workflows. Paths are
 * normalized during construction, but the request does not read descriptor contents or bundle
 * artifacts. That validation remains in the writer so callers can build, inspect, and pass around a
 * request without performing file-system work.
 *
 * @param catalogId stable catalog identifier written to {@code catalog.id} after normalization
 * @param catalogName human-readable catalog name written to {@code catalog.name}
 * @param generatedAt deterministic generation timestamp written to {@code catalog.generatedAt}
 * @param entryDescriptorFiles one or more descriptor files in exact output entry order
 * @param outputFile optional file that should receive the catalog properties bytes
 */
public record AppCatalogBuildRequest(
    String catalogId,
    String catalogName,
    Instant generatedAt,
    List<Path> entryDescriptorFiles,
    Optional<Path> outputFile) {
  /**
   * Creates a request that returns bytes without writing a catalog file.
   *
   * <p>This overload is useful for tests and command-line flows that want to inspect or sign the
   * generated bytes before deciding where to place them. It delegates to the canonical constructor,
   * so catalog identifiers, names, timestamps, and descriptor paths are validated in the same way
   * as requests that include an output file.
   *
   * @param catalogId stable catalog identifier used as the catalog namespace
   * @param catalogName human-readable catalog name shown in developer output
   * @param generatedAt deterministic generation timestamp for the catalog metadata
   * @param entryDescriptorFiles descriptor files in the exact order written to the catalog
   */
  public AppCatalogBuildRequest(
      String catalogId, String catalogName, Instant generatedAt, List<Path> entryDescriptorFiles) {
    this(catalogId, catalogName, generatedAt, entryDescriptorFiles, Optional.empty());
  }

  /**
   * Creates a normalized immutable build request.
   *
   * <p>The constructor normalizes the catalog identifier through the same rules used by parsed
   * catalog files, rejects blank single-line names, copies descriptor paths into an immutable list,
   * and converts all stored paths to absolute normalized form. It intentionally does not check
   * whether the files exist. Missing or malformed descriptor files are reported by {@link
   * AppCatalogWriter} with descriptor-specific context.
   *
   * @param catalogId stable catalog identifier used as the catalog namespace
   * @param catalogName human-readable catalog name shown in developer output
   * @param generatedAt deterministic generation timestamp for the catalog metadata
   * @param entryDescriptorFiles descriptor files in the exact order written to the catalog
   * @param outputFile optional destination for the generated catalog properties bytes
   * @throws AppCatalogException if catalog metadata or descriptor-file inputs are malformed
   */
  public AppCatalogBuildRequest {
    catalogId = AppCatalog.normalizeCatalogId(catalogId);
    catalogName =
        AppCatalogSidecars.requireNonBlankSingleLine(
            catalogName, "catalog.name", AppCatalogSidecars.INVALID_CATALOG_ENTRY);
    Objects.requireNonNull(generatedAt, "generatedAt");
    entryDescriptorFiles = normalizeDescriptorFiles(entryDescriptorFiles);
    outputFile =
        Objects.requireNonNull(outputFile, "outputFile")
            .map(
                path ->
                    Objects.requireNonNull(path, "outputFile path").toAbsolutePath().normalize());
  }

  /**
   * Returns the normalized descriptor files in catalog entry order.
   *
   * <p>The returned list is a defensive copy of the immutable request state. Mutating the list
   * returned by this accessor is not possible through the collection API, and callers that need a
   * different order must build a new request.
   *
   * @return immutable descriptor paths in the order used for {@code catalog.entries}
   */
  @Override
  public List<Path> entryDescriptorFiles() {
    return List.copyOf(entryDescriptorFiles);
  }

  /**
   * Returns a copy of this request that writes the generated catalog to {@code outputFile}.
   *
   * <p>The original request is not modified. The destination path is normalized by the canonical
   * constructor, which keeps CLI code simple and makes the writer's result stable regardless of the
   * current working directory used to create the request.
   *
   * @param outputFile destination for {@code cryptad-app-catalog.properties}
   * @return request with the same catalog metadata and descriptor files plus an output path
   */
  public AppCatalogBuildRequest withOutputFile(Path outputFile) {
    return new AppCatalogBuildRequest(
        catalogId, catalogName, generatedAt, entryDescriptorFiles, Optional.of(outputFile));
  }

  private static List<Path> normalizeDescriptorFiles(List<Path> descriptorFiles) {
    Objects.requireNonNull(descriptorFiles, "entryDescriptorFiles");
    if (descriptorFiles.isEmpty()) {
      throw AppCatalogSidecars.invalidEntry(
          "catalog build request must include at least one entry descriptor file");
    }
    List<Path> normalized = new ArrayList<>(descriptorFiles.size());
    for (Path descriptorFile : descriptorFiles) {
      normalized.add(
          Objects.requireNonNull(descriptorFile, "entryDescriptorFile")
              .toAbsolutePath()
              .normalize());
    }
    return List.copyOf(normalized);
  }
}
