package network.crypta.runtime.diagnostics.threads;

/**
 * Immutable, value-based view of a single JVM thread at a particular sampling moment.
 *
 * <p>This record is a lightweight data carrier produced by the thread diagnostics subsystem. Each
 * instance represents the attributes and recent CPU usage of one thread captured during a sampling
 * pass. Values are intentionally simple, serializable-friendly primitives and strings so they can
 * be sorted, displayed and transmitted without additional context. The object is immutable and
 * thread-safe; callers may freely retain references across application components without
 * synchronization.
 *
 * <p>Typical usage is to obtain a {@code java.util.List<NodeThreadInfo>} from a snapshot provider
 * and then filter or order it according to the desired criteria (for example, highest CPU usage
 * during the most recent interval). Entries originating from pooled executors expose a stable
 * <em>job id</em> which allows correlating work across sampling passes even when the underlying
 * worker thread is reused by the pool. For non-pooled threads the job id equals the operating
 * system thread id.
 *
 * <ul>
 *   <li><strong>Immutability</strong>: all components are final; instances are safe for concurrent
 *       sharing.
 *   <li><strong>Scope</strong>: describes a point-in-time measurement; values do not update after
 *       creation.
 *   <li><strong>CPU time</strong>: {@code cpuTime} is a delta for the last sampling interval and is
 *       expressed in nanoseconds, not a lifetime total.
 * </ul>
 *
 * @param id the JVM/OS thread identifier at the time of sampling; typically unique within the
 *     process; used for display and as a fallback identifier when no separate job id exists
 * @param jobId identifier of the unit of work associated with the thread; for pooled workers this
 *     is the current job id; for regular threads this value equals {@code id}; may be used to
 *     correlate entries across snapshots
 * @param cpuTime CPU usage delta in nanoseconds measured for the immediately preceding sampling
 *     period; this value is non-accumulating and may be zero when the thread consumed no CPU during
 *     the interval
 * @param name the thread name captured during sampling; may be {@code null} when a name is not
 *     available or has not been assigned by the thread creator
 * @param prio the Java thread priority value at sampling time; usually within {@code 1..10}; the
 *     effective scheduling behavior may still depend on the host platform
 * @param groupName the name of the thread group to which the thread belongs; may be {@code null}
 *     when the group is unavailable or has no name
 * @param state the thread state as a human-readable string (for example, {@code RUNNABLE} or {@code
 *     TIMED_WAITING}); may be {@code null} if not determined
 */
public record NodeThreadInfo(
    long id, long jobId, long cpuTime, String name, int prio, String groupName, String state) {

  // Canonical constructor is generated by the record; keep JavaBean-style accessors for
  // compatibility

  /**
   * Returns the operating system thread identifier captured for this entry.
   *
   * <p>The identifier reflects the thread as observed at sampling time. For most JVMs this value is
   * stable over the lifetime of the thread. Use {@link #getJobId()} to group work items when pooled
   * executors reuse worker threads.
   *
   * @return the thread id value as recorded at sampling time; callers must not assume global
   *     stability beyond the lifetime of the corresponding thread
   */
  public long getId() {
    return id();
  }

  /**
   * Returns the job identifier associated with this thread at sampling time.
   *
   * <p>For pooled worker threads this corresponds to the current job or task id, enabling
   * correlation across multiple sampling passes even if the physical thread is reused. For other
   * threads the job id equals the thread id.
   *
   * @return a job id suitable for correlating activity across snapshots; equals {@link #getId()}
   *     for non-pooled threads
   */
  public long getJobId() {
    return jobId();
  }

  /**
   * Returns the thread name captured during the sampling pass.
   *
   * <p>The name is read from the underlying {@code Thread} at the moment of sampling. It may be
   * {@code null} when no name was set or if the name could not be obtained.
   *
   * @return the thread name at sampling time, or {@code null} if unavailable
   */
  public String getName() {
    return name();
  }

  /**
   * Returns the Java thread priority observed at sampling time.
   *
   * <p>Java priorities commonly range from {@code 1} (lowest) to {@code 10} (highest). The exact
   * scheduling effect is platform-dependent and may not map linearly to operating system
   * priorities.
   *
   * @return the priority value as an integer, typically within {@code 1..10}
   */
  public int getPrio() {
    return prio();
  }

  /**
   * Returns the name of the thread group that owned the thread when sampled.
   *
   * <p>Some environments de-emphasize thread groups; in such cases this value may be {@code null}
   * or an empty string depending on the runtime.
   *
   * @return the group name string, or {@code null} when unavailable
   */
  public String getGroupName() {
    return groupName();
  }

  /**
   * Returns the string representation of the thread state at sampling time.
   *
   * <p>Values typically correspond to {@code Thread.State} names, such as {@code RUNNABLE}, {@code
   * TIMED_WAITING} or {@code BLOCKED}. The value may be {@code null} if the state could not be
   * determined reliably during sampling.
   *
   * @return a non-empty state name when known, otherwise {@code null}
   */
  public String getState() {
    return state();
  }

  /**
   * Returns the CPU time delta measured for the thread during the last sampling interval.
   *
   * <p>The value is expressed in nanoseconds. It represents the difference between the CPU time at
   * the current and previous samples, not a lifetime cumulative sum. When CPU accounting is not
   * supported by the platform, this value may be zero.
   *
   * @return a non-negative number of nanoseconds representing recent CPU consumption
   */
  public long getCpuTime() {
    return cpuTime();
  }
}
