package network.crypta.clients.http;

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import network.crypta.client.HighLevelSimpleClient;
import network.crypta.runtime.spi.TransferAccessPort;
import network.crypta.support.HTMLNode;

/**
 * Local file browser for the content filter toadlet.
 *
 * <p>This toadlet exposes a file picker that feeds the content filter UI. Operators navigate
 * allowed directories, choose a file, and return to the filter form without retyping paths. It
 * honors the same access rules as {@link ContentFilterToadlet} and never writes to filesystem
 * paths.
 *
 * <p>Use this class when an authenticated browse endpoint must align with filtering. The path is
 * configurable via the {@code network.crypta.clients.http.LocalFileFilterToadlet.path} system
 * property and normalized with leading and trailing slashes so links remain absolute. The
 * surrounding HTTP container supplies authentication and advanced-mode gating; this instance keeps
 * no mutable request state and is stateless under servlet-style dispatch.
 *
 * <ul>
 *   <li>Responsibilities: render selection controls, persist filter parameters across round-trips,
 *       and delegate upload validation to the core.
 *   <li>Notable behaviors: directory browsing is disabled to avoid recursive selection; only files
 *       under {@link #allowedDir(File)} are selectable.
 * </ul>
 *
 * @see ContentFilterToadlet
 */
public class LocalFileFilterToadlet extends LocalFileBrowserToadlet {
  private static final String PATH_PROPERTY =
      "network.crypta.clients.http.LocalFileFilterToadlet.path";
  private static final String DEFAULT_PATH_SEGMENT = "filter-browse";
  private static final String PATH_DELIMITER = "/";
  private static final String DEFAULT_PATH =
      String.join(PATH_DELIMITER, "", DEFAULT_PATH_SEGMENT, "");

  /**
   * Resolved endpoint path used to expose the local filter browser. The value is computed once at
   * class load time from the system property or default segment and retains leading/trailing
   * slashes so it can be registered directly with the HTTP container and reused in generated links.
   */
  public static final String BROWSE_PATH = resolvePath();

  /**
   * Target endpoint for submitted selections, aligned with the main content filter toadlet path.
   * The value always includes leading and trailing slashes, so hyperlinks generated by this class
   * resolve as absolute URLs rather than relative paths. Callers should not mutate or cache a
   * divergent copy; use this constant to keep navigation coherent with {@link
   * ContentFilterToadlet}.
   */
  public static final String POST_TO = LegacyContentFilterSupport.CONTENT_FILTER_PATH;

  /**
   * Creates a stateless browser toadlet that reuses the provided client core and HTTP helper.
   *
   * <p>The constructor does not perform I/O or container registration; callers are expected to
   * mount the instance at {@link #BROWSE_PATH} after ensuring the node is in advanced mode and the
   * requesting user has sufficient privileges. Both collaborators must be non-null and remain valid
   * for the lifetime of the toadlet; this class does not own their lifecycle.
   *
   * @param transferAccess transfer-access runtime port used for upload permission checks; must not
   *     be {@code null} and should stay alive for as long as requests may be served.
   * @param highLevelSimpleClient HTTP client abstraction used by the superclass to render and link
   *     HTML responses; must not be {@code null}.
   */
  public LocalFileFilterToadlet(
      TransferAccessPort transferAccess, HighLevelSimpleClient highLevelSimpleClient) {
    super(transferAccess, highLevelSimpleClient);
  }

  /**
   * Returns the normalized browse endpoint where this toadlet expects to be mounted. Callers use
   * the value when registering the toadlet with the container and when generating absolute links in
   * rendered HTML. Because the path is normalized with leading and trailing slashes at startup, the
   * returned string can be concatenated directly with relative resource names without risking
   * malformed URLs or path traversal ambiguities.
   *
   * @return absolute path beginning and ending with {@code /}; suitable for registration, link
   *     construction, and consistent with {@link #BROWSE_PATH}.
   */
  @Override
  public String path() {
    return BROWSE_PATH;
  }

  /**
   * Reports the form submission target used when a file is selected. The value mirrors the content
   * filter toadlet's endpoint so hand-offs from the browser page to the filter processor remain
   * coherent. The method performs no computation at call time and simply relays the normalized
   * constant, allowing repeated invocations without overhead.
   *
   * @return absolute path of the content filter submission handler; never {@code null} or empty and
   *     always normalized with leading/trailing slashes.
   */
  @Override
  protected String postTo() {
    return POST_TO;
  }

  /**
   * Checks whether uploads from the given directory are permitted for the current node. The method
   * delegates to {@link TransferAccessPort#allowUploadFrom(File)} so the decision reflects the
   * node's runtime security policy, including sandboxing or user configuration. Null inputs are
   * forwarded directly, allowing the runtime policy to apply its own null-handling rules without
   * duplicating logic here.
   *
   * @param path directory candidate chosen by the user; may be {@code null} when selection failed
   *     or was cleared.
   * @return {@code true} when the core allows uploads from the directory; otherwise {@code false},
   *     enabling the UI to block navigation before rendering links.
   */
  @Override
  protected boolean allowedDir(File path) {
    return transferAccess.allowUploadFrom(path);
  }

  /**
   * Renders the Submit button and persists the selected absolute file path. The method injects both
   * a visible submission control and a hidden filename field, so the following POST to the content
   * filter includes the user's selection without further interaction. State unrelated to the file
   * path is preserved via the provided persistence node, which is appended unchanged to avoid
   * mutating caller-owned structures.
   *
   * @param node HTML container to append form controls into; must not be {@code null} because the
   *     method writes directly into it.
   * @param absolutePath canonical absolute path of the selected file; must not be {@code null} or
   *     empty or the resulting form will point at an invalid target.
   * @param persistence hidden fields representing filter state that should survive the round-trip;
   *     must not be {@code null} and should already contain validated keys.
   */
  @Override
  protected void createSelectFileButton(HTMLNode node, String absolutePath, HTMLNode persistence) {
    node.addChild(
        "input",
        new String[] {"type", "name", "value"},
        new String[] {"submit", SELECT_FILE, LegacyContentFilterSupport.l10n("selectFile")});
    node.addChild(
        "input",
        new String[] {"type", "name", "value"},
        new String[] {"hidden", filenameField(), absolutePath});
    node.addChild(persistence);
  }

  /**
   * Intentionally omits directory selection controls because the content filter expects individual
   * files. Providing an empty implementation keeps the UI from exposing a directory picker and
   * prevents callers from submitting paths that downstream components cannot process. The
   * surrounding form still renders normally; only file-level actions are available.
   *
   * @param node HTML container that would otherwise host a directory button; unused but never
   *     {@code null}.
   * @param absolutePath placeholder for directory paths; ignored to avoid unsupported inputs.
   * @param persistence hidden state holder; forwarded untouched to preserve request context.
   */
  @Override
  protected void createSelectDirectoryButton(
      HTMLNode node, String absolutePath, HTMLNode persistence) {
    // Directory selection is intentionally disabled for the content filter flow to avoid
    // accepting directory inputs where only files are valid.
  }

  /**
   * Copies filter-related fields from the incoming request so the browser form preserves them. Only
   * recognized keys are retained, allowing the UI to maintain user selections while discarding
   * unrelated parameters that may have been injected by intermediaries or stale forms. The returned
   * map is a fresh {@link HashMap}, enabling callers to mutate or extend it without affecting
   * request-scoped data.
   *
   * @param set request parameter map, typically originating from {@link
   *     network.crypta.support.api.HTTPRequest} parsing; may be empty but not {@code null}.
   * @return map containing only parameters relevant to the filter form; never {@code null} but may
   *     be empty when no known keys are present.
   */
  @Override
  protected Map<String, String> persistenceFields(Map<String, String> set) {
    Map<String, String> fieldPairs = new HashMap<>();
    String element = set.get("filter-operation");
    if (element != null) {
      fieldPairs.put("filter-operation", element);
    }
    element = set.get("result-handling");
    if (element != null) {
      fieldPairs.put("result-handling", element);
    }
    element = set.get("mime-type");
    if (element != null) {
      fieldPairs.put("mime-type", element);
    }
    return fieldPairs;
  }

  /**
   * Provides the initial directory shown when the local browser opens. The method delegates to the
   * superclass helper {@code defaultUploadDir()}, preserving consistency with other upload-aware
   * toadlets so users land in a predictable location. Implementations may tailor the helper to the
   * host platform, but this class treats the returned path as authoritative and does not normalize
   * or validate it further.
   *
   * @return absolute path for the starting directory, typically the node's default upload folder;
   *     never {@code null} under normal configuration.
   */
  @Override
  protected String startingDir() {
    return defaultUploadDir();
  }

  private static String resolvePath() {
    String configuredPath = System.getProperty(PATH_PROPERTY);
    String path =
        (configuredPath == null || configuredPath.isBlank()) ? DEFAULT_PATH : configuredPath.trim();

    if (!path.startsWith(PATH_DELIMITER)) {
      path = PATH_DELIMITER + path;
    }
    if (!path.endsWith(PATH_DELIMITER)) {
      path = path + PATH_DELIMITER;
    }
    return path;
  }
}
