package network.crypta.platform.api.content.subscriptions;

import java.io.IOException;
import java.util.List;
import java.util.Optional;

/**
 * Durable metadata store for app-owned content subscriptions.
 *
 * <p>Stores persist only safe subscription metadata and fetch-result summaries. Implementations
 * must not derive file names from source URIs and must not expose backing paths through returned
 * state. The durable identity is the pair of normalized app id and platform-generated subscription
 * id; the public source URI is data inside the record, never part of the storage path.
 *
 * <p>The interface is intentionally small so it remains a subscription metadata store rather than a
 * general app database. Implementations may be file-backed or in-memory, but they should return
 * deterministic orderings, tolerate absent records, and surface real I/O failures to the service so
 * API routes can return stable platform errors.
 */
public interface ContentSubscriptionStore {
  /**
   * Lists subscriptions owned by one app.
   *
   * <p>The result must not include subscriptions for any other app id. Missing app directories or
   * empty app state should return an empty list, not an error.
   *
   * @param appId normalized or normalizable app id used as the owner partition
   * @return subscriptions owned by the app in deterministic order
   * @throws IOException if the backing store cannot be read
   */
  List<ContentSubscription> listForApp(String appId) throws IOException;

  /**
   * Lists all subscriptions across all apps for scheduler due checks.
   *
   * <p>The scheduler uses this method to find due work and enforce global pressure limits. Corrupt
   * or invalid records should not leak partial path details through returned state; file-backed
   * implementations may skip records they cannot safely reconstruct.
   *
   * @return all valid subscriptions in deterministic order
   * @throws IOException if the backing store cannot be read
   */
  List<ContentSubscription> listAll() throws IOException;

  /**
   * Reads one subscription owned by an app.
   *
   * <p>The lookup must be scoped by both app id and subscription id. A record owned by another app
   * should be indistinguishable from an absent record to callers of the service.
   *
   * @param appId normalized or normalizable owner app id
   * @param subscriptionId safe subscription id generated by the platform
   * @return stored subscription, or empty when absent or invalid
   * @throws IOException if the backing store cannot be read
   */
  Optional<ContentSubscription> read(String appId, String subscriptionId) throws IOException;

  /**
   * Writes one subscription metadata record.
   *
   * <p>The implementation should persist atomically enough that a restart either sees the old valid
   * record or the new valid record. It must persist metadata only and must not store fetched
   * content bytes beside the record.
   *
   * @param subscription path-free subscription metadata to persist
   * @throws IOException if the backing store cannot be written
   */
  void write(ContentSubscription subscription) throws IOException;

  /**
   * Deletes one subscription owned by an app.
   *
   * <p>Deleting a missing record should be a harmless no-op reported as {@code false}. The method
   * must scope deletion to the owner app id and subscription id and must not inspect the source
   * URI.
   *
   * @param appId normalized or normalizable owner app id
   * @param subscriptionId safe subscription id generated by the platform
   * @return {@code true} when a durable record was removed
   * @throws IOException if the backing store cannot delete the record
   */
  boolean delete(String appId, String subscriptionId) throws IOException;

  /**
   * Deletes all subscriptions owned by one app.
   *
   * <p>This is used by app lifecycle cleanup after uninstall. Implementations must scope the
   * deletion to the normalized app id and must not inspect or derive paths from subscription source
   * URIs. Deleting a missing app partition should be harmless.
   *
   * @param appId normalized or normalizable owner app id
   * @throws IOException if the backing store cannot delete the app's records
   */
  void deleteAllForApp(String appId) throws IOException;
}
