package network.crypta.platform.api.content.subscriptions;

import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.regex.Pattern;
import network.crypta.platform.api.PlatformApiException;
import network.crypta.platform.apphost.manifest.AppManifest;

/**
 * Durable metadata for one app-owned content subscription.
 *
 * <p>A subscription belongs to exactly one app principal and represents a bounded background poll
 * of a public USK source. The service and scheduler treat this record as the durable state machine:
 * API calls create, pause, resume, refresh, or delete it, while scheduler polls update only timing,
 * status, digest, edition, and other safe metadata. Callers should build new states through the
 * helper methods on this record so validation, redaction, and message bounds stay consistent across
 * file-backed and in-memory stores.
 *
 * <p>The record stores subscription control data and fetch result metadata only. It never stores
 * fetched bytes, raw request bodies, browser-session tokens, app process tokens, queue HTML,
 * private insert URIs, private keys, local paths, or daemon exception messages. The app-facing
 * summary still includes the owning app id and the app-supplied public source URI, because those
 * are already visible to the app that owns the subscription.
 *
 * @param subscriptionId safe path segment generated by the platform for this subscription
 * @param appId normalized app id that owns and may access the subscription
 * @param label short app-facing label shown in summaries and reference UI
 * @param sourceUri canonical public USK source string owned by the app
 * @param normalizedSourceKind stable source kind label, currently always {@code USK}
 * @param runtimeFetchUri normalized URI passed to the detached content fetch port
 * @param enabled whether scheduler polls are allowed for this record
 * @param status current lifecycle or last scheduler result for the subscription
 * @param policy bounded polling, byte, and timeout policy for fetches
 * @param createdAt instant when the subscription metadata was first created
 * @param updatedAt instant when durable subscription metadata last changed
 * @param lastCheckAt instant when the scheduler last attempted or skipped a poll
 * @param nextCheckAt instant when the scheduler may next consider the record due
 * @param lastSuccessAt instant when a fetch last completed successfully
 * @param lastFailureAt instant when a fetch or pressure skip last failed visibly
 * @param failureCount consecutive failure or pressure-skip count used for backoff
 * @param lastErrorCode stable sanitized error code for app summaries
 * @param lastSeenResolvedUri sanitized resolved USK URI reported by the runtime
 * @param lastSeenEdition resolved USK edition number extracted from the runtime URI
 * @param contentSha256 SHA-256 digest of the last fetched content bytes
 * @param bytesLength byte length of the last successful bounded fetch result
 * @param updateCount number of distinct content or edition updates observed
 * @param message bounded single-line status text safe for app-facing summaries
 * @see ContentSubscriptionService
 * @see ContentSubscriptionStore
 */
public record ContentSubscription(
    String subscriptionId,
    String appId,
    String label,
    String sourceUri,
    String normalizedSourceKind,
    String runtimeFetchUri,
    boolean enabled,
    ContentSubscriptionStatus status,
    ContentSubscriptionPolicy policy,
    Instant createdAt,
    Instant updatedAt,
    Instant lastCheckAt,
    Instant nextCheckAt,
    Instant lastSuccessAt,
    Instant lastFailureAt,
    int failureCount,
    String lastErrorCode,
    String lastSeenResolvedUri,
    Long lastSeenEdition,
    String contentSha256,
    Long bytesLength,
    int updateCount,
    String message) {
  static final String SOURCE_KIND_USK = "USK";
  static final int MAX_LABEL_LENGTH = 80;
  static final int MAX_OPTIONAL_TEXT_LENGTH = 180;
  private static final Pattern SAFE_ID = Pattern.compile("[a-z0-9](?:[a-z0-9._-]{0,190}[a-z0-9])?");
  private static final Pattern SAFE_ERROR_CODE =
      Pattern.compile("[a-z0-9](?:[a-z0-9._-]*[a-z0-9])?");
  private static final Pattern SHA_256 = Pattern.compile("[a-f0-9]{64}");

  /**
   * Creates validated subscription metadata.
   *
   * <p>The compact constructor normalizes the app id, source URI, runtime fetch URI, safe error
   * code, optional resolved URI, digest, and message. It also rejects negative counters and
   * lengths. The checks are intentionally repeated here instead of relying on callers, because
   * records can be reconstructed from durable files as well as from freshly parsed API requests.
   *
   * @throws IllegalArgumentException if counters, byte lengths, or digests are invalid
   * @throws PlatformApiException if app-visible identifiers or labels are invalid
   */
  public ContentSubscription {
    subscriptionId = requireSubscriptionId(subscriptionId);
    appId = AppManifest.normalizeAppId(appId);
    label = requireLabel(label);
    sourceUri = ContentSubscriptionSource.normalizeSourceUri(sourceUri).sourceUri();
    ContentSubscriptionSource source = ContentSubscriptionSource.normalizeSourceUri(sourceUri);
    runtimeFetchUri = source.runtimeFetchUri();
    normalizedSourceKind = SOURCE_KIND_USK;
    Objects.requireNonNull(status, "status");
    Objects.requireNonNull(policy, "policy");
    Objects.requireNonNull(createdAt, "createdAt");
    Objects.requireNonNull(updatedAt, "updatedAt");
    if (failureCount < 0) {
      throw new IllegalArgumentException("failureCount must be >= 0");
    }
    if (updateCount < 0) {
      throw new IllegalArgumentException("updateCount must be >= 0");
    }
    lastErrorCode = optionalSafeCode(lastErrorCode);
    lastSeenResolvedUri = ContentSubscriptionSource.sanitizeResolvedUri(lastSeenResolvedUri);
    contentSha256 = optionalSha256(contentSha256);
    if (bytesLength != null && bytesLength < 0L) {
      throw new IllegalArgumentException("bytesLength must be >= 0");
    }
    message = optionalSingleLine(message);
  }

  /**
   * Creates a new scheduled subscription.
   *
   * <p>The returned record has no fetch result metadata yet. It is enabled, starts in the scheduled
   * state, and receives the supplied first due time without running a network fetch synchronously.
   * The scheduler performs the first detached fetch later, subject to app capability checks, queue
   * pressure handling, per-tick limits, and the policy stored on the record.
   *
   * @param subscriptionId generated safe id used as the durable record name
   * @param appId owner app id used for API scoping and store partitioning
   * @param label display label supplied by the owning app
   * @param sourceUri app-owned public USK source URI to poll
   * @param policy bounded fetch policy applied to every scheduler poll
   * @param now creation time stored as both created and updated time
   * @param nextCheckAt first due time considered by deterministic scheduler ticks
   * @return new enabled subscription metadata ready for storage
   */
  public static ContentSubscription create(
      String subscriptionId,
      String appId,
      String label,
      String sourceUri,
      ContentSubscriptionPolicy policy,
      Instant now,
      Instant nextCheckAt) {
    ContentSubscriptionSource source = ContentSubscriptionSource.normalizeSourceUri(sourceUri);
    return new ContentSubscription(
        subscriptionId,
        appId,
        label,
        source.sourceUri(),
        SOURCE_KIND_USK,
        source.runtimeFetchUri(),
        true,
        ContentSubscriptionStatus.SCHEDULED,
        policy,
        now,
        now,
        null,
        nextCheckAt,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        0,
        "Waiting for the next subscription poll.");
  }

  /**
   * Returns an app-facing path-free summary map.
   *
   * <p>The summary is suitable for JSON serialization by platform API handlers. It preserves stable
   * insertion order, includes only safe subscription metadata, and deliberately omits the runtime
   * fetch URI because that value exists only to call the content fetch port. Timestamps are
   * rendered with {@link Instant#toString()} and absent fields are represented as {@code null}.
   *
   * @return deterministic JSON-compatible subscription summary with no raw content or local paths
   */
  public Map<String, Object> toSummary() {
    LinkedHashMap<String, Object> json = LinkedHashMap.newLinkedHashMap(23);
    json.put("subscriptionId", subscriptionId);
    json.put("appId", appId);
    json.put("label", label);
    json.put("sourceUri", sourceUri);
    json.put("normalizedSourceKind", normalizedSourceKind);
    json.put("enabled", enabled);
    json.put("paused", status == ContentSubscriptionStatus.PAUSED || !enabled);
    json.put("status", status.jsonValue());
    json.put("pollIntervalSeconds", policy.pollIntervalSeconds());
    json.put("maxBytes", policy.maxBytes());
    json.put("timeoutMillis", policy.timeoutMillis());
    json.put("lastCheckAt", timestamp(lastCheckAt));
    json.put("nextCheckAt", timestamp(nextCheckAt));
    json.put("lastSuccessAt", timestamp(lastSuccessAt));
    json.put("lastFailureAt", timestamp(lastFailureAt));
    json.put("failureCount", failureCount);
    json.put("lastErrorCode", lastErrorCode);
    json.put("lastSeenResolvedUri", lastSeenResolvedUri);
    json.put("lastSeenEdition", lastSeenEdition);
    json.put("contentSha256", contentSha256);
    json.put("bytesLength", bytesLength);
    json.put("updateCount", updateCount);
    json.put("message", message);
    return json;
  }

  ContentSubscription withRunning(Instant now) {
    return copy(
        enabled,
        ContentSubscriptionStatus.RUNNING,
        now,
        now,
        nextCheckAt,
        lastSuccessAt,
        lastFailureAt,
        failureCount,
        lastErrorCode,
        lastSeenResolvedUri,
        lastSeenEdition,
        contentSha256,
        bytesLength,
        updateCount,
        "Subscription poll is running.");
  }

  ContentSubscription withPaused(Instant now) {
    return copy(
        false,
        ContentSubscriptionStatus.PAUSED,
        now,
        lastCheckAt,
        null,
        lastSuccessAt,
        lastFailureAt,
        failureCount,
        lastErrorCode,
        lastSeenResolvedUri,
        lastSeenEdition,
        contentSha256,
        bytesLength,
        updateCount,
        "Subscription is paused.");
  }

  ContentSubscription withResumed(Instant now) {
    return copy(
        true,
        ContentSubscriptionStatus.SCHEDULED,
        now,
        lastCheckAt,
        now,
        lastSuccessAt,
        lastFailureAt,
        failureCount,
        lastErrorCode,
        lastSeenResolvedUri,
        lastSeenEdition,
        contentSha256,
        bytesLength,
        updateCount,
        "Subscription is scheduled.");
  }

  ContentSubscription withDeleted(Instant now) {
    return copy(
        false,
        ContentSubscriptionStatus.DELETED,
        now,
        lastCheckAt,
        null,
        lastSuccessAt,
        lastFailureAt,
        failureCount,
        lastErrorCode,
        lastSeenResolvedUri,
        lastSeenEdition,
        contentSha256,
        bytesLength,
        updateCount,
        "Subscription was deleted.");
  }

  ContentSubscription withSuccess(
      Instant now,
      Instant next,
      String resolvedUri,
      Long edition,
      String digest,
      long length,
      boolean changed) {
    return copy(
        enabled,
        ContentSubscriptionStatus.SUCCESS,
        now,
        now,
        next,
        now,
        null,
        0,
        null,
        resolvedUri,
        edition,
        digest,
        length,
        changed ? updateCount + 1 : updateCount,
        changed ? "Subscription content metadata changed." : "Subscription content is unchanged.");
  }

  ContentSubscription withFailure(Instant now, Instant next, String errorCode, String safeMessage) {
    return copy(
        enabled,
        ContentSubscriptionStatus.BACKOFF,
        now,
        now,
        next,
        lastSuccessAt,
        now,
        failureCount + 1,
        errorCode,
        lastSeenResolvedUri,
        lastSeenEdition,
        contentSha256,
        bytesLength,
        updateCount,
        safeMessage);
  }

  ContentSubscription withSkipped(
      Instant now,
      Instant next,
      ContentSubscriptionStatus skippedStatus,
      String errorCode,
      String safeMessage) {
    return copy(
        enabled,
        skippedStatus,
        now,
        now,
        next,
        lastSuccessAt,
        now,
        failureCount + 1,
        errorCode,
        lastSeenResolvedUri,
        lastSeenEdition,
        contentSha256,
        bytesLength,
        updateCount,
        safeMessage);
  }

  boolean shouldSkipPollAt(Instant now) {
    return !enabled
        || status == ContentSubscriptionStatus.PAUSED
        || (nextCheckAt != null && nextCheckAt.isAfter(now));
  }

  private ContentSubscription copy(
      boolean newEnabled,
      ContentSubscriptionStatus newStatus,
      Instant newUpdatedAt,
      Instant newLastCheckAt,
      Instant newNextCheckAt,
      Instant newLastSuccessAt,
      Instant newLastFailureAt,
      int newFailureCount,
      String newLastErrorCode,
      String newResolvedUri,
      Long newEdition,
      String newContentSha256,
      Long newBytesLength,
      int newUpdateCount,
      String newMessage) {
    return new ContentSubscription(
        subscriptionId,
        appId,
        label,
        sourceUri,
        normalizedSourceKind,
        runtimeFetchUri,
        newEnabled,
        newStatus,
        policy,
        createdAt,
        newUpdatedAt,
        newLastCheckAt,
        newNextCheckAt,
        newLastSuccessAt,
        newLastFailureAt,
        newFailureCount,
        newLastErrorCode,
        newResolvedUri,
        newEdition,
        newContentSha256,
        newBytesLength,
        newUpdateCount,
        newMessage);
  }

  static String requireSubscriptionId(String value) {
    String normalized =
        Objects.requireNonNull(value, "subscriptionId").trim().toLowerCase(java.util.Locale.ROOT);
    if (!SAFE_ID.matcher(normalized).matches()) {
      throw new PlatformApiException(
          400, "invalid_path_parameter", "subscriptionId must be one safe path segment.");
    }
    return normalized;
  }

  static String requireLabel(String value) {
    String normalized = Objects.requireNonNull(value, "label").trim();
    if (normalized.isEmpty()) {
      throw new PlatformApiException(
          400, "invalid_query_parameter", "Query parameter 'label' must not be blank.");
    }
    if (normalized.length() > MAX_LABEL_LENGTH || hasLineBreak(normalized)) {
      throw new PlatformApiException(
          400,
          "invalid_query_parameter",
          "Query parameter 'label' must be a short single-line value.");
    }
    return normalized;
  }

  static String optionalSafeCode(String value) {
    if (value == null || value.isBlank()) {
      return null;
    }
    String normalized = value.trim().toLowerCase(java.util.Locale.ROOT);
    return SAFE_ERROR_CODE.matcher(normalized).matches() ? normalized : "subscription_failed";
  }

  static String optionalSingleLine(String value) {
    if (value == null || value.isBlank()) {
      return null;
    }
    String normalized = value.trim();
    if (hasLineBreak(normalized)) {
      return null;
    }
    return normalized.length() > MAX_OPTIONAL_TEXT_LENGTH
        ? normalized.substring(0, MAX_OPTIONAL_TEXT_LENGTH)
        : normalized;
  }

  private static String optionalSha256(String value) {
    if (value == null || value.isBlank()) {
      return null;
    }
    String normalized = value.trim().toLowerCase(java.util.Locale.ROOT);
    if (!SHA_256.matcher(normalized).matches()) {
      throw new IllegalArgumentException("contentSha256 must be a SHA-256 hex digest");
    }
    return normalized;
  }

  private static String timestamp(Instant instant) {
    return instant == null ? null : instant.toString();
  }

  private static boolean hasLineBreak(String value) {
    return value.indexOf('\n') >= 0 || value.indexOf('\r') >= 0 || value.indexOf('\u0000') >= 0;
  }
}
