package network.crypta.client;

import network.crypta.client.InsertException.InsertExceptionMode;
import network.crypta.client.async.BaseClientPutter;
import network.crypta.client.async.ClientContext;
import network.crypta.client.async.ClientPutCallback;
import network.crypta.keys.FreenetURI;
import network.crypta.node.RequestClient;
import network.crypta.support.api.Bucket;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Blocking adapter for asynchronous insert callbacks.
 *
 * <p>{@code PutWaiter} bridges the {@link ClientPutCallback} contract, which reports insert
 * progress via callbacks, to a simple blocking API that returns the final {@link FreenetURI} or
 * throws an {@link InsertException}. It is primarily used by higher-level helpers such as {@code
 * HighLevelSimpleClientImpl} to offer convenience methods that hide the asynchronous machinery from
 * callers. Typical usage is to construct a waiter, start a {@link BaseClientPutter} that targets
 * the waiter as its callback, and then invoke {@link #waitForCompletion()} on a caller-controlled
 * thread.
 *
 * <p>The instance records exactly one terminal outcome: either {@link #onSuccess(BaseClientPutter)}
 * or {@link #onFailure(InsertException, BaseClientPutter)}. Before a terminal callback arrives the
 * {@link #waitForCompletion()} method blocks the calling thread. Once a result is available,
 * subsequent calls to {@link #waitForCompletion()} return immediately with the same outcome. The
 * class performs no I/O on its own and simply mirrors the final state reported by the underlying
 * putter.
 *
 * <ul>
 *   <li>Stores the first generated {@link FreenetURI} and exposes it to callers on success.
 *   <li>Propagates insert failures and may rewrap them to attach a deterministic URI when known.
 *   <li>Ignores advisory callbacks such as {@link #onFetchable(BaseClientPutter)} while freeing
 *       metadata buckets in {@link #onGeneratedMetadata(Bucket, BaseClientPutter)}.
 *   <li>Is thread-safe for multiple waiters; all state transitions are synchronized on {@code
 *       this}.
 * </ul>
 *
 * @see ClientPutCallback
 * @see BaseClientPutter
 * @see network.crypta.client.HighLevelSimpleClientImpl
 */
public class PutWaiter implements ClientPutCallback {
  private static final Logger LOG = LoggerFactory.getLogger(PutWaiter.class);

  private boolean finished;
  private boolean succeeded;
  private FreenetURI uri;
  private InsertException error;
  final RequestClient client;

  /**
   * Creates a waiter bound to a specific {@link RequestClient} identity.
   *
   * <p>The supplied {@code client} is returned from {@link #getRequestClient()} and is used by the
   * scheduler to attribute the insert to a particular logical client or persistence group. The
   * waiter itself does not modify or interpret the client object; it simply exposes it so that
   * surrounding infrastructure can enforce quotas and policy while the insert is in flight. Each
   * {@code PutWaiter} instance is intended for a single insert operation.
   *
   * @param client non-null request client representing the owner of the insert; typically the
   *     {@code HighLevelSimpleClient} or similar component that initiated the request.
   */
  public PutWaiter(RequestClient client) {
    this.client = client;
  }

  /** {@inheritDoc} */
  @Override
  public synchronized void onSuccess(BaseClientPutter state) {
    succeeded = true;
    finished = true;
    notifyAll();
  }

  /** {@inheritDoc} */
  @Override
  public synchronized void onFailure(InsertException e, BaseClientPutter state) {
    error = e;
    finished = true;
    notifyAll();
  }

  /**
   * Records a generated URI for the insert.
   *
   * <p>The first non-null URI received via this callback is stored and later returned by {@link
   * #waitForCompletion()} if the insert succeeds. Additional calls that supply the same URI are
   * ignored. If a different URI is passed after one has already been recorded, the method logs a
   * warning but keeps the original value, preserving the single-URI invariant observed by callers.
   *
   * @param uri non-null {@link FreenetURI} generated by the insert pipeline; treated as immutable
   *     and suitable for later retrieval.
   * @param state originating {@link BaseClientPutter} associated with this insert; not inspected by
   *     this implementation but useful for diagnostics.
   */
  @Override
  public synchronized void onGeneratedURI(FreenetURI uri, BaseClientPutter state) {
    if (LOG.isDebugEnabled()) LOG.debug("URI: {}", uri);
    if (this.uri == null) this.uri = uri;
    if (uri.equals(this.uri)) return;
    LOG.warn("URI already set: {} but new URI: {}", this.uri, uri);
  }

  /**
   * Blocks until the insert completes and returns the final URI or throws on failure.
   *
   * <p>This method waits until one of {@link #onSuccess(BaseClientPutter)} or {@link
   * #onFailure(InsertException, BaseClientPutter)} has been invoked. It can be called from any
   * thread, including multiple threads concurrently; after the terminal outcome is known, all
   * callers return immediately with the same result. If the insert fails, the underlying {@link
   * InsertException} is rethrown. When the failure does not carry a URI but this waiter has
   * observed a deterministic URI, the exception is wrapped in a new {@code InsertException} that
   * preserves the original message while attaching the URI for diagnostics.
   *
   * <p>Interrupts of the waiting thread are detected and briefly recorded for logging purposes, but
   * do not change the outcome: the method continues to wait until the insert either succeeds or
   * fails. This keeps the reported result consistent with what actually happened on the network.
   *
   * @return the {@link FreenetURI} produced by a successful insert, or {@code null} when the insert
   *     protocol legitimately completes without a URI; the returned reference is the same instance
   *     observed via {@link #onGeneratedURI(FreenetURI, BaseClientPutter)}.
   * @throws InsertException if the insert fails for any reason, including internal errors; callers
   *     should inspect {@link InsertException#getMode()} and {@link InsertException#getUri()} to
   *     distinguish fatal conditions from transient ones and to obtain a deterministic URI when
   *     available.
   */
  public synchronized FreenetURI waitForCompletion() throws InsertException {
    while (!finished) {
      try {
        wait();
      } catch (InterruptedException e) {
        // Preserve interrupt status to satisfy analysis tools but continue waiting so that
        // callers observe the real terminal outcome of the insert. We then clear the flag
        // again so that subsequent wait() calls do not immediately rethrow.
        Thread.currentThread().interrupt();
        boolean wasInterrupted = Thread.interrupted();
        if (LOG.isDebugEnabled() && wasInterrupted) {
          LOG.debug("Interrupted while waiting for insert completion", e);
        }
      }
    }
    if (error != null) {
      if (error.getUri() == null && uri != null) {
        throw new InsertException(error, uri);
      }
      throw error;
    }
    if (succeeded) return uri;
    LOG.error("Did not succeed but no error");
    throw new InsertException(
        InsertExceptionMode.INTERNAL_ERROR, "Did not succeed but no error", uri);
  }

  /** {@inheritDoc} */
  @Override
  public void onFetchable(BaseClientPutter state) {
    // Ignore
  }

  /**
   * {@inheritDoc}
   *
   * <p>This implementation logs that unexpected metadata was generated for a put operation that is
   * being waited on synchronously and then immediately frees the {@link Bucket} to avoid leaking
   * resources. Callers relying on metadata delivery should use a different callback implementation.
   *
   * @param metadata metadata bucket produced by the insert pipeline; this implementation always
   *     frees the bucket and never retains it.
   * @param state originating {@link BaseClientPutter}, passed only for logging and correlation
   *     purposes; not inspected otherwise.
   */
  @Override
  public void onGeneratedMetadata(Bucket metadata, BaseClientPutter state) {
    LOG.warn("onGeneratedMetadata() on PutWaiter from {}", state);
    metadata.free();
  }

  /**
   * {@inheritDoc}
   *
   * <p>{@code PutWaiter} instances are intentionally non-persistent helpers and do not support
   * resuming across node restarts. As a result this method always throws {@link
   * UnsupportedOperationException}. Persistent insert workflows should rely on callback
   * implementations designed for resume semantics rather than this simple blocking adapter.
   *
   * @param context client context supplied by the node when attempting to resume a persistent
   *     request; ignored by this implementation.
   * @throws UnsupportedOperationException always thrown because this helper cannot participate in
   *     persistence or resume flows.
   */
  @Override
  public void onResume(ClientContext context) {
    throw new UnsupportedOperationException(); // Not persistent.
  }

  /**
   * Returns the {@link RequestClient} identity associated with this waiter.
   *
   * <p>The returned object is the same reference that was supplied to the constructor and is used
   * by schedulers and accounting code to group related requests, determine persistence behavior,
   * and apply quotas. {@code PutWaiter} never mutates the client object; callers may safely share a
   * single {@link RequestClient} instance across multiple waiters representing different inserts.
   *
   * @return non-null {@link RequestClient} representing the logical owner and persistence policy
   *     for the underlying insert associated with this waiter.
   */
  @Override
  public RequestClient getRequestClient() {
    return client;
  }
}
