[versions]
kotlin = "2.2.20"
coroutines = "1.10.2"
bcprov = "2.73.9"
jna = "5.17.0"
commonsCompress = "1.28.0"
pebble = "3.2.4"
unbescape = "1.1.6.RELEASE"
slf4j = "2.0.17"
mockito = "5.19.0"
hamcrest = "3.0"
objenesis = "3.4"
picocli = "4.7.7"
spotless = "8.0.0"
flatlaf = "3.6.1"
jsystemTheme = "ea2f8582ea"
dbusJava = "5.1.1"
junitJupiter = "5.13.4"
junitPlatform = "1.13.4"
sonarqube = "6.3.1.5724"

[libraries]
bcprov = { group = "org.bouncycastle", name = "bcprov-lts8on", version.ref = "bcprov" }
bcpkix = { group = "org.bouncycastle", name = "bcpkix-lts8on", version.ref = "bcprov" }
jna = { group = "net.java.dev.jna", name = "jna", version.ref = "jna" }
jnaPlatform = { group = "net.java.dev.jna", name = "jna-platform", version.ref = "jna" }
commonsCompress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commonsCompress" }
pebble = { group = "io.pebbletemplates", name = "pebble", version.ref = "pebble" }
unbescape = { group = "org.unbescape", name = "unbescape", version.ref = "unbescape" }
slf4jApi = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
mockitoCore = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
objenesis = { group = "org.objenesis", name = "objenesis", version.ref = "objenesis" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli" }
kotlinxCoroutinesSwing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }
flatlaf = { group = "com.formdev", name = "flatlaf", version.ref = "flatlaf" }
jsystemThemeDetector = { group = "com.github.Dansoftowner", name = "jSystemThemeDetector", version.ref = "jsystemTheme" }
dbusCore = { group = "com.github.hypfvieh", name = "dbus-java-core", version.ref = "dbusJava" }
dbusTransportNativeUnix = { group = "com.github.hypfvieh", name = "dbus-java-transport-native-unixsocket", version.ref = "dbusJava" }
junitJupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitJupiter" }
junitJupiterParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junitJupiter" }
junitJupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitJupiter" }
junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatform" }
junitPlatformSuite = { group = "org.junit.platform", name = "junit-platform-suite", version.ref = "junitPlatform" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
