package network.crypta.clients.fcp;

import network.crypta.support.SimpleFieldSet;

/**
 * Terminal marker message produced by the node when it has finished streaming persistent request
 * metadata to an FCP client.
 *
 * <p>The class is intentionally lightweight: it simply packages an optional identifier that ties
 * the terminating event to a prior {@code ListPersistentRequests} query. Instances are created by
 * the node side as soon as all pending entries have been enumerated, then serialized over the
 * connection using {@link #getFieldSet()}. Consumers typically watch for this message to know that
 * no more state is forthcoming, at which point they can release buffers, resume UI updates, or mark
 * pagination cursors as settled.
 *
 * <p>Although the message contains no mutable state, callers should treat it as a single-use
 * notification. Each instance belongs to the lifecycle of one logical listing operation and is not
 * meant for reuse across connections. The type is thread-safe because it holds only an immutable
 * identifier string and exposes no mutators.
 *
 * <ul>
 *   <li>Responsibilities: encode the identifier and advertise the canonical message name.
 *   <li>Limitations: never sent by clients; {@link #run(FCPConnectionHandler)} always throws.
 *   <li>Observability: the {@link #NAME} constant allows tests to verify correct wiring.
 * </ul>
 *
 * @see EndListPeersMessage
 */
public class EndListPersistentRequestsMessage extends FCPMessage {
  static final String NAME = "EndListPersistentRequests";
  private final String listRequestIdentifier;

  /**
   * Creates a completion marker tied to the supplied list request identifier.
   *
   * <p>The identifier should match the value provided in the corresponding plan or request. When it
   * is {@code null}, the message still serves as a terminator but skips binding to a particular
   * client-side token. The constructor performs no validation because identifiers are traditionally
   * generated by upstream components with their own rules. Reuse the same identifier only if the
   * client understands that multiple concurrent listings may share it and can disambiguate based on
   * connection ordering.
   *
   * @param listRequestIdentifier unique token supplied with {@code ListPersistentRequests}, or
   *     {@code null} to emit an anonymous completion notice.
   */
  public EndListPersistentRequestsMessage(String listRequestIdentifier) {
    this.listRequestIdentifier = listRequestIdentifier;
  }

  /**
   * Creates the wire representation that will be sent to peers via FCP.
   *
   * <p>The returned {@link SimpleFieldSet} always contains the {@code Identifier} key when
   * available so that downstream consumers can correlate the message with outstanding list
   * requests. No other fields are emitted, which keeps the payload compact yet unambiguous. The
   * caller receives a fresh {@code SimpleFieldSet} instance and may modify or serialize it without
   * affecting other recipients.
   *
   * <pre>{@code
   * SimpleFieldSet payload = message.getFieldSet();
   * connection.send(payload);
   * }</pre>
   *
   * @return a short-lived field set containing zero or one {@code Identifier} entry ready for
   *     transmission.
   */
  @Override
  public SimpleFieldSet getFieldSet() {
    SimpleFieldSet simpleFieldSet = new SimpleFieldSet(true);
    simpleFieldSet.putSingle("Identifier", listRequestIdentifier);
    return simpleFieldSet;
  }

  /**
   * Returns the canonical protocol name used when encoding the message header.
   *
   * <p>The value is stable across releases and matches the name expected by legacy Freenet clients,
   * enabling them to parse responses even when they do not understand newer features. Because the
   * name is constant, callers can use it for comparisons or logging without allocating additional
   * strings.
   *
   * @return the literal {@link #NAME} reference identifying this message type within FCP.
   */
  @Override
  public String getName() {
    return NAME;
  }

  /**
   * Rejects inbound execution attempts because the message flows from server to client only.
   *
   * <p>If a client erroneously submits this message, the node immediately raises a {@link
   * MessageInvalidException} with {@link ProtocolErrorMessage#INVALID_MESSAGE}. No node state is
   * touched, and the supplied {@code handler} receives no callbacks. This guard defends against
   * spoofed completion notices that could otherwise truncate legitimate listings.
   *
   * @param handler connection handler requesting execution; ignored because the call always fails.
   * @throws MessageInvalidException always thrown to signal protocol misuse by the client.
   */
  @Override
  public void run(FCPConnectionHandler handler) throws MessageInvalidException {
    throw new MessageInvalidException(
        ProtocolErrorMessage.INVALID_MESSAGE,
        "EndListPersistentRequests goes from server to client not the other way around",
        null,
        false);
  }
}
