"""Unified command-line interface for Cryptad release certification."""

from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
from pathlib import Path

from . import selftest
from .engines.stable_1_0_rc_core import SAME_RUN_INPUT_KEYS
from .legacy import execute as execute_engine
from .manifest import load_manifest
from .migration import execute as execute_migration
from .models import RunManifest
from .workspace import _require_confined_directory, prepare_context, prepare_run_root

COMMANDS = (
    "app-platform",
    "app-platform-docs",
    "network-scale-soak",
    "live-network-beta",
    "release-certification",
    "production-beta",
    "go-no-go",
    "stable-readiness",
    "stable-rc",
    "stable-ga",
    "stable-maintenance",
)
MULTI_NODE_ACTIONS = (
    "plan",
    "run",
    "verify",
    "previous-summary",
    "verify-previous-summary",
    "schema",
)
SECURITY_ACTIONS = (
    "verify",
    "drill-create",
    "drill-verify",
    "drill-run-all",
    "drill-verify-all",
    "advisory-template",
)
SELF_TEST_SUITES = (
    "all",
    "core",
    "app-platform",
    "app-platform-docs",
    "network-scale-soak",
    "live-network-beta",
    "multi-node-beta",
    "security-response",
    "release-certification",
    "production-beta",
    "go-no-go",
    "stable-readiness",
    "stable-rc",
    "stable-ga",
    "stable-maintenance",
    "migration",
)


def _add_run_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--manifest", type=Path, help="Versioned, non-secret release-run manifest.")
    parser.add_argument("--workspace-root", type=Path, default=Path.cwd())
    parser.add_argument("--out-root", type=Path)
    parser.add_argument("--self-test", action="store_true", help="Run this command's focused unittest suite.")


def build_parser() -> argparse.ArgumentParser:
    """Build the unified command tree."""

    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    for command in COMMANDS:
        child = subparsers.add_parser(command)
        _add_run_arguments(child)

    multi = subparsers.add_parser("multi-node-beta")
    _add_run_arguments(multi)
    multi.add_argument("action", nargs="?", choices=MULTI_NODE_ACTIONS)

    security = subparsers.add_parser("security-response")
    _add_run_arguments(security)
    security.add_argument("action", nargs="?", choices=SECURITY_ACTIONS)

    migration = subparsers.add_parser("migrate-v1")
    migration.add_argument("migration_kind", choices=("previous-candidate", "release-history"))
    migration.add_argument("--manifest", type=Path, required=True)
    migration.add_argument("--workspace-root", type=Path, default=Path.cwd())
    migration.add_argument("--out-root", type=Path)

    tests = subparsers.add_parser("self-test")
    tests.add_argument("suite", nargs="?", choices=SELF_TEST_SUITES, default="all")
    return parser


def _execute_component(
    workspace_root: Path,
    manifest: RunManifest,
    command: str,
    action: str | None = None,
) -> int:
    component = command if action is None else f"{command}/{action}"
    run_root = (manifest.output.root / manifest.release.release_id).resolve()
    component_dir = run_root / Path(component)
    _require_confined_directory(component_dir, run_root, "component")
    resolved_component = component_dir.resolve()
    try:
        resolved_component.relative_to(run_root)
    except ValueError as exc:
        raise ValueError(f"component path escapes the release workspace: {component}") from exc
    if component_dir.is_symlink():
        raise ValueError(f"refusing to replace a symlinked component directory: {component}")
    if component_dir.exists():
        if not component_dir.is_dir():
            raise ValueError(f"component output is not a directory: {component}")
        shutil.rmtree(component_dir)
    context = prepare_context(workspace_root, manifest, component)
    return execute_engine(context, command, action)


def _collect_release_evidence(workspace_root: Path, manifest: RunManifest) -> None:
    """Collect every candidate-scoped input formerly generated by the shell wrapper."""

    inputs = manifest.inputs
    if "appPlatform" not in inputs:
        _execute_component(workspace_root, manifest, "app-platform")
    if "networkScaleSoak" not in inputs:
        _execute_component(workspace_root, manifest, "network-scale-soak")
    if "multiNodeSoak" not in inputs:
        _execute_component(workspace_root, manifest, "multi-node-beta", "run")
    if "securityDrills" not in inputs:
        _execute_component(workspace_root, manifest, "security-response", "verify")
        _execute_component(workspace_root, manifest, "security-response", "drill-run-all")
        _execute_component(workspace_root, manifest, "security-response", "drill-verify-all")
    collect_live = (
        manifest.requirements.get("liveNetwork") is True
        or manifest.execution.get("collectLiveNetwork") is True
    )
    if collect_live and "liveNetwork" not in inputs:
        _execute_component(workspace_root, manifest, "live-network-beta")


def _require_pending_component(manifest: RunManifest, component: str) -> None:
    """Reject a completed component without creating or changing its directory."""

    run_root = (manifest.output.root / manifest.release.release_id).resolve()
    component_dir = run_root / Path(component)
    _require_confined_directory(component_dir, run_root, "component")
    summary = component_dir / "summary.json"
    if summary.is_symlink() or summary.exists():
        raise ValueError(
            f"component already has a summary; reset the run before rerunning: {component}"
        )


def _validate_stable_rc_manifest(manifest: RunManifest) -> None:
    """Reject Stable RC orchestration outside the protected Stable review profile."""

    if manifest.release.profile != "stable-review":
        raise ValueError("stable-rc requires release.profile stable-review")
    version = manifest.release.version
    if version is None or re.fullmatch(r"[1-9][0-9]*", version) is None:
        raise ValueError("stable-rc requires a canonical positive integer release.version")
    freeze_mode = manifest.policies.get("stableRcFreezeMode")
    has_previous_freeze = "previousStableRcFreeze" in manifest.inputs
    if freeze_mode not in {"first-freeze", "refreeze"}:
        raise ValueError(
            "stable-rc requires policies.stableRcFreezeMode first-freeze or refreeze"
        )
    if freeze_mode == "first-freeze" and has_previous_freeze:
        raise ValueError(
            "stable-rc first-freeze mode cannot include inputs.previousStableRcFreeze"
        )
    if freeze_mode == "refreeze" and not has_previous_freeze:
        raise ValueError(
            "stable-rc refreeze mode requires inputs.previousStableRcFreeze"
        )
    configured_same_run = [key for key in SAME_RUN_INPUT_KEYS if key in manifest.inputs]
    if configured_same_run:
        names = ", ".join(f"inputs.{key}" for key in configured_same_run)
        raise ValueError(
            "stable-rc generates production-beta and its promotion inputs in the same "
            f"protected run; externally supplied same-run inputs are not accepted: {names}"
        )


def _validate_stable_ga_manifest(manifest: RunManifest) -> None:
    """Reject Stable GA validation unless every immutable input is explicit."""

    if manifest.release.profile != "stable-review":
        raise ValueError("stable-ga requires release.profile stable-review")
    version = manifest.release.version
    if version is None or re.fullmatch(r"[1-9][0-9]*", version) is None:
        raise ValueError("stable-ga requires a canonical positive integer release.version")
    required_inputs = {
        "selectedStableRcSummary",
        "selectedStableRcFreeze",
        "selectedStableRcFreezeSidecar",
        "selectedStableRcArchive",
        "selectedStableRcProduct",
        "selectedStableRcChecksums",
        "selectedStableRcProvenance",
        "selectedStableRcLineage",
        "previousCandidate",
        "stableRcValidation",
        "stableGaPolicy",
    }
    missing = sorted(required_inputs.difference(manifest.inputs))
    if missing:
        raise ValueError(
            "stable-ga requires explicit immutable inputs: " + ", ".join(missing)
        )
    mode = manifest.commands.get("stable-ga", {}).get("mode", "validate-only")
    if mode not in {"validate-only", "prepare-authorization"}:
        raise ValueError(
            "stable-ga command mode must be validate-only or prepare-authorization"
        )
    if mode == "validate-only" and "stableGaAuthorization" not in manifest.inputs:
        raise ValueError("stable-ga validate-only requires inputs.stableGaAuthorization")
    if mode == "prepare-authorization" and "stableGaAuthorization" in manifest.inputs:
        raise ValueError(
            "stable-ga prepare-authorization must not include inputs.stableGaAuthorization"
        )
    if mode == "prepare-authorization" and "stableGaPublicationReceipt" in manifest.inputs:
        raise ValueError(
            "stable-ga prepare-authorization cannot verify a publication receipt"
        )
    expected_policies = {
        "catalogChannel": "stable",
        "publicationIntent": "prepare-explicit-protected-publication",
    }
    for field, expected in expected_policies.items():
        if manifest.policies.get(field) != expected:
            raise ValueError(f"stable-ga requires policies.{field} {expected}")
    commit = manifest.policies.get("candidateSourceCommit")
    if not isinstance(commit, str) or re.fullmatch(r"[0-9a-f]{40,64}", commit) is None:
        raise ValueError("stable-ga requires a canonical policies.candidateSourceCommit")
    source_ref = manifest.policies.get("candidateSourceRef")
    if source_ref != f"commit:{commit}":
        raise ValueError(
            "stable-ga requires policies.candidateSourceRef to be the selected immutable "
            "commit:<sha> identity"
        )
    previous_release = manifest.policies.get("expectedPreviousReleaseId")
    if not isinstance(previous_release, str) or not previous_release:
        raise ValueError("stable-ga requires policies.expectedPreviousReleaseId")
    previous_product = manifest.policies.get("expectedPreviousProductDigest")
    if not isinstance(previous_product, str) or re.fullmatch(
        r"sha256:[0-9a-f]{64}", previous_product
    ) is None:
        raise ValueError("stable-ga requires policies.expectedPreviousProductDigest")
    metadata = manifest.policies.get("metadata")
    required_metadata = {"catalogPrimaryUri", "catalogMirrorUris"}
    if not isinstance(metadata, dict) or not required_metadata.issubset(metadata):
        raise ValueError(
            "stable-ga requires public catalog primary and mirror URIs in policies.metadata"
        )


def _validate_stable_maintenance_manifest(manifest: RunManifest) -> None:
    """Reject Stable maintenance runs whose class, mode, or immutable inputs are ambiguous."""

    if manifest.release.profile != "stable-review":
        raise ValueError("stable-maintenance requires release.profile stable-review")
    version = manifest.release.version
    if version is None or re.fullmatch(r"[1-9][0-9]*", version) is None:
        raise ValueError(
            "stable-maintenance requires a canonical positive integer release.version"
        )
    release_class = manifest.policies.get("releaseClass")
    if release_class not in {"maintenance", "security-hotfix"}:
        raise ValueError(
            "stable-maintenance requires policies.releaseClass maintenance or security-hotfix"
        )
    expected_branch = f"{'release' if release_class == 'maintenance' else 'hotfix'}/{version}"
    if manifest.policies.get("candidateSourceBranch") != expected_branch:
        raise ValueError(
            f"stable-maintenance {release_class} requires policies.candidateSourceBranch "
            f"{expected_branch}"
        )
    commit = manifest.policies.get("candidateSourceCommit")
    if not isinstance(commit, str) or re.fullmatch(r"[0-9a-f]{40,64}", commit) is None:
        raise ValueError(
            "stable-maintenance requires a canonical policies.candidateSourceCommit"
        )
    if manifest.policies.get("candidateSourceRef") != f"commit:{commit}":
        raise ValueError(
            "stable-maintenance requires policies.candidateSourceRef to be commit:<sha>"
        )
    base_commit = manifest.policies.get("candidateBaseCommit")
    if (
        not isinstance(base_commit, str)
        or re.fullmatch(r"[0-9a-f]{40,64}", base_commit) is None
        or base_commit == commit
    ):
        raise ValueError(
            "stable-maintenance requires a distinct canonical policies.candidateBaseCommit"
        )
    if manifest.policies.get("catalogChannel") != "stable":
        raise ValueError("stable-maintenance requires policies.catalogChannel stable")
    if manifest.policies.get("publicationIntent") != (
        "prepare-explicit-protected-publication"
    ):
        raise ValueError(
            "stable-maintenance requires explicit protected publication intent"
        )
    required_inputs = {
        "stableGaPromotionSummary",
        "stableGaValidation",
        "stableGaAuthorizationSummary",
        "stableGaPublicationPlan",
        "stableGaPublicationReceipt",
        "stableGaChecksums",
        "stableGaProvenance",
        "stableGaMaintenanceBaseline",
        "predecessorPublicationReceipt",
        "predecessorBaseline",
        "maintenanceCandidate",
        "maintenanceCandidateFreeze",
        "maintenanceCandidateAssets",
        "maintenanceCandidateChecksums",
        "maintenanceCandidateProvenance",
        "maintenanceEvidence",
        "maintenancePolicy",
    }
    missing = sorted(required_inputs.difference(manifest.inputs))
    if missing:
        raise ValueError(
            "stable-maintenance requires explicit immutable inputs: "
            + ", ".join(missing)
        )
    mode = manifest.commands.get("stable-maintenance", {}).get(
        "mode", "validate-only"
    )
    allowed_modes = {
        "validate-only",
        "prepare-authorization",
        "close-hotfix-follow-up",
    }
    if mode not in allowed_modes:
        raise ValueError(
            "stable-maintenance command mode must be validate-only, "
            "prepare-authorization, or close-hotfix-follow-up"
        )
    has_authorization = "stableMaintenanceAuthorization" in manifest.inputs
    if mode == "prepare-authorization" and has_authorization:
        raise ValueError(
            "stable-maintenance prepare-authorization must not include authorization"
        )
    if mode == "prepare-authorization" and (
        "stableMaintenancePublicationReceipt" in manifest.inputs
        or "coreUpdatePublicationReceipt" in manifest.inputs
    ):
        raise ValueError(
            "stable-maintenance prepare-authorization cannot verify publication receipts"
        )
    if mode == "validate-only" and not has_authorization:
        raise ValueError(
            "stable-maintenance validate-only requires inputs.stableMaintenanceAuthorization"
        )
    if mode == "close-hotfix-follow-up":
        required_closure = {
            "stableMaintenanceAuthorization",
            "hotfixFollowUpObligation",
            "hotfixFollowUpEvidence",
        }
        missing_closure = sorted(required_closure.difference(manifest.inputs))
        if release_class != "security-hotfix" or missing_closure:
            raise ValueError(
                "stable-maintenance close-hotfix-follow-up requires security-hotfix and inputs: "
                + ", ".join(missing_closure)
            )
    receipt_inputs = {
        "stableMaintenancePublicationReceipt",
        "coreUpdatePublicationReceipt",
    }
    present_receipts = receipt_inputs.intersection(manifest.inputs)
    if present_receipts and present_receipts != receipt_inputs:
        raise ValueError(
            "stable-maintenance publication verification requires both maintenance and "
            "CoreUpdater receipts"
        )
    predecessor_build = manifest.policies.get("expectedPredecessorBuild")
    if (
        not isinstance(predecessor_build, str)
        or re.fullmatch(r"[1-9][0-9]*", predecessor_build) is None
        or (
            mode != "close-hotfix-follow-up"
            and int(version) <= int(predecessor_build)
        )
    ):
        raise ValueError(
            "stable-maintenance requires a canonical latest predecessor and a strictly "
            "higher release build outside follow-up closure"
        )


def _run_command(args: argparse.Namespace) -> int:
    command = str(args.command)
    if getattr(args, "self_test", False):
        return selftest.run(command)
    manifest_path = getattr(args, "manifest", None)
    if manifest_path is None:
        raise ValueError(f"{command} requires --manifest")
    workspace_root = args.workspace_root.resolve()
    manifest = load_manifest(manifest_path.resolve(), workspace_root, args.out_root)
    if command == "stable-rc":
        _validate_stable_rc_manifest(manifest)
    if command == "stable-ga":
        _validate_stable_ga_manifest(manifest)
    if command == "stable-maintenance":
        _validate_stable_maintenance_manifest(manifest)
    prepare_run_root(manifest)

    previous = Path.cwd()
    try:
        os.chdir(workspace_root)
        if command == "migrate-v1":
            component = f"migration/{args.migration_kind}"
            _require_pending_component(manifest, component)
            context = prepare_context(workspace_root, manifest, component)
            code = execute_migration(context, args.migration_kind)
        else:
            action = getattr(args, "action", None)
            if command in {"multi-node-beta", "security-response"} and action is None:
                raise ValueError(f"{command} requires an action unless --self-test is used")
            if command == "release-certification" and manifest.execution.get("collectEvidence") is True:
                _require_pending_component(manifest, "release-certification")
                _collect_release_evidence(workspace_root, manifest)
            if command == "stable-rc":
                _require_pending_component(manifest, "stable-rc")
                _execute_component(workspace_root, manifest, "production-beta")
            component = command if action is None else f"{command}/{action}"
            context = prepare_context(workspace_root, manifest, component)
            code = execute_engine(context, command, action)
    finally:
        os.chdir(previous)
    print(f"{command}: {context.component_dir / 'summary.json'}")
    return code


def main(argv: list[str] | None = None) -> int:
    """Run the unified CLI with sanitized error handling."""

    args = build_parser().parse_args(argv)
    try:
        if args.command == "self-test":
            return selftest.run(args.suite)
        return _run_command(args)
    except (OSError, ValueError) as exc:
        print(f"certify: {exc}", file=sys.stderr)
        return 2
