"""Unified command-line interface for Cryptad release certification."""

from __future__ import annotations

import argparse
import os
import shutil
import sys
from pathlib import Path

from . import selftest
from .legacy import execute as execute_engine
from .manifest import load_manifest
from .migration import execute as execute_migration
from .models import RunManifest
from .workspace import _require_confined_directory, prepare_context, prepare_run_root

COMMANDS = (
    "app-platform",
    "app-platform-docs",
    "network-scale-soak",
    "live-network-beta",
    "release-certification",
    "production-beta",
    "go-no-go",
    "stable-readiness",
)
MULTI_NODE_ACTIONS = (
    "plan",
    "run",
    "verify",
    "previous-summary",
    "verify-previous-summary",
    "schema",
)
SECURITY_ACTIONS = (
    "verify",
    "drill-create",
    "drill-verify",
    "drill-run-all",
    "drill-verify-all",
    "advisory-template",
)
SELF_TEST_SUITES = (
    "all",
    "core",
    "app-platform",
    "app-platform-docs",
    "network-scale-soak",
    "live-network-beta",
    "multi-node-beta",
    "security-response",
    "release-certification",
    "production-beta",
    "go-no-go",
    "stable-readiness",
    "migration",
)


def _add_run_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--manifest", type=Path, help="Versioned, non-secret release-run manifest.")
    parser.add_argument("--workspace-root", type=Path, default=Path.cwd())
    parser.add_argument("--out-root", type=Path)
    parser.add_argument("--self-test", action="store_true", help="Run this command's focused unittest suite.")


def build_parser() -> argparse.ArgumentParser:
    """Build the unified command tree."""

    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    for command in COMMANDS:
        child = subparsers.add_parser(command)
        _add_run_arguments(child)

    multi = subparsers.add_parser("multi-node-beta")
    _add_run_arguments(multi)
    multi.add_argument("action", nargs="?", choices=MULTI_NODE_ACTIONS)

    security = subparsers.add_parser("security-response")
    _add_run_arguments(security)
    security.add_argument("action", nargs="?", choices=SECURITY_ACTIONS)

    migration = subparsers.add_parser("migrate-v1")
    migration.add_argument("migration_kind", choices=("previous-candidate", "release-history"))
    migration.add_argument("--manifest", type=Path, required=True)
    migration.add_argument("--workspace-root", type=Path, default=Path.cwd())
    migration.add_argument("--out-root", type=Path)

    tests = subparsers.add_parser("self-test")
    tests.add_argument("suite", nargs="?", choices=SELF_TEST_SUITES, default="all")
    return parser


def _execute_component(
    workspace_root: Path,
    manifest: RunManifest,
    command: str,
    action: str | None = None,
) -> int:
    component = command if action is None else f"{command}/{action}"
    run_root = (manifest.output.root / manifest.release.release_id).resolve()
    component_dir = run_root / Path(component)
    _require_confined_directory(component_dir, run_root, "component")
    resolved_component = component_dir.resolve()
    try:
        resolved_component.relative_to(run_root)
    except ValueError as exc:
        raise ValueError(f"component path escapes the release workspace: {component}") from exc
    if component_dir.is_symlink():
        raise ValueError(f"refusing to replace a symlinked component directory: {component}")
    if component_dir.exists():
        if not component_dir.is_dir():
            raise ValueError(f"component output is not a directory: {component}")
        shutil.rmtree(component_dir)
    context = prepare_context(workspace_root, manifest, component)
    return execute_engine(context, command, action)


def _collect_release_evidence(workspace_root: Path, manifest: RunManifest) -> None:
    """Collect every candidate-scoped input formerly generated by the shell wrapper."""

    inputs = manifest.inputs
    if "appPlatform" not in inputs:
        _execute_component(workspace_root, manifest, "app-platform")
    if "networkScaleSoak" not in inputs:
        _execute_component(workspace_root, manifest, "network-scale-soak")
    if "multiNodeSoak" not in inputs:
        _execute_component(workspace_root, manifest, "multi-node-beta", "run")
    if "securityDrills" not in inputs:
        _execute_component(workspace_root, manifest, "security-response", "verify")
        _execute_component(workspace_root, manifest, "security-response", "drill-run-all")
        _execute_component(workspace_root, manifest, "security-response", "drill-verify-all")
    collect_live = (
        manifest.requirements.get("liveNetwork") is True
        or manifest.execution.get("collectLiveNetwork") is True
    )
    if collect_live and "liveNetwork" not in inputs:
        _execute_component(workspace_root, manifest, "live-network-beta")


def _require_pending_component(manifest: RunManifest, component: str) -> None:
    """Reject a completed component without creating or changing its directory."""

    run_root = (manifest.output.root / manifest.release.release_id).resolve()
    component_dir = run_root / Path(component)
    _require_confined_directory(component_dir, run_root, "component")
    summary = component_dir / "summary.json"
    if summary.is_symlink() or summary.exists():
        raise ValueError(
            f"component already has a summary; reset the run before rerunning: {component}"
        )


def _run_command(args: argparse.Namespace) -> int:
    command = str(args.command)
    if getattr(args, "self_test", False):
        return selftest.run(command)
    manifest_path = getattr(args, "manifest", None)
    if manifest_path is None:
        raise ValueError(f"{command} requires --manifest")
    workspace_root = args.workspace_root.resolve()
    manifest = load_manifest(manifest_path.resolve(), workspace_root, args.out_root)
    prepare_run_root(manifest)

    previous = Path.cwd()
    try:
        os.chdir(workspace_root)
        if command == "migrate-v1":
            component = f"migration/{args.migration_kind}"
            _require_pending_component(manifest, component)
            context = prepare_context(workspace_root, manifest, component)
            code = execute_migration(context, args.migration_kind)
        else:
            action = getattr(args, "action", None)
            if command in {"multi-node-beta", "security-response"} and action is None:
                raise ValueError(f"{command} requires an action unless --self-test is used")
            if command == "release-certification" and manifest.execution.get("collectEvidence") is True:
                _require_pending_component(manifest, "release-certification")
                _collect_release_evidence(workspace_root, manifest)
            component = command if action is None else f"{command}/{action}"
            context = prepare_context(workspace_root, manifest, component)
            code = execute_engine(context, command, action)
    finally:
        os.chdir(previous)
    print(f"{command}: {context.component_dir / 'summary.json'}")
    return code


def main(argv: list[str] | None = None) -> int:
    """Run the unified CLI with sanitized error handling."""

    args = build_parser().parse_args(argv)
    try:
        if args.command == "self-test":
            return selftest.run(args.suite)
        return _run_command(args)
    except (OSError, ValueError) as exc:
        print(f"certify: {exc}", file=sys.stderr)
        return 2
