package com.onionnetworks.fec;

import com.onionnetworks.util.Util;

/**
 * Implements a pure Java forward error correction code built on 8-bit symbols.
 *
 * <p>This implementation pairs {@link FECMath} with a precomputed encoding matrix to offer a
 * systematic code that mirrors Luigi Rizzo's reference C version. It is intended for situations
 * where native bindings are undesirable yet deterministic erasure coding is required, such as
 * replicating packets over unreliable transports. Instances are lightweight and reuse a shared
 * finite-field helper to minimize allocation overhead when creating multiple encoders.
 *
 * <p>The class focuses on bulk buffer processing: callers supply parallel arrays of packet data,
 * offsets, and indices, and the code writes results directly into caller-managed buffers rather
 * than allocating new ones. Callers must therefore ensure buffer sizing and alignment before
 * invocation. The code does not synchronize; use distinct instances per thread or coordinate access
 * externally when sharing buffers.
 *
 * <ul>
 *   <li>Systematic layout: indices {@code 0..k-1} reference original packets.
 *   <li>Parity generation: indices {@code k..n-1} derive repair packets via the encoding matrix.
 *   <li>In-place decode: reconstructed packets overwrite the provided packet array entries.
 * </ul>
 *
 * @author Justin F. Chapweske (justin@chapweske.com)
 * @see FECMath
 */
public class PureCode extends FECCode {

  /**
   * Shared finite-field math helper for 8-bit operations, reused across instances to avoid repeated
   * table generation while keeping arithmetic consistent with the reference implementation.
   */
  protected static final FECMath fecMath = new FECMath(8);

  /**
   * Encoding matrix arranged in row-major order, containing {@code n*k} coefficients used to build
   * repair symbols; treated as read-only after construction and shared across encode/decode calls.
   */
  protected char[] encMatrix;

  /**
   * Create a pure-code instance that computes its own encoding matrix for the supplied code
   * dimensions.
   *
   * <p>This constructor is a convenience for callers who only know the block layout and are
   * comfortable with the default matrix generated by {@link FECMath#createEncodeMatrix(int, int)}.
   * The resulting instance is systematic: the first {@code k} indices correspond to the original
   * packets and the remaining {@code n-k} indices produce repair packets. No validation is
   * performed beyond what {@link FECCode} enforces, so callers should ensure their parameters align
   * with the packet layout used throughout the application.
   *
   * @param k number of source packets per block; must be positive.
   * @param n total packets per block including {@code k} systematic originals.
   */
  public PureCode(int k, int n) {
    this(k, n, fecMath.createEncodeMatrix(k, n));
  }

  /**
   * Create a pure-code instance that uses the provided encoding matrix.
   *
   * <p>Callers supply a row-major matrix generated elsewhere, enabling deterministic reuse across
   * processes or serialization of the coding scheme. The matrix must contain exactly {@code n*k}
   * entries corresponding to packet indices {@code 0..n-1}, and it is consumed as-is without
   * copying, so subsequent external mutation would affect future encodes and decodes.
   *
   * @param k number of source packets per block; must be positive.
   * @param n total packets per block including {@code k} systematic originals.
   * @param encMatrix precomputed encoding matrix with {@code n*k} coefficients in row-major order.
   */
  public PureCode(int k, int n, char[] encMatrix) {
    super(k, n);
    this.encMatrix = encMatrix;
  }

  /**
   * Encode one or more repair packets in a single pass.
   *
   * <p>This helper iterates over the requested repair indices and delegates the heavy lifting to
   * the single-packet encoder. It assumes that the caller has sized the {@code repair} and {@code
   * repairOff} arrays to match the {@code index} array and that each corresponding entry references
   * a writable buffer of {@code packetLength} bytes. Source packets are never mutated; the method
   * clears each repair buffer before combining data according to the encoding matrix. Use this path
   * when generating multiple parity packets for the same block, as it avoids repeated setup and
   * keeps offset arrays in sync.
   *
   * @param src source packet array containing the systematic data buffers.
   * @param srcOff per-packet offsets into {@code src} buffers where payloads begin.
   * @param repair destination buffers that will receive encoded repair packets.
   * @param repairOff offsets inside each repair buffer where writing starts.
   * @param index indices for each repair packet; values {@code k..n-1} are expected.
   * @param packetLength number of bytes to read or write for every packet.
   */
  @Override
  protected void encode(
      byte[][] src, int[] srcOff, byte[][] repair, int[] repairOff, int[] index, int packetLength) {
    for (int i = 0; i < repair.length; i++) {
      encode(src, srcOff, repair[i], repairOff[i], index[i], packetLength);
    }
  }

  /**
   * Encode a single packet, producing either a systematic copy or a repair symbol.
   *
   * <p>When {@code index} falls below {@code k}, the method performs a direct copy from the
   * corresponding source buffer. For parity indices, it zeroes the repair buffer and iteratively
   * accumulates finite-field products of each source packet with the appropriate matrix
   * coefficient. Callers must ensure that all buffers contain at least {@code packetLength} bytes
   * from the supplied offsets. The method operates in place without synchronization and is safe for
   * reuse across multiple calls as long as different threads do not share mutable buffers.
   *
   * @param src source packet array containing the systematic data buffers.
   * @param srcOff per-packet offsets into {@code src} buffers where payloads begin.
   * @param repair destination buffer that will receive the encoded packet contents.
   * @param repairOff offset into {@code repair} where writing starts.
   * @param index packet index within the code block; {@code 0..n-1} accepted.
   * @param packetLength number of bytes to read or write for every packet.
   */
  protected void encode(
      byte[][] src, int[] srcOff, byte[] repair, int repairOff, int index, int packetLength) {
    // *remember* indices start at 0, k starts at 1.
    if (index < k) { // < k, systematic so direct copy.
      System.arraycopy(src[index], srcOff[index], repair, repairOff, packetLength);
    } else { // index >= k && index < n
      int pos = index * k;
      Util.bzero(repair, repairOff, packetLength);
      for (int i = 0; i < k; i++) {
        fecMath.addMul(
            repair, repairOff, src[i], srcOff[i], (byte) encMatrix[pos + i], packetLength);
      }
    }
  }

  /**
   * Reconstruct missing packets in place using the provided packet set and indices.
   *
   * <p>The method optionally shuffles the provided packet arrays so that the first {@code k} slots
   * correspond to the intended systematic indices. It then derives a decode matrix tailored to the
   * available packets, synthesizes any missing data into temporary buffers, and finally copies
   * reconstructed packets back into the caller-provided arrays while normalizing the {@code index}
   * array to {@code 0..k-1}. At least {@code k} distinct packets must be present for successful
   * recovery. Buffers are mutated in place, so callers should not reuse them concurrently without
   * external coordination.
   *
   * @param pkts packet buffers containing a mixture of systematic and repair data.
   * @param pktsOff offsets into each packet buffer where payload bytes begin.
   * @param index indices identifying the original position of each packet in the block.
   * @param packetLength number of payload bytes considered for decode operations.
   * @param shuffled set to {@code true} when {@code pkts} already matches index order.
   */
  @Override
  protected void decode(
      byte[][] pkts, int[] pktsOff, int[] index, int packetLength, boolean shuffled) {
    // This may be the second time shuffle has been called, if so
    // this is ok because it will quickly determine that things are in
    // order.  The previous shuffles may have been necessary to keep
    // another data structure in sync with the byte[]'s
    if (!shuffled) {
      shuffle(pkts, pktsOff, index, k);
    }

    char[] decMatrix = fecMath.createDecodeMatrix(encMatrix, index, k, n);

    // do the actual decoding.
    byte[][] tmpPkts = new byte[k][];
    for (int row = 0; row < k; row++) {
      if (index[row] >= k) {
        tmpPkts[row] = new byte[packetLength];
        for (int col = 0; col < k; col++) {
          fecMath.addMul(
              tmpPkts[row],
              0,
              pkts[col],
              pktsOff[col],
              (byte) decMatrix[row * k + col],
              packetLength);
        }
      }
    }

    // move pkts to their final destination
    for (int row = 0; row < k; row++) {
      if (index[row] >= k) { // only copy those actually decoded.
        System.arraycopy(tmpPkts[row], 0, pkts[row], pktsOff[row], packetLength);
        index[row] = row;
      }
    }
  }

  /**
   * Return a short diagnostic label that captures the code dimensions.
   *
   * <p>The string follows the pattern {@code PureCode[k=<k>,n=<n>]}, which helps log readers
   * quickly confirm the configured block sizes without inspecting state directly. The
   * representation is stable for a given instance and omits encoding matrix details, making it safe
   * for concise debugging output or user-facing status messages where a summary is sufficient.
   *
   * @return human-readable code summary showing {@code k} data and {@code n} total packets.
   */
  @Override
  public String toString() {
    return "PureCode[k=" + k + ",n=" + n + "]";
  }
}
