package network.crypta.platform.appui;

import java.time.Instant;
import java.util.Objects;

/**
 * Browser session issuance result containing the one-time bearer value for bootstrap JSON.
 *
 * <p>This is the narrow handoff object between the browser session issuer and the app-owned UI
 * bootstrap serializer. It is intentionally separate from {@link AppBrowserSession}: issuance must
 * expose the opaque bearer token once so browser code can place it in {@code X-Crypta-App-Session},
 * while verification should return only token-free identity metadata. Keeping those two shapes
 * distinct reduces the chance that Platform API routers, audit entries, or diagnostics accidentally
 * retain a credential.
 *
 * <p>The token is validated only for basic non-blank shape here. Entropy, uniqueness, lifetime, and
 * app binding are responsibilities of the issuer that creates the value. The diagnostic string
 * redacts the bearer text because this object can otherwise be tempting to log while debugging
 * bootstrap responses.
 */
public final class AppBrowserSessionIssue {
  private final String token;
  private final Instant expiresAt;

  /**
   * Creates one bootstrap-facing browser session issuance result.
   *
   * <p>The constructor is package-private so production code issues sessions through the store or a
   * test-controlled {@link AppBrowserSessionIssuer}. It accepts an already-generated opaque token
   * and its absolute expiry timestamp, then preserves them unchanged for serialization.
   *
   * @param token opaque bearer token that will be sent only in app UI bootstrap JSON
   * @param expiresAt UTC timestamp after which the bearer token must not authenticate
   * @throws IllegalArgumentException if the token is blank after caller-side generation
   * @throws NullPointerException if the token or expiry timestamp is {@code null}
   */
  AppBrowserSessionIssue(String token, Instant expiresAt) {
    if (Objects.requireNonNull(token, "token").isBlank()) {
      throw new IllegalArgumentException("token must not be blank");
    }
    this.token = token;
    this.expiresAt = Objects.requireNonNull(expiresAt, "expiresAt");
  }

  /**
   * Returns the opaque browser session token to place in the app-owned UI bootstrap response.
   *
   * <p>Callers should treat the returned value as a short-lived bearer credential. It belongs in
   * the bootstrap response body and then in the request header used by the browser SDK. It must not
   * be copied into logs, audit records, persistent browser storage, URLs, or general app summaries.
   *
   * @return URL-safe opaque bearer token generated by the session issuer
   */
  public String token() {
    return token;
  }

  /**
   * Returns the absolute session expiry timestamp.
   *
   * <p>The timestamp is metadata for browser code and tests; the server-side verifier remains
   * authoritative. A client may use this value to decide when to refresh or reload the app UI, but
   * successful authentication still depends on the backing session store accepting the bearer
   * token.
   *
   * @return UTC expiry timestamp associated with the issued bearer token
   */
  public Instant expiresAt() {
    return expiresAt;
  }

  /**
   * Returns redacted diagnostic text for this issuance result.
   *
   * <p>The expiry remains visible because it is useful for debugging session lifetime decisions.
   * The bearer token is never included, even in abbreviated form.
   *
   * @return diagnostic text that redacts the raw browser session token
   */
  @Override
  public String toString() {
    return "AppBrowserSessionIssue[token=[REDACTED], expiresAt=" + expiresAt + "]";
  }
}
