@encoding=UTF-8
# Use a wildcard to include all jars in lib, including cryptad.jar and dependencies
wrapper.java.classpath.1=lib/*
wrapper.java.additional.1=-Dnetworkaddress.cache.ttl=0
wrapper.java.additional.2=-Dnetworkaddress.cache.negative.ttl=0
wrapper.java.additional.3=-Djava.net.preferIPv4Stack=false
wrapper.java.additional.4=-Djava.io.tmpdir=./temp/
wrapper.java.additional.5=--enable-native-access=ALL-UNNAMED
wrapper.java.additional.6=--add-opens=java.base/java.lang=ALL-UNNAMED
wrapper.java.additional.7=--add-opens=java.base/java.util=ALL-UNNAMED
wrapper.java.additional.8=--add-opens=java.base/java.io=ALL-UNNAMED
wrapper.java.additional.9=-Xss512k
wrapper.java.additional.10=-enableassertions:freenet
wrapper.java.additional.11=--illegal-access=permit
wrapper.java.command=java
wrapper.working.dir=.
wrapper.jarfile=wrapper.jar
wrapper.java.mainclass=network.crypta.node.NodeStarter
wrapper.java.library.path.1=lib
wrapper.java.initmemory=60
wrapper.java.maxmemory=1536
wrapper.app.parameter.1=cryptad.ini
wrapper.console.format=PM
wrapper.console.loglevel=INFO
wrapper.logfile=wrapper.log
wrapper.logfile.format=LPTM
wrapper.logfile.loglevel=INFO
wrapper.logfile.maxsize=2M
wrapper.logfile.maxfiles=3
wrapper.syslog.loglevel=NONE
wrapper.console.title=Crypta
wrapper.jvm_exit.timeout=120
wrapper.restart.reload_configuration=TRUE
wrapper.filter.trigger.1=java.lang.OutOfMemoryError
wrapper.filter.action.1=RESTART
wrapper.restart.delay=5
wrapper.anchorfile=Crypta.anchor
wrapper.anchor.poll_interval=1

# Use PIPE to avoid some problems with firewalls etc
wrapper.backend.type=PIPE
