package network.crypta.runtime.alerts;

import java.util.Iterator;
import java.util.Map;
import network.crypta.runtime.alerts.feed.BasicUserAlertFeedEvent;
import network.crypta.runtime.alerts.feed.UserAlertFeedEvent;
import network.crypta.support.HTMLNode;

/**
 * Base class for user alerts that keep a live collection of related, dismissible events.
 *
 * <p>This type stores events in a shared {@link Map} and provides common behavior to render a
 * combined HTML view, emit a runtime-owned feed event, and coordinate dismissal. Subclasses
 * typically add the domain-specific fields that describe a single event and implement {@link
 * #getEventText()} and {@link #getEventHTMLText()} to produce textual and structured HTML
 * representations respectively.
 *
 * <p>The backing collection is supplied by the caller and is not copied. This class synchronizes on
 * that map when iterating and mutating it, so all accesses performed here are serialized against
 * the same monitor. Callers should avoid mutating the map from other locations without using the
 * same synchronization strategy. Instances are otherwise immutable with respect to their
 * descriptive metadata; only the shared map’s contents change over time.
 *
 * <p>Typical usage is to construct a subclass instance for a new event, put it in the shared map
 * under a stable key, and rely on the framework to query {@link #getHTMLText()} for an aggregated
 * view or call {@link #onDismiss()} to clear the collection. Dismissal cascades to each stored
 * event via {@link #onEventDismiss()}, allowing a subclass to release resources or unregister
 * listeners before removal.
 *
 * <ul>
 *   <li>Aggregates HTML for all stored events in the order reported by the map.
 *   <li>Builds a minimal feed event from the plain-text representation.
 *   <li>Removes all events on dismissing, invoking per-event cleanup hooks.
 * </ul>
 *
 * @param <T> the concrete subtype, enabling type-safe storage of homogeneous events
 * @see AbstractUserEvent
 * @see network.crypta.support.HTMLNode
 */
public abstract class StoringUserEvent<T extends StoringUserEvent<T>> extends AbstractUserEvent {

  /**
   * Backing collection of currently active events indexed by an implementation-defined key.
   *
   * <p>The map is owned externally but accessed by this instance inside synchronized blocks using
   * the map object as the monitor. Implementations should ensure the same synchronization
   * discipline is used when mutating the map elsewhere. Keys are expected to be stable identifiers;
   * values are instances of the concrete subtype parameter {@code T}.
   */
  protected final Map<String, T> events;

  /**
   * Convenience constructor for subclasses that supply only the storage map and configure the
   * remaining metadata elsewhere.
   *
   * <p>The supplied map is not defensively copied. This instance will synchronize with it when
   * iterating or removing elements. Passing a non-null, consistently used map is required for
   * correct behavior.
   *
   * @param events storage of active events; must be non-null and stable for the lifetime of this
   *     instance; ownership remains with the caller
   */
  @SuppressWarnings("unused")
  protected StoringUserEvent(Map<String, T> events) {
    this.events = events;
  }

  /**
   * Constructor that accepts a consolidated event description and the backing map.
   *
   * @param details bundled event presentation and dismissal metadata
   * @param events storage of active events; must be non-null; synchronized on by this instance
   */
  protected StoringUserEvent(UserEventDetails details, Map<String, T> events) {
    super(details);
    this.events = events;
  }

  /**
   * Returns the plain-text representation for this single-stored event instance.
   *
   * <p>Implementations should return a human-readable description suitable for logs, feed entries,
   * and other plain-text channels. The text should not contain HTML markup and should be reasonably
   * concise to fit compact UI surfaces. The returned value is used as the title and body in the
   * generated feed event.
   *
   * @return descriptive text for this event instance; never includes HTML tags
   */
  public abstract String getEventText();

  /**
   * Returns the structured HTML node for this single event instance.
   *
   * <p>The node is inserted as a direct child of the container generated by {@link #getHTMLText()}.
   * Implementations should avoid expensive tree construction on every call and may reuse immutable
   * nodes where appropriate. Callers must not modify the returned node after it has been handed to
   * the rendering pipeline.
   *
   * @return an {@link HTMLNode} representing this event’s HTML content; never {@code null}
   */
  public abstract HTMLNode getEventHTMLText();

  /**
   * {@inheritDoc}
   *
   * <p>This implementation aggregates the HTML for all currently stored events by appending each
   * event’s {@link #getEventHTMLText()} as a child of a container {@code div}. Iteration and access
   * are synchronized on the shared {@link #events} map to maintain a consistent snapshot during
   * rendering.
   */
  @Override
  public HTMLNode getHTMLText() {
    HTMLNode text = new HTMLNode("div");
    synchronized (events) {
      for (StoringUserEvent<T> event : events.values()) {
        text.addChild(event.getEventHTMLText());
      }
    }
    return text;
  }

  /**
   * {@inheritDoc}
   *
   * <p>This implementation builds a minimal feed event using the same text for the subject,
   * summary, and body. Priority and update time are taken from this event’s metadata.
   */
  @Override
  public UserAlertFeedEvent getFeedEvent() {
    return new BasicUserAlertFeedEvent(
        getEventText(), getEventText(), getEventText(), getPriorityClass(), getUpdatedTime());
  }

  /**
   * {@inheritDoc}
   *
   * <p>This implementation iterates over the stored events, invoking {@link #onEventDismiss()} on
   * each and removing it from the backing map within the same synchronized block. The operation is
   * best-effort and proceeds through all entries.
   */
  @Override
  public void onDismiss() {
    synchronized (events) {
      for (Iterator<T> iter = events.values().iterator(); iter.hasNext(); ) {
        T event = iter.next();
        event.onEventDismiss();
        iter.remove();
      }
    }
  }

  /**
   * {@inheritDoc}
   *
   * <p>The event is considered valid while the backing {@link #events} map is non-empty. The check
   * is performed under synchronization with the same monitor used for mutations.
   */
  @Override
  public boolean isValid() {
    boolean valid;
    synchronized (events) {
      valid = !events.isEmpty();
    }
    return valid;
  }

  /**
   * Cleanup hook invoked when this individual event is being dismissed.
   *
   * <p>Subclasses should release resources, unregister any listeners, or update the related state
   * so the event can be safely discarded. Implementations should be idempotent and must not throw
   * unchecked exceptions; failures should be handled internally where possible.
   */
  public abstract void onEventDismiss();
}
