package network.crypta.clients.http;

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import network.crypta.client.HighLevelSimpleClient;
import network.crypta.l10n.NodeL10n;
import network.crypta.node.NodeClientCore;
import network.crypta.support.HTMLNode;

/**
 * Toadlet that allows the local HTTP UI to pick a directory for saving downloads.
 *
 * <p>The toadlet renders a directory browser rooted at the node's configured download locations and
 * exposes submission controls that hand the chosen path back to higher-level download flows. It
 * keeps all behavior stateless and defers validation to {@link NodeClientCore} so multiple HTTP
 * requests can be served concurrently without locking or per-request allocation beyond the form
 * nodes themselves. Typical usage pairs the toadlet with bulk-download pages or FProxy handlers
 * that need a user-confirmed destination before fetching content, while still preserving the
 * calling page's query parameters through {@link #persistenceFields(Map)}. The class is effectively
 * immutable after construction and reuses the same localization strings for every request.
 *
 * <ul>
 *   <li>Responsibilities: render directory selection controls and persist download-related form
 *       state between navigation steps.
 *   <li>Thread-safety: stateless; safe for reuse across concurrent HTTP requests.
 *   <li>Lifecycle: created during HTTP layer initialization and retained as a shared handler.
 * </ul>
 */
public class LocalDownloadDirectoryToadlet extends LocalDirectoryToadlet {

  private static final String BULK_DOWNLOADS = "bulkDownloads";
  private static final String FILTER_DATA = "filterData";

  LocalDownloadDirectoryToadlet(
      NodeClientCore core, HighLevelSimpleClient highLevelSimpleClient, String post) {
    super(core, highLevelSimpleClient, post);
  }

  /**
   * Returns the directory that should appear first when the browser view opens.
   *
   * <p>The implementation delegates to {@link #defaultDownloadDir()} so the initial listing always
   * reflects the node's download directory policy: it prefers the configured default when downloads
   * are unrestricted and otherwise selects the first explicitly allowed directory. The value is
   * resolved without touching the filesystem beyond reading configuration data and is therefore
   * safe to call for every request. Because the result may point outside the user's home directory
   * when administrators restrict paths, callers should not assume it is user-writable beyond the
   * validation performed later by {@link #allowedDir(File)}.
   *
   * @return absolute directory path used as the starting context for the download browser; never
   *     {@code null} but may require further permission checks.
   */
  @Override
  protected String startingDir() {
    return defaultDownloadDir();
  }

  /**
   * Verifies that a candidate download directory is permitted by node policy.
   *
   * <p>The method defers to {@link NodeClientCore#allowDownloadTo(File)} so directory validation
   * remains consistent with the rest of the HTTP UI and command-line tools. It performs no
   * normalization itself, allowing the core to enforce canonicalization, drive-space rules, or any
   * sandboxing constraints. The result is deterministic for a given path and configuration and is
   * safe for repeated invocation during navigation or form submission handling.
   *
   * @param path absolute or canonical directory path proposed by the user interface; must not be
   *     {@code null} and should reference an existing directory.
   * @return {@code true} when the path is within the configured download allowlist and passes core
   *     validation; {@code false} otherwise.
   */
  @Override
  protected boolean allowedDir(File path) {
    return core.allowDownloadTo(path);
  }

  /**
   * Provides the form field name used to carry a selected directory path between requests.
   *
   * <p>Using a constant field identifier keeps the local download workflow aligned with other
   * directory-selection toadlets, simplifying handler code that extracts the posted value. The name
   * is intentionally short and stable because it is embedded in hidden fields generated by {@link
   * #createSelectDirectoryButton(HTMLNode, String, HTMLNode)} and propagated by {@link
   * #persistenceFields(Map)}. No localization or encoding is applied here; callers are responsible
   * for sanitizing user-visible echoes of the value if needed.
   *
   * @return literal field name {@code "path"} expected by downstream handlers when reading the
   *     selected directory.
   */
  @Override
  protected String filenameField() {
    return "path";
  }

  /**
   * Adds a localized submit control that posts the currently viewed directory as the selection.
   *
   * <p>The method injects a submit button labeled with {@link NodeL10n#getBase()} text, a hidden
   * field containing the directory path under {@link #filenameField()}, and any persistent form
   * fields supplied by the caller. It performs no validation of {@code path} beyond embedding it in
   * the generated inputs, relying on later handlers to call {@link #allowedDir(File)} before
   * writing to disk. Invocation is idempotent for identical arguments, making it safe to call from
   * templating code that may render multiple similar controls.
   *
   * <pre>{@code
   * // Example: attach a selection button beneath a directory listing row
   * createSelectDirectoryButton(row, directory.getAbsolutePath(), hiddenState);
   * }</pre>
   *
   * @param formNode HTML container to receive the submit and hidden inputs; must not be {@code
   *     null}.
   * @param path absolute directory path to post back when the button is pressed; must not be empty.
   * @param persist collection of hidden persistence nodes to append unchanged; callers should build
   *     this via {@link #persistenceFields(Map)}.
   */
  @Override
  protected void createSelectDirectoryButton(HTMLNode formNode, String path, HTMLNode persist) {
    formNode.addChild(
        "input",
        new String[] {"type", "name", "value"},
        new String[] {"submit", SELECT_DIR, NodeL10n.getBase().getString("QueueToadlet.download")});
    formNode.addChild(
        "input",
        new String[] {"type", "name", "value"},
        new String[] {"hidden", filenameField(), path});
    formNode.addChild(persist);
  }

  /**
   * Builds a set of hidden fields that preserve context across directory-browsing requests.
   *
   * <p>The helper copies only the parameters relevant to download flows: bulk-download submissions
   * retain the original marker and force an insert-to-disk action, whereas FProxy-driven requests
   * keep the key plus download flags. It also propagates {@code filterData} when present so list
   * filtering survives navigation. The returned map is safe to reuse for multiple form renderings
   * and omits unrelated parameters to avoid leaking stale state between workflows.
   *
   * @param set request parameter map obtained from the current navigation step; values are read but
   *     never modified.
   * @return new map containing only the persistence-relevant key/value pairs to include as hidden
   *     inputs in subsequent forms.
   */
  @Override
  protected Map<String, String> persistenceFields(Map<String, String> set) {
    Map<String, String> fieldPairs = new HashMap<>();
    // From bulk downloads, set download button.
    if (set.containsKey(BULK_DOWNLOADS)) {
      fieldPairs.put(BULK_DOWNLOADS, set.get(BULK_DOWNLOADS));
      fieldPairs.put("insert", "1");
      fieldPairs.put("target", "disk");
      // From FProxy page, set download button.
    } else if (set.containsKey("key")) {
      fieldPairs.put("key", set.get("key"));
      fieldPairs.put("download", "1");
      fieldPairs.put("return-type", "disk");
    }

    if (set.containsKey(FILTER_DATA)) fieldPairs.put(FILTER_DATA, set.get(FILTER_DATA));
    return fieldPairs;
  }
}
