package network.crypta.clients.http;

import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import network.crypta.client.HighLevelSimpleClient;
import network.crypta.l10n.NodeL10n;
import network.crypta.node.NodeClientCore;
import network.crypta.support.HTMLNode;
import network.crypta.support.SizeUtil;
import network.crypta.support.api.HTTPRequest;

/**
 * Provides shared rendering and flow control for toadlets that let users browse local files and
 * directories before posting a selection back to a handler. Subclasses supply the public HTTP path
 * and a target URI for completed selections while this base class manages listing, navigation, and
 * redirect logic that respects node directory restrictions and localization keys.
 *
 * <p>Use this type when an HTTP UI needs to prompt the operator for a local file or directory
 * (upload destinations, download targets, plugin storage, and similar flows). The instance keeps
 * the last successful directory so subsequent visits open nearby locations, and it renders only
 * readable, allowed entries. It assumes the surrounding toadlet infrastructure provides per-request
 * threading and authorization; the class itself is not synchronized and should not be shared across
 * concurrent mutation without external guarding.
 *
 * <ul>
 *   <li>Constructs localized infobox-style listings with navigation controls and size metadata.
 *   <li>Persists caller-provided parameters via hidden inputs generated by {@link
 *       #persistenceFields(Map)}.
 *   <li>Redirects immediately after a selection to the URI returned by {@link #postTo()}.
 * </ul>
 *
 * @author David 'Bombe' Roden &lt;bombe@freenetproject.org&gt;
 * @version $Id$
 */
public abstract class LocalFileBrowserToadlet extends Toadlet {

  /**
   * Node client core used to derive allowed upload/download directories and to resolve default
   * starting points for new browser sessions. The reference is immutable after construction and is
   * expected to enforce any necessary synchronization or permission checks externally.
   */
  protected final NodeClientCore core;

  private static final int MAX_POST_SIZE = 1024 * 1024;
  private static final String INPUT = "input";
  private static final String VALUE = "value";
  private static final String SUBMIT = "submit";
  private static final String HIDDEN = "hidden";
  private static final String CLASS = "class";
  private static final String INSERT_LOCAL_FILE_FORM = "insertLocalFileForm";
  private static final String LISTING_TITLE_KEY = "listingTitle";
  private static final String DIR_ACCESS_DENIED_KEY = "dirAccessDenied";
  private static final String FORBIDDEN_TITLE = "Forbidden";

  /**
   * Creates a browser toadlet that renders listings and redirects selections using the supplied
   * core services.
   *
   * <p>The constructor wires the immutable dependencies required for directory permission checks
   * and HTTP response handling. It does not perform I/O or validation beyond storing references, so
   * the surrounding wiring code should ensure the arguments are fully initialized and safe to reuse
   * across concurrent requests.
   *
   * @param core node client core that exposes allowed directories and download defaults; must not
   *     be {@code null}.
   * @param highLevelSimpleClient HTTP client passed to the {@link Toadlet} base for responding to
   *     user requests; must not be {@code null}.
   */
  protected LocalFileBrowserToadlet(
      NodeClientCore core, HighLevelSimpleClient highLevelSimpleClient) {
    super(highLevelSimpleClient);
    this.core = core;
  }

  /**
   * Returns the HTTP path that exposes this browser toadlet.
   *
   * <p>Subclasses usually map this to a user-facing URL segment so the toadlet can be reached via a
   * form or hyperlink. The returned path must remain consistent across requests so persisted form
   * posts continue to resolve correctly.
   *
   * @return absolute or context-relative path used by the surrounding HTTP server to dispatch
   *     requests to this toadlet.
   */
  @Override
  public abstract String path();

  /**
   * Provides the URI to which the user should be redirected after a successful selection.
   *
   * <p>Implementations typically point to the handler that consumes the chosen file or directory.
   * The URI is passed directly into {@link RedirectException}, so it should already include any
   * required query parameters or path prefixes and be valid for the current HTTP context.
   *
   * @return URI string that accepts the selection POST/GET once navigation completes.
   */
  protected abstract String postTo();

  /**
   * Last directory from which an action was performed. If accessible, this value is reused as the
   * starting point for subsequent requests to keep the navigation flow localized around the user's
   * most recent activity. It is not persisted beyond the lifetime of the toadlet instance.
   */
  private File lastSuccessful;

  /**
   * Form field name submitted when a directory is explicitly selected. Public so callers generating
   * auxiliary UI can mirror the same contract and have their forms interpreted by the toadlet's
   * selection logic.
   */
  public static final String SELECT_DIR = "select-dir";

  /**
   * Form field name submitted when a regular file is selected. External components may use this
   * constant to create compatible selection controls that trigger the redirect handled by {@link
   * #postTo()}.
   */
  public static final String SELECT_FILE = "select-file";

  /**
   * Form field name submitted when the user requests navigation into another directory. Keeping the
   * constant public enables consistent handling between server-rendered controls and custom caller
   * additions.
   */
  public static final String CHANGE_DIR = "change-dir";

  /**
   * Returns the request parameter name that carries the selected file or directory.
   *
   * <p>Subclasses may override this when they need to embed the selection into a different form
   * field layout. The name is used for both GET parameters and POST parts.
   *
   * @return parameter name that stores the absolute path of the current selection.
   */
  protected String filenameField() {
    return "filename";
  }

  /**
   * Indicates whether the provided directory may be browsed or selected by this toadlet.
   *
   * <p>Typical implementations consult node configuration (upload/download whitelists) and possibly
   * user roles to prevent exposing restricted paths.
   *
   * @param path directory to validate; expected to be canonical or at least non-null.
   * @return {@code true} when browsing and selection are allowed; otherwise selection buttons and
   *     navigation links will be omitted.
   */
  protected abstract boolean allowedDir(File path);

  /**
   * Performs any required validation and returns a map of request parameters to persist across
   * navigation steps.
   *
   * <p>Subclasses can filter, normalize, or inject additional context (such as CSRF tokens or user
   * identifiers) before the fields are transformed into hidden inputs. The returned map should be
   * safe to echo back to the client and small enough to fit within typical form limits.
   *
   * @param set parameters or parts from the current HTTP request; may be empty but not {@code null}
   *     in typical flows.
   * @return map of key/value pairs that should be serialized into hidden inputs for subsequent
   *     requests so caller context is preserved.
   */
  protected abstract Map<String, String> persistenceFields(Map<String, String> set);

  /**
   * Determines the default directory to display when no explicit path is provided.
   *
   * <p>Implementations should consider the most likely operator intent and keep the location within
   * the allowed directory set to avoid immediate access errors. The value is used only when the
   * requester has not provided a path and no recent successful directory is remembered.
   *
   * <p>The method should consider allowed directory rules and pick a sensible starting point for
   * the specific browser use case (for example, download destinations vs. upload sources).
   *
   * @return absolute path of the directory to render first when the request does not supply one.
   */
  protected abstract String startingDir();

  /**
   * Computes a starting directory when the user is browsing for a file to upload.
   *
   * <p>The helper first checks whether uploads are unrestricted or unspecified and falls back to
   * the user's home directory for familiarity. When explicit upload directories are configured, it
   * chooses the first entry, assuming the configuration is already ordered by preference.
   *
   * @return user's home directory when uploads are globally allowed or unspecified; otherwise the
   *     first explicitly allowed upload directory.
   */
  protected String defaultUploadDir() {
    if ((core.getAllowedUploadDirs().length == 1
            && core.getAllowedUploadDirs()[0].toString().equals("all"))
        || core.getAllowedUploadDirs().length == 0) {
      /* If all directories are allowed, or none are, go for the home directory.
       * If none are allowed, any directory will result in an error anyway.
       */
      return System.getProperty("user.home");
    }
    // If locations are explicitly specified take the first one.
    return core.getAllowedUploadDirs()[0].getAbsolutePath();
  }

  /**
   * Computes a starting directory when browsing for a destination to download into.
   *
   * <p>The helper mirrors {@link #defaultUploadDir()} but uses download directory settings. It
   * avoids accessing the filesystem beyond reading configuration values, keeping initialization
   * lightweight while still producing a stable, canonical starting point.
   *
   * @return node's default download directory when downloads are globally allowed or unspecified;
   *     otherwise the first explicitly allowed download directory.
   */
  protected String defaultDownloadDir() {
    if ((core.getAllowedDownloadDirs().length == 1
            && core.getAllowedDownloadDirs()[0].toString().equals("all"))
        || core.getAllowedDownloadDirs().length == 0) {
      /* If all directories are allowed, or none are, go for the default download directory.
       * If none are allowed, any directory will result in an error anyway.
       */
      return core.getDownloadsDir().getAbsolutePath();
    }
    // If locations are explicitly specified take the first one.
    return core.getAllowedDownloadDirs()[0].getAbsolutePath();
  }

  /**
   * Renders a button that selects the specified directory and posts it using {@link #SELECT_DIR}.
   * The method injects hidden fields for the current selection and any persisted parameters so
   * callers receive a complete context after redirection.
   *
   * @param node parent HTML node to attach the form inputs to; must not be {@code null}.
   * @param absolutePath absolute directory path to place into {@link #filenameField()}.
   * @param persistence container holding hidden persistence fields generated by {@link
   *     #persistenceFields(Map)}.
   */
  protected void createSelectDirectoryButton(
      HTMLNode node, String absolutePath, HTMLNode persistence) {
    node.addChild(
        INPUT,
        new String[] {"type", "name", VALUE},
        new String[] {SUBMIT, SELECT_DIR, l10n("insert")});
    node.addChild(
        INPUT,
        new String[] {"type", "name", VALUE},
        new String[] {HIDDEN, filenameField(), absolutePath});
    node.addChild(persistence);
  }

  /**
   * Renders a button that selects the given file and posts it using {@link #SELECT_FILE}. Hidden
   * persistence inputs are appended so subsequent handlers receive the preserved context.
   *
   * @param node parent HTML node where the controls are added; must be non-null.
   * @param absolutePath absolute file path to place into {@link #filenameField()}.
   * @param persistence container holding hidden persistence fields generated by {@link
   *     #persistenceFields(Map)}.
   */
  protected void createSelectFileButton(HTMLNode node, String absolutePath, HTMLNode persistence) {
    node.addChild(
        INPUT,
        new String[] {"type", "name", VALUE},
        new String[] {SUBMIT, SELECT_FILE, l10n("insert")});
    node.addChild(
        INPUT,
        new String[] {"type", "name", VALUE},
        new String[] {HIDDEN, filenameField(), absolutePath});
    node.addChild(persistence);
  }

  /**
   * Renders directory changing button with changeDir and filenameField() set.
   *
   * @param node Node to add the button to.
   * @param path Path to set the "path" field to.
   * @param persistence Additional persistence fields to include.
   */
  private void createChangeDirButton(
      HTMLNode node, String buttonText, String path, HTMLNode persistence) {
    node.addChild(
        INPUT, new String[] {"type", "name", VALUE}, new String[] {SUBMIT, CHANGE_DIR, buttonText});
    node.addChild(INPUT, new String[] {"type", "name", VALUE}, new String[] {HIDDEN, "path", path});
    node.addChild(persistence);
  }

  /**
   * Returns a Hashtable of all URL parameters.
   *
   * @param request contains URL parameters
   * @return Hashtable of all GET params.
   */
  private Map<String, String> readGET(HTTPRequest request) {
    Map<String, String> set = new HashMap<>();
    for (String key : request.getParameterNames()) {
      set.put(key, request.getParam(key));
    }
    return set;
  }

  /**
   * Returns a Hashtable of all POST parts up to a length of 1024*1024 characters.
   *
   * @param request contains POST parts
   * @return set a Hashtable of all POST parts.
   */
  private Map<String, String> readPOST(HTTPRequest request) {
    Map<String, String> set = new HashMap<>();
    for (String key : request.getParts()) {
      set.put(key, request.getPartAsStringFailsafe(key, MAX_POST_SIZE));
    }
    return set;
  }

  /**
   * Renders hidden fields.
   *
   * @param fieldPairs Pairs of values to be rendered
   * @return result HTMLNode containing hidden persistence fields
   */
  private HTMLNode renderPersistenceFields(Map<String, String> fieldPairs) {
    HTMLNode result = new HTMLNode("div", "id", "persistenceFields");
    for (Map.Entry<String, String> entry : fieldPairs.entrySet()) {
      result.addChild(
          INPUT,
          new String[] {"type", "name", VALUE},
          new String[] {HIDDEN, entry.getKey(), entry.getValue()});
    }
    return result;
  }

  private String selectedValue(HTTPRequest request) {
    if (request.isParameterSet(filenameField())
        && (request.isParameterSet(SELECT_DIR) || request.isParameterSet(SELECT_FILE))) {
      // Request is a GET.
      return request.getParam(filenameField());
    } else if (request.isPartSet(filenameField())
        && (request.isPartSet(SELECT_DIR) || request.isPartSet(SELECT_FILE))) {
      // Request is a POST.
      return request.getPartAsStringFailsafe(filenameField(), MAX_POST_SIZE);
    }
    return null;
  }

  /**
   * Handles GET requests by reading query parameters, rendering the directory listing, or
   * redirecting immediately if a selection is present. The URI parameter is validated only for
   * nullity; all navigation state comes from the request fields and persisted form data.
   *
   * @param uri request URI; must not be {@code null} but otherwise unused by this handler.
   * @param request HTTP request carrying query parameters such as {@code path} and {@link
   *     #filenameField()}.
   * @param ctx toadlet context used for permission checks, localization, and response rendering;
   *     must be open.
   * @throws ToadletContextClosedException when the connection has been closed before the reply is
   *     written.
   * @throws IOException if reading the filesystem or writing the response fails.
   * @throws RedirectException when a selection triggers an immediate redirect to {@link #postTo()}.
   * @see Toadlet#findSupportedMethods()
   * @see ToadletContext
   */
  @Override
  public void handleMethodGET(URI uri, HTTPRequest request, final ToadletContext ctx)
      throws ToadletContextClosedException, IOException, RedirectException {
    Objects.requireNonNull(uri);
    renderPage(
        persistenceFields(readGET(request)), request.getParam("path"), ctx, selectedValue(request));
  }

  /**
   * Handles POST requests by reading multipart form parts, rendering the directory listing, or
   * redirecting once a file or directory has been selected. This entry point mirrors {@link
   * #handleMethodGET(URI, HTTPRequest, ToadletContext)} but pulls data from POST parts to
   * accommodate larger payloads.
   *
   * @param uri request URI; validated for nullity only.
   * @param request HTTP request containing multipart parts such as {@code path} and {@link
   *     #filenameField()} with selection data.
   * @param ctx toadlet context that provides permission checks, localization, and HTML rendering.
   * @throws ToadletContextClosedException if the context closes before the response is produced.
   * @throws IOException on filesystem access errors or response write failures.
   * @throws RedirectException when a valid selection is detected and the user must be redirected.
   */
  public void handleMethodPOST(URI uri, HTTPRequest request, final ToadletContext ctx)
      throws ToadletContextClosedException, IOException, RedirectException {
    Objects.requireNonNull(uri);
    renderPage(
        persistenceFields(readPOST(request)),
        request.getPartAsStringFailsafe("path", MAX_POST_SIZE),
        ctx,
        selectedValue(request));
  }

  /**
   * Presents a file selection screen, or a something has been selected notes its directory and
   * redirects to the POST target.
   *
   * @param fieldPairs fields which are to be persisted between views
   * @param path current path to display
   * @param ctx context used for rendering
   * @param filename a filename if a file or directory is selected, NULL if not.
   * @throws ToadletContextClosedException if the context is closed before the response is written.
   * @throws IOException if reading the filesystem or writing the response fails.
   * @throws RedirectException when a valid selection triggers redirection to {@link #postTo()}.
   */
  private void renderPage(
      Map<String, String> fieldPairs, String path, final ToadletContext ctx, String filename)
      throws ToadletContextClosedException, IOException, RedirectException {
    HTMLNode persistenceFields = renderPersistenceFields(fieldPairs);

    if (redirectIfSelection(filename, ctx)) {
      return;
    }

    String effectivePath = resolvePath(path);
    File currentPath = new File(effectivePath).getCanonicalFile();
    String attemptedPath = currentPath.getAbsolutePath();

    if (!allowedDir(currentPath)) {
      sendForbidden(ctx, attemptedPath);
      return;
    }

    PageNode page = buildPage(currentPath, attemptedPath, persistenceFields, ctx);
    if (page == null) {
      return; // error response already sent
    }
    writeHTMLReply(ctx, 200, "OK", page.generate());
  }

  private PageNode buildPage(
      File currentPath, String attemptedPath, HTMLNode persistenceFields, ToadletContext ctx)
      throws IOException, ToadletContextClosedException {
    PageMaker pageMaker = ctx.getPageMaker();
    if (isReadableDirectory(currentPath)) {
      return buildDirectoryPage(currentPath, persistenceFields, ctx, pageMaker);
    }
    return buildUnreadablePage(attemptedPath, ctx, pageMaker);
  }

  private PageNode buildDirectoryPage(
      File currentPath, HTMLNode persistenceFields, ToadletContext ctx, PageMaker pageMaker)
      throws IOException, ToadletContextClosedException {
    PageNode page =
        pageMaker.getPageNode(l10nWithPath(LISTING_TITLE_KEY, currentPath.getAbsolutePath()), ctx);
    HTMLNode contentNode = page.getContentNode();
    if (ctx.isAllowedFullAccess()) contentNode.addChild(ctx.getAlertManager().createSummary());

    HTMLNode listingDiv = addListingContainer(currentPath, contentNode);
    File[] files = currentPath.listFiles();

    if (files == null) {
      sendErrorPage(ctx, 403, FORBIDDEN_TITLE, l10n(DIR_ACCESS_DENIED_KEY));
      return null;
    }

    Arrays.sort(files, this::compareFiles);

    HTMLNode listingTable = listingDiv.addChild("table", CLASS, "directory-listing");
    addHeaderRow(listingTable);
    addRootRows(listingTable, persistenceFields, ctx);
    addBackLinkRow(currentPath, listingTable, persistenceFields, ctx);
    addFileRows(files, listingTable, persistenceFields, ctx);
    return page;
  }

  private HTMLNode addListingContainer(File currentPath, HTMLNode contentNode) {
    HTMLNode infoboxDiv = contentNode.addChild("div", CLASS, "infobox");
    infoboxDiv.addChild(
        "div", CLASS, "infobox-header", l10nWithPath("listing", currentPath.getAbsolutePath()));
    return infoboxDiv.addChild("div", CLASS, "infobox-content");
  }

  private void addHeaderRow(HTMLNode listingTable) {
    HTMLNode headerRow = listingTable.addChild("tr");
    headerRow.addChild("th");
    headerRow.addChild("th", l10n("fileHeader"));
    headerRow.addChild("th", l10n("sizeHeader"));
  }

  private void addRootRows(HTMLNode listingTable, HTMLNode persistenceFields, ToadletContext ctx)
      throws IOException {
    for (File currentRoot : File.listRoots()) {
      if (!allowedDir(currentRoot)) {
        continue;
      }
      HTMLNode rootRow = listingTable.addChild("tr");
      rootRow.addChild("td");
      HTMLNode rootLinkCellNode = rootRow.addChild("td");
      HTMLNode rootLinkFormNode =
          ctx.addFormChild(rootLinkCellNode, path(), INSERT_LOCAL_FILE_FORM);
      createChangeDirButton(
          rootLinkFormNode,
          currentRoot.getCanonicalPath(),
          currentRoot.getAbsolutePath(),
          persistenceFields);
      rootRow.addChild("td");
    }
  }

  private void addBackLinkRow(
      File currentPath, HTMLNode listingTable, HTMLNode persistenceFields, ToadletContext ctx) {
    File parentFile = currentPath.getParentFile();
    if (parentFile == null || !allowedDir(parentFile)) {
      return;
    }
    HTMLNode backlinkRow = listingTable.addChild("tr");
    backlinkRow.addChild("td");
    HTMLNode backLinkCellNode = backlinkRow.addChild("td");
    HTMLNode backLinkFormNode = ctx.addFormChild(backLinkCellNode, path(), INSERT_LOCAL_FILE_FORM);
    createChangeDirButton(backLinkFormNode, "..", currentPath.getParent(), persistenceFields);
    backlinkRow.addChild("td");
  }

  private void addFileRows(
      File[] files, HTMLNode listingTable, HTMLNode persistenceFields, ToadletContext ctx) {
    for (File currentFile : files) {
      if (currentFile.isHidden()) {
        continue;
      }
      HTMLNode fileRow = listingTable.addChild("tr");
      if (currentFile.isDirectory()) {
        addDirectoryRow(currentFile, fileRow, persistenceFields, ctx);
      } else {
        addRegularFileRow(currentFile, fileRow, persistenceFields, ctx);
      }
    }
  }

  private void addDirectoryRow(
      File currentFile, HTMLNode fileRow, HTMLNode persistenceFields, ToadletContext ctx) {
    if (!currentFile.canRead()) {
      fileRow.addChild("td");
      fileRow.addChild("td", CLASS, "unreadable-file", currentFile.getName());
      fileRow.addChild("td");
      return;
    }

    if (allowedDir(currentFile)) {
      HTMLNode cellNode = fileRow.addChild("td");
      HTMLNode formNode = ctx.addFormChild(cellNode, path(), INSERT_LOCAL_FILE_FORM);

      createSelectDirectoryButton(formNode, currentFile.getAbsolutePath(), persistenceFields);

      HTMLNode directoryCellNode = fileRow.addChild("td");
      HTMLNode directoryFormNode =
          ctx.addFormChild(directoryCellNode, path(), INSERT_LOCAL_FILE_FORM);
      createChangeDirButton(
          directoryFormNode,
          currentFile.getName(),
          currentFile.getAbsolutePath(),
          persistenceFields);
    }

    fileRow.addChild("td");
  }

  private void addRegularFileRow(
      File currentFile, HTMLNode fileRow, HTMLNode persistenceFields, ToadletContext ctx) {
    if (currentFile.canRead()) {
      HTMLNode cellNode = fileRow.addChild("td");
      HTMLNode formNode = ctx.addFormChild(cellNode, path(), INSERT_LOCAL_FILE_FORM);
      createSelectFileButton(formNode, currentFile.getAbsolutePath(), persistenceFields);

      fileRow.addChild("td", currentFile.getName());
      fileRow.addChild("td", CLASS, "right-align", SizeUtil.formatSize(currentFile.length(), true));
      return;
    }

    fileRow.addChild("td");
    fileRow.addChild("td", CLASS, "unreadable-file", currentFile.getName());
    fileRow.addChild("td", CLASS, "right-align", SizeUtil.formatSize(currentFile.length(), true));
  }

  private PageNode buildUnreadablePage(
      String attemptedPath, ToadletContext ctx, PageMaker pageMaker) {
    PageNode page = pageMaker.getPageNode(l10nWithPath(LISTING_TITLE_KEY, attemptedPath), ctx);
    HTMLNode contentNode = page.getContentNode();
    if (ctx.isAllowedFullAccess()) contentNode.addChild(ctx.getAlertManager().createSummary());

    HTMLNode infoboxDiv = contentNode.addChild("div", CLASS, "infobox");
    infoboxDiv.addChild("div", CLASS, "infobox-header", l10nWithPath("listing", attemptedPath));
    HTMLNode listingDiv = infoboxDiv.addChild("div", CLASS, "infobox-content");

    listingDiv.addChild("#", l10nWithPath("dirCannotBeRead", attemptedPath));
    HTMLNode ulNode = listingDiv.addChild("ul");
    ulNode.addChild("li", l10n("checkPathExist"));
    ulNode.addChild("li", l10n("checkPathIsDir"));
    ulNode.addChild("li", l10n("checkPathReadable"));
    return page;
  }

  private int compareFiles(File firstFile, File secondFile) {
    if (firstFile.isDirectory() && !secondFile.isDirectory()) {
      return -1;
    }
    if (!firstFile.isDirectory() && secondFile.isDirectory()) {
      return 1;
    }
    return firstFile.getName().compareToIgnoreCase(secondFile.getName());
  }

  private boolean redirectIfSelection(String filename, ToadletContext ctx)
      throws RedirectException, ToadletContextClosedException, IOException {
    if (filename == null) {
      return false;
    }

    File file = new File(filename);
    if (file.isDirectory()) {
      lastSuccessful = file.getAbsoluteFile();
    } else {
      lastSuccessful = Objects.requireNonNull(file.getParentFile()).getAbsoluteFile();
    }

    try {
      throw new RedirectException(postTo());
    } catch (URISyntaxException e) {
      sendErrorPage(
          ctx,
          500,
          NodeL10n.getBase().getString("Toadlet.internalErrorPleaseReport"),
          e.getMessage());
    }
    return true;
  }

  private String resolvePath(String path) {
    if (path == null || path.isEmpty()) {
      if (lastSuccessful != null && lastSuccessful.isDirectory() && allowedDir(lastSuccessful)) {
        return lastSuccessful.getAbsolutePath();
      }
      return startingDir();
    }
    return path;
  }

  private boolean isReadableDirectory(File currentPath) {
    return currentPath.exists() && currentPath.isDirectory() && currentPath.canRead();
  }

  private void sendForbidden(ToadletContext ctx, String attemptedPath)
      throws ToadletContextClosedException, IOException {
    PageNode page =
        ctx.getPageMaker().getPageNode(l10nWithPath(LISTING_TITLE_KEY, attemptedPath), ctx);
    ctx.getPageMaker()
        .getInfobox("infobox-error", FORBIDDEN_TITLE, page.getContentNode(), "access-denied", true)
        .addChild("#", l10n(DIR_ACCESS_DENIED_KEY));

    sendErrorPage(ctx, 403, FORBIDDEN_TITLE, l10n(DIR_ACCESS_DENIED_KEY));
  }

  private String l10nWithPath(String key, String value) {
    return NodeL10n.getBase()
        .getString("LocalFileInsertToadlet." + key, new String[] {"path"}, new String[] {value});
  }

  private static String l10n(String msg) {
    return NodeL10n.getBase().getString("LocalFileInsertToadlet." + msg);
  }
}
